// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module merge_sort_hls_merge_sort_hls_Pipeline_merge_a_to_b_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        indvars_iv16,
        k_4,
        j_7,
        right_r,
        buffer_b_address0,
        buffer_b_ce0,
        buffer_b_we0,
        buffer_b_d0,
        buffer_a_address0,
        buffer_a_ce0,
        buffer_a_q0,
        buffer_a_address1,
        buffer_a_ce1,
        buffer_a_q1,
        buffer_a_address2,
        buffer_a_ce2,
        buffer_a_q2
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] indvars_iv16;
input  [31:0] k_4;
input  [31:0] j_7;
input  [31:0] right_r;
output  [5:0] buffer_b_address0;
output   buffer_b_ce0;
output   buffer_b_we0;
output  [31:0] buffer_b_d0;
output  [5:0] buffer_a_address0;
output   buffer_a_ce0;
input  [31:0] buffer_a_q0;
output  [5:0] buffer_a_address1;
output   buffer_a_ce1;
input  [31:0] buffer_a_q1;
output  [5:0] buffer_a_address2;
output   buffer_a_ce2;
input  [31:0] buffer_a_q2;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln36_fu_155_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [63:0] sext_ln36_fu_127_p1;
reg  signed [63:0] sext_ln36_reg_252;
reg   [63:0] k_2_reg_257;
reg   [63:0] k_2_reg_257_pp0_iter2_reg;
reg   [31:0] j_3_reg_263;
reg   [31:0] i_4_reg_269;
wire   [0:0] icmp_ln39_fu_160_p2;
reg   [0:0] icmp_ln39_reg_278;
reg   [0:0] icmp_ln39_reg_278_pp0_iter2_reg;
wire   [0:0] icmp_ln39_1_fu_165_p2;
reg   [0:0] icmp_ln39_1_reg_282;
reg   [0:0] icmp_ln39_1_reg_282_pp0_iter2_reg;
reg   [31:0] buffer_a_load_reg_296;
wire   [0:0] take_left_fu_191_p2;
reg   [0:0] take_left_reg_301;
wire   [63:0] zext_ln39_fu_170_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln39_1_fu_175_p1;
wire   [63:0] zext_ln44_fu_207_p1;
wire   [5:0] buffer_b_addr_gep_fu_118_p3;
reg   [63:0] k_fu_32;
wire   [63:0] add_ln36_fu_180_p2;
wire    ap_loop_init;
reg   [31:0] j_fu_36;
wire   [31:0] j_4_fu_211_p2;
reg   [31:0] ap_sig_allocacmp_j_3;
reg   [31:0] i_fu_40;
wire   [31:0] i_5_fu_197_p2;
reg   [31:0] ap_sig_allocacmp_i_4;
reg    buffer_a_ce2_local;
reg    buffer_a_ce1_local;
reg    buffer_a_ce0_local;
reg    buffer_b_we0_local;
reg   [31:0] buffer_b_d0_local;
reg    buffer_b_ce0_local;
reg   [5:0] buffer_b_address0_local;
wire  signed [31:0] sext_ln36_fu_127_p0;
wire  signed [31:0] icmp_ln39_1_fu_165_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_181;
reg    ap_condition_188;
reg    ap_condition_321;
reg    ap_condition_324;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 k_fu_32 = 64'd0;
#0 j_fu_36 = 32'd0;
#0 i_fu_40 = 32'd0;
#0 ap_done_reg = 1'b0;
end

merge_sort_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            i_fu_40 <= k_4;
        end else if ((1'b1 == ap_condition_321)) begin
            i_fu_40 <= i_5_fu_197_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            j_fu_36 <= j_7;
        end else if ((1'b1 == ap_condition_324)) begin
            j_fu_36 <= j_4_fu_211_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_32 <= indvars_iv16;
        end else if (((icmp_ln36_fu_155_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            k_fu_32 <= add_ln36_fu_180_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        i_4_reg_269 <= ap_sig_allocacmp_i_4;
        icmp_ln39_1_reg_282 <= icmp_ln39_1_fu_165_p2;
        icmp_ln39_reg_278 <= icmp_ln39_fu_160_p2;
        j_3_reg_263 <= ap_sig_allocacmp_j_3;
        k_2_reg_257 <= k_fu_32;
        sext_ln36_reg_252 <= sext_ln36_fu_127_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_a_load_reg_296 <= buffer_a_q2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln39_1_reg_282_pp0_iter2_reg <= icmp_ln39_1_reg_282;
        icmp_ln39_reg_278_pp0_iter2_reg <= icmp_ln39_reg_278;
        k_2_reg_257_pp0_iter2_reg <= k_2_reg_257;
        take_left_reg_301 <= take_left_fu_191_p2;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_155_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((icmp_ln39_1_reg_282 == 1'd0) & (icmp_ln39_reg_278 == 1'd1)) | ((take_left_fu_191_p2 == 1'd0) & (icmp_ln39_reg_278 == 1'd1))))) begin
        ap_sig_allocacmp_i_4 = i_5_fu_197_p2;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_40;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & ((icmp_ln39_reg_278 == 1'd0) | ((take_left_fu_191_p2 == 1'd1) & (icmp_ln39_1_reg_282 == 1'd1))))) begin
        ap_sig_allocacmp_j_3 = j_4_fu_211_p2;
    end else begin
        ap_sig_allocacmp_j_3 = j_fu_36;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buffer_a_ce0_local = 1'b1;
    end else begin
        buffer_a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_a_ce1_local = 1'b1;
    end else begin
        buffer_a_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_a_ce2_local = 1'b1;
    end else begin
        buffer_a_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((1'b1 == ap_condition_188)) begin
            buffer_b_address0_local = buffer_b_addr_gep_fu_118_p3;
        end else if ((1'b1 == ap_condition_181)) begin
            buffer_b_address0_local = k_2_reg_257_pp0_iter2_reg;
        end else begin
            buffer_b_address0_local = 'bx;
        end
    end else begin
        buffer_b_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & ((icmp_ln39_reg_278_pp0_iter2_reg == 1'd0) | ((take_left_reg_301 == 1'd1) & (icmp_ln39_1_reg_282_pp0_iter2_reg == 1'd1)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (((icmp_ln39_1_reg_282_pp0_iter2_reg == 1'd0) & (icmp_ln39_reg_278_pp0_iter2_reg == 1'd1)) | ((take_left_reg_301 == 1'd0) & (icmp_ln39_reg_278_pp0_iter2_reg == 1'd1)))))) begin
        buffer_b_ce0_local = 1'b1;
    end else begin
        buffer_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((1'b1 == ap_condition_188)) begin
            buffer_b_d0_local = buffer_a_q0;
        end else if ((1'b1 == ap_condition_181)) begin
            buffer_b_d0_local = buffer_a_load_reg_296;
        end else begin
            buffer_b_d0_local = 'bx;
        end
    end else begin
        buffer_b_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & ((icmp_ln39_reg_278_pp0_iter2_reg == 1'd0) | ((take_left_reg_301 == 1'd1) & (icmp_ln39_1_reg_282_pp0_iter2_reg == 1'd1)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (((icmp_ln39_1_reg_282_pp0_iter2_reg == 1'd0) & (icmp_ln39_reg_278_pp0_iter2_reg == 1'd1)) | ((take_left_reg_301 == 1'd0) & (icmp_ln39_reg_278_pp0_iter2_reg == 1'd1)))))) begin
        buffer_b_we0_local = 1'b1;
    end else begin
        buffer_b_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln36_fu_180_p2 = (k_fu_32 + 64'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_181 = (((icmp_ln39_1_reg_282_pp0_iter2_reg == 1'd0) & (icmp_ln39_reg_278_pp0_iter2_reg == 1'd1)) | ((take_left_reg_301 == 1'd0) & (icmp_ln39_reg_278_pp0_iter2_reg == 1'd1)));
end

always @ (*) begin
    ap_condition_188 = ((icmp_ln39_reg_278_pp0_iter2_reg == 1'd0) | ((take_left_reg_301 == 1'd1) & (icmp_ln39_1_reg_282_pp0_iter2_reg == 1'd1)));
end

always @ (*) begin
    ap_condition_321 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((icmp_ln39_1_reg_282 == 1'd0) & (icmp_ln39_reg_278 == 1'd1)) | ((take_left_fu_191_p2 == 1'd0) & (icmp_ln39_reg_278 == 1'd1))));
end

always @ (*) begin
    ap_condition_324 = ((ap_enable_reg_pp0_iter2 == 1'b1) & ((icmp_ln39_reg_278 == 1'd0) | ((take_left_fu_191_p2 == 1'd1) & (icmp_ln39_1_reg_282 == 1'd1))));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign buffer_a_address0 = zext_ln44_fu_207_p1;

assign buffer_a_address1 = zext_ln39_1_fu_175_p1;

assign buffer_a_address2 = zext_ln39_fu_170_p1;

assign buffer_a_ce0 = buffer_a_ce0_local;

assign buffer_a_ce1 = buffer_a_ce1_local;

assign buffer_a_ce2 = buffer_a_ce2_local;

assign buffer_b_addr_gep_fu_118_p3 = k_2_reg_257_pp0_iter2_reg;

assign buffer_b_address0 = buffer_b_address0_local;

assign buffer_b_ce0 = buffer_b_ce0_local;

assign buffer_b_d0 = buffer_b_d0_local;

assign buffer_b_we0 = buffer_b_we0_local;

assign i_5_fu_197_p2 = (i_4_reg_269 + 32'd1);

assign icmp_ln36_fu_155_p2 = (($signed(k_fu_32) < $signed(sext_ln36_reg_252)) ? 1'b1 : 1'b0);

assign icmp_ln39_1_fu_165_p1 = right_r;

assign icmp_ln39_1_fu_165_p2 = (($signed(ap_sig_allocacmp_j_3) < $signed(icmp_ln39_1_fu_165_p1)) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_160_p2 = (($signed(ap_sig_allocacmp_i_4) < $signed(j_7)) ? 1'b1 : 1'b0);

assign j_4_fu_211_p2 = (j_3_reg_263 + 32'd1);

assign sext_ln36_fu_127_p0 = right_r;

assign sext_ln36_fu_127_p1 = sext_ln36_fu_127_p0;

assign take_left_fu_191_p2 = (($signed(buffer_a_q2) > $signed(buffer_a_q1)) ? 1'b1 : 1'b0);

assign zext_ln39_1_fu_175_p1 = ap_sig_allocacmp_j_3;

assign zext_ln39_fu_170_p1 = ap_sig_allocacmp_i_4;

assign zext_ln44_fu_207_p1 = j_3_reg_263;

endmodule //merge_sort_hls_merge_sort_hls_Pipeline_merge_a_to_b_loop
