

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "3", "5", "7", "8", "9", "10", "11"],
		"CDFG" : "merge_sort_offchip_hls",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_in", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_in_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_merge_sort_offchip_hls_Pipeline_copy_input_to_scratch_a_fu_232", "Port" : "gmem_in", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "gmem_scratch_a", "Type" : "MAXI", "Direction" : "IO",
				"BlockSignal" : [
					{"Name" : "gmem_scratch_a_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_scratch_a_blk_n_B", "Type" : "RtlSignal"},
					{"Name" : "gmem_scratch_a_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_merge_sort_offchip_hls_Pipeline_copy_input_to_scratch_a_fu_232", "Port" : "gmem_scratch_a", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "3", "SubInstance" : "grp_merge_sort_offchip_hls_Pipeline_merge_element_loop_fu_242", "Port" : "gmem_scratch_a", "Inst_start_state" : "18", "Inst_end_state" : "19"},
					{"ID" : "5", "SubInstance" : "grp_merge_sort_offchip_hls_Pipeline_copy_result_to_out_fu_260", "Port" : "gmem_scratch_a", "Inst_start_state" : "28", "Inst_end_state" : "29"}]},
			{"Name" : "gmem_scratch_b", "Type" : "MAXI", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_merge_sort_offchip_hls_Pipeline_merge_element_loop_fu_242", "Port" : "gmem_scratch_b", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "gmem_out", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_out_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_out_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_merge_sort_offchip_hls_Pipeline_copy_result_to_out_fu_260", "Port" : "gmem_out", "Inst_start_state" : "28", "Inst_end_state" : "29"}]},
			{"Name" : "in_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "scratch_a", "Type" : "None", "Direction" : "I"},
			{"Name" : "scratch_b", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_r", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "merge_block_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "34", "FirstState" : "ap_ST_fsm_state18", "LastState" : ["ap_ST_fsm_state19"], "QuitState" : ["ap_ST_fsm_state18"], "PreState" : ["ap_ST_fsm_state17"], "PostState" : ["ap_ST_fsm_state17"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "merge_width_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "34", "FirstState" : "ap_ST_fsm_state17", "LastState" : ["ap_ST_fsm_state18"], "QuitState" : ["ap_ST_fsm_state17"], "PreState" : ["ap_ST_fsm_state16"], "PostState" : ["ap_ST_fsm_state20"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_merge_sort_offchip_hls_Pipeline_copy_input_to_scratch_a_fu_232", "Parent" : "0", "Child" : ["2"],
		"CDFG" : "merge_sort_offchip_hls_Pipeline_copy_input_to_scratch_a",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "68", "EstimateLatencyMax" : "68",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_scratch_a", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_scratch_a_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "gmem_in", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_in_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln21_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln21", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "copy_input_to_scratch_a", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_merge_sort_offchip_hls_Pipeline_copy_input_to_scratch_a_fu_232.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_merge_sort_offchip_hls_Pipeline_merge_element_loop_fu_242", "Parent" : "0", "Child" : ["4"],
		"CDFG" : "merge_sort_offchip_hls_Pipeline_merge_element_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "indvars_iv14", "Type" : "None", "Direction" : "I"},
			{"Name" : "mid", "Type" : "None", "Direction" : "I"},
			{"Name" : "left_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_scratch_b", "Type" : "MAXI", "Direction" : "IO",
				"BlockSignal" : [
					{"Name" : "gmem_scratch_b_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_scratch_b_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_scratch_b_blk_n_B", "Type" : "RtlSignal"},
					{"Name" : "gmem_scratch_b_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_scratch_b_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "right_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_scratch_a", "Type" : "MAXI", "Direction" : "IO",
				"BlockSignal" : [
					{"Name" : "gmem_scratch_a_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_scratch_a_blk_n_R", "Type" : "RtlSignal"},
					{"Name" : "gmem_scratch_a_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_scratch_a_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_scratch_a_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "scratch_b", "Type" : "None", "Direction" : "I"},
			{"Name" : "source_is_a", "Type" : "None", "Direction" : "I"},
			{"Name" : "scratch_a", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "merge_element_loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "13", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage8", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage8_subdone", "QuitState" : "ap_ST_fsm_pp0_stage8", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage8_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_merge_sort_offchip_hls_Pipeline_merge_element_loop_fu_242.flow_control_loop_pipe_sequential_init_U", "Parent" : "3"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_merge_sort_offchip_hls_Pipeline_copy_result_to_out_fu_260", "Parent" : "0", "Child" : ["6"],
		"CDFG" : "merge_sort_offchip_hls_Pipeline_copy_result_to_out",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "67", "EstimateLatencyMax" : "67",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_out", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_out_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "gmem_scratch_a", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_scratch_a_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln21_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln72", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "copy_result_to_out", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_merge_sort_offchip_hls_Pipeline_copy_result_to_out_fu_260.flow_control_loop_pipe_sequential_init_U", "Parent" : "5"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_in_m_axi_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_out_m_axi_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_scratch_a_m_axi_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_scratch_b_m_axi_U", "Parent" : "0"}]}
