-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity read_write_write_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_mem_1_0_AWVALID : OUT STD_LOGIC;
    m_axi_mem_1_0_AWREADY : IN STD_LOGIC;
    m_axi_mem_1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_mem_1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mem_1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_mem_1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mem_1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mem_1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mem_1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mem_1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mem_1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mem_1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mem_1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mem_1_0_WVALID : OUT STD_LOGIC;
    m_axi_mem_1_0_WREADY : IN STD_LOGIC;
    m_axi_mem_1_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_mem_1_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_mem_1_0_WLAST : OUT STD_LOGIC;
    m_axi_mem_1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mem_1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mem_1_0_ARVALID : OUT STD_LOGIC;
    m_axi_mem_1_0_ARREADY : IN STD_LOGIC;
    m_axi_mem_1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_mem_1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mem_1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_mem_1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mem_1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mem_1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mem_1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mem_1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mem_1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mem_1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mem_1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mem_1_0_RVALID : IN STD_LOGIC;
    m_axi_mem_1_0_RREADY : OUT STD_LOGIC;
    m_axi_mem_1_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_mem_1_0_RLAST : IN STD_LOGIC;
    m_axi_mem_1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mem_1_0_RFIFONUM : IN STD_LOGIC_VECTOR (4 downto 0);
    m_axi_mem_1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mem_1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mem_1_0_BVALID : IN STD_LOGIC;
    m_axi_mem_1_0_BREADY : OUT STD_LOGIC;
    m_axi_mem_1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mem_1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_mem_1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    mem_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    mem_empty_n : IN STD_LOGIC;
    mem_read : OUT STD_LOGIC;
    mem_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    mem_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_1_empty_n : IN STD_LOGIC;
    stream_1_read : OUT STD_LOGIC;
    stream_1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of read_write_write_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv480_lc_1 : STD_LOGIC_VECTOR (479 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal first_iter_0_reg_456 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state4_io_grp2 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_subdone_grp2 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone_grp3_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_subdone_grp3 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln24_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage3 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal mem_1_blk_n_AW : STD_LOGIC;
    signal ap_block_pp0_stage3_grp2 : BOOLEAN;
    signal mem_1_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp4 : BOOLEAN;
    signal icmp_ln28_reg_465 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone_grp4_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal mem_1_blk_n_B : STD_LOGIC;
    signal ap_block_pp0_stage0_grp5 : BOOLEAN;
    signal icmp_ln26_reg_494 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone_grp5_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp5 : BOOLEAN;
    signal mem_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_grp1 : BOOLEAN;
    signal first_iter_010_reg_164 : STD_LOGIC_VECTOR (0 downto 0);
    signal stream_1_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage3_grp3 : BOOLEAN;
    signal icmp_ln266_reg_177 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_224_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_445 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal trunc_ln25_fu_232_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln25_reg_451 : STD_LOGIC_VECTOR (2 downto 0);
    signal first_iter_0_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal trunc_ln_reg_460 : STD_LOGIC_VECTOR (57 downto 0);
    signal icmp_ln28_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_295_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal j_reg_470 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage3_11001_grp2 : BOOLEAN;
    signal stream_1_read_reg_482 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage3_11001_grp3 : BOOLEAN;
    signal select_ln24_2_fu_337_p3 : STD_LOGIC_VECTOR (479 downto 0);
    signal select_ln24_2_reg_488 : STD_LOGIC_VECTOR (479 downto 0);
    signal ap_block_pp0_stage3_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_subdone_grp0 : BOOLEAN;
    signal icmp_ln26_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal icmp_ln26_reg_494_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_494_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_499_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_io_grp4 : BOOLEAN;
    signal ap_block_state73_pp0_stage0_iter18_grp5 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_icmp_ln266_phi_fu_180_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage1_iter0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal sext_ln26_fu_318_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_11001_grp4 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp5 : BOOLEAN;
    signal indvar_flatten2_fu_108 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln24_1_fu_328_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal i3_fu_112 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_block_pp0_stage1_grp0 : BOOLEAN;
    signal j4_fu_116 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal phi_ln285_fu_120 : STD_LOGIC_VECTOR (479 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal select_ln28_fu_391_p3 : STD_LOGIC_VECTOR (479 downto 0);
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage3_grp0 : BOOLEAN;
    signal add_ln247_fu_124 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln24_fu_301_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mem_111_fu_128 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_block_pp0_stage1_11001_grp1 : BOOLEAN;
    signal select_ln24_fu_242_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln25_cast_fu_256_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln25_fu_265_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln25_fu_269_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln26_fu_285_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal tmp_1_fu_375_p4 : STD_LOGIC_VECTOR (447 downto 0);
    signal tmp_2_fu_384_p3 : STD_LOGIC_VECTOR (479 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter18_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to17 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0_1to18 : STD_LOGIC;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_731 : BOOLEAN;
    signal ap_condition_735 : BOOLEAN;
    signal ap_condition_739 : BOOLEAN;
    signal ap_condition_745 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component read_write_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component read_write_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage3,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= ap_const_boolean_0;
            else
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp4_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp4_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp4_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4)) then 
                        ap_block_pp0_stage0_subdone_grp4_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp5_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5)) then 
                        ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage3_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then 
                        ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0)) then 
                        ap_block_pp0_stage3_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage3_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage3_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then 
                        ap_block_pp0_stage3_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2)) then 
                        ap_block_pp0_stage3_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage3_subdone_grp3_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage3_subdone_grp3_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then 
                        ap_block_pp0_stage3_subdone_grp3_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp3)) then 
                        ap_block_pp0_stage3_subdone_grp3_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter18_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    add_ln247_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg_iter0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                add_ln247_fu_124 <= ap_const_lv4_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                add_ln247_fu_124 <= add_ln24_fu_301_p2;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter10_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter10_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter11_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter11_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter12_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter12_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter13_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter13_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter14_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter14_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter15_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter15_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter16_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter16_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter17_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter17_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter18_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_loop_exit_ready_pp0_iter17_reg = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0)))) then 
                ap_loop_exit_ready_pp0_iter18_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter5_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter6_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter7_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter8_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter8_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter9_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then 
                ap_loop_exit_ready_pp0_iter9_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
            end if; 
        end if;
    end process;

    first_iter_010_reg_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_735)) then 
                    first_iter_010_reg_164 <= ap_const_lv1_0;
                elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    first_iter_010_reg_164 <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    i3_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg_iter0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                i3_fu_112 <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                i3_fu_112 <= i_reg_445;
            end if; 
        end if;
    end process;

    icmp_ln266_reg_177_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                if ((ap_const_boolean_1 = ap_condition_739)) then 
                    icmp_ln266_reg_177 <= icmp_ln26_reg_494;
                elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    icmp_ln266_reg_177 <= ap_const_lv1_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten2_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg_iter0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten2_fu_108 <= ap_const_lv10_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                indvar_flatten2_fu_108 <= add_ln24_1_fu_328_p2;
            end if; 
        end if;
    end process;

    j4_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg_iter0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                j4_fu_116 <= ap_const_lv8_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0))) then 
                j4_fu_116 <= j_reg_470;
            end if; 
        end if;
    end process;

    phi_ln285_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if ((ap_const_boolean_1 = ap_condition_745)) then 
                    phi_ln285_fu_120 <= ap_const_lv480_lc_1;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg))) then 
                    phi_ln285_fu_120 <= select_ln28_fu_391_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then
                first_iter_0_reg_456 <= first_iter_0_fu_250_p2;
                icmp_ln28_reg_465 <= icmp_ln28_fu_289_p2;
                j_reg_470 <= j_fu_295_p2;
                trunc_ln_reg_460 <= add_ln25_fu_269_p2(63 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0))) then
                i_reg_445 <= i_fu_224_p3;
                trunc_ln25_reg_451 <= trunc_ln25_fu_232_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then
                icmp_ln24_reg_499 <= icmp_ln24_fu_353_p2;
                icmp_ln24_reg_499_pp0_iter10_reg <= icmp_ln24_reg_499_pp0_iter9_reg;
                icmp_ln24_reg_499_pp0_iter11_reg <= icmp_ln24_reg_499_pp0_iter10_reg;
                icmp_ln24_reg_499_pp0_iter12_reg <= icmp_ln24_reg_499_pp0_iter11_reg;
                icmp_ln24_reg_499_pp0_iter13_reg <= icmp_ln24_reg_499_pp0_iter12_reg;
                icmp_ln24_reg_499_pp0_iter14_reg <= icmp_ln24_reg_499_pp0_iter13_reg;
                icmp_ln24_reg_499_pp0_iter15_reg <= icmp_ln24_reg_499_pp0_iter14_reg;
                icmp_ln24_reg_499_pp0_iter16_reg <= icmp_ln24_reg_499_pp0_iter15_reg;
                icmp_ln24_reg_499_pp0_iter17_reg <= icmp_ln24_reg_499_pp0_iter16_reg;
                icmp_ln24_reg_499_pp0_iter1_reg <= icmp_ln24_reg_499;
                icmp_ln24_reg_499_pp0_iter2_reg <= icmp_ln24_reg_499_pp0_iter1_reg;
                icmp_ln24_reg_499_pp0_iter3_reg <= icmp_ln24_reg_499_pp0_iter2_reg;
                icmp_ln24_reg_499_pp0_iter4_reg <= icmp_ln24_reg_499_pp0_iter3_reg;
                icmp_ln24_reg_499_pp0_iter5_reg <= icmp_ln24_reg_499_pp0_iter4_reg;
                icmp_ln24_reg_499_pp0_iter6_reg <= icmp_ln24_reg_499_pp0_iter5_reg;
                icmp_ln24_reg_499_pp0_iter7_reg <= icmp_ln24_reg_499_pp0_iter6_reg;
                icmp_ln24_reg_499_pp0_iter8_reg <= icmp_ln24_reg_499_pp0_iter7_reg;
                icmp_ln24_reg_499_pp0_iter9_reg <= icmp_ln24_reg_499_pp0_iter8_reg;
                icmp_ln26_reg_494_pp0_iter10_reg <= icmp_ln26_reg_494_pp0_iter9_reg;
                icmp_ln26_reg_494_pp0_iter11_reg <= icmp_ln26_reg_494_pp0_iter10_reg;
                icmp_ln26_reg_494_pp0_iter12_reg <= icmp_ln26_reg_494_pp0_iter11_reg;
                icmp_ln26_reg_494_pp0_iter13_reg <= icmp_ln26_reg_494_pp0_iter12_reg;
                icmp_ln26_reg_494_pp0_iter14_reg <= icmp_ln26_reg_494_pp0_iter13_reg;
                icmp_ln26_reg_494_pp0_iter15_reg <= icmp_ln26_reg_494_pp0_iter14_reg;
                icmp_ln26_reg_494_pp0_iter16_reg <= icmp_ln26_reg_494_pp0_iter15_reg;
                icmp_ln26_reg_494_pp0_iter17_reg <= icmp_ln26_reg_494_pp0_iter16_reg;
                icmp_ln26_reg_494_pp0_iter1_reg <= icmp_ln26_reg_494;
                icmp_ln26_reg_494_pp0_iter2_reg <= icmp_ln26_reg_494_pp0_iter1_reg;
                icmp_ln26_reg_494_pp0_iter3_reg <= icmp_ln26_reg_494_pp0_iter2_reg;
                icmp_ln26_reg_494_pp0_iter4_reg <= icmp_ln26_reg_494_pp0_iter3_reg;
                icmp_ln26_reg_494_pp0_iter5_reg <= icmp_ln26_reg_494_pp0_iter4_reg;
                icmp_ln26_reg_494_pp0_iter6_reg <= icmp_ln26_reg_494_pp0_iter5_reg;
                icmp_ln26_reg_494_pp0_iter7_reg <= icmp_ln26_reg_494_pp0_iter6_reg;
                icmp_ln26_reg_494_pp0_iter8_reg <= icmp_ln26_reg_494_pp0_iter7_reg;
                icmp_ln26_reg_494_pp0_iter9_reg <= icmp_ln26_reg_494_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then
                icmp_ln26_reg_494 <= icmp_ln26_fu_345_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((first_iter_010_reg_164 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1))) then
                mem_111_fu_128 <= mem_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp0))) then
                select_ln24_2_reg_488 <= select_ln24_2_fu_337_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp3_done_reg))) then
                stream_1_read_reg_482 <= stream_1_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage3_subdone, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone, ap_condition_exit_pp0_iter18_stage0, ap_idle_pp0_0to17, ap_idle_pp0_1to18, ap_block_pp0_stage2_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to17 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter18_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to18 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln24_1_fu_328_p2 <= std_logic_vector(unsigned(indvar_flatten2_fu_108) + unsigned(ap_const_lv10_1));
    add_ln24_fu_301_p2 <= std_logic_vector(unsigned(i_reg_445) + unsigned(ap_const_lv4_1));
    add_ln25_fu_269_p2 <= std_logic_vector(unsigned(zext_ln25_fu_265_p1) + unsigned(mem_111_fu_128));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp4_assign_proc : process(ap_enable_reg_pp0_iter0, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_01001_grp4 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter18, ap_block_pp0_stage0_subdone_grp4_done_reg, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state5_io_grp4, ap_block_state73_pp0_stage0_iter18_grp5)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state73_pp0_stage0_iter18_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg)));
    end process;


    ap_block_pp0_stage0_11001_grp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_11001_grp0 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0));
    end process;


    ap_block_pp0_stage0_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp4_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state5_io_grp4)
    begin
                ap_block_pp0_stage0_11001_grp4 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg)));
    end process;


    ap_block_pp0_stage0_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter18, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state73_pp0_stage0_iter18_grp5)
    begin
                ap_block_pp0_stage0_11001_grp5 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state73_pp0_stage0_iter18_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg)));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter18, ap_block_pp0_stage0_subdone_grp4_done_reg, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state5_io_grp4, ap_block_state73_pp0_stage0_iter18_grp5)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state73_pp0_stage0_iter18_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg)));
    end process;


    ap_block_pp0_stage0_subdone_grp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_subdone_grp0 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0));
    end process;


    ap_block_pp0_stage0_subdone_grp4_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp4_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state5_io_grp4)
    begin
                ap_block_pp0_stage0_subdone_grp4 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg)));
    end process;


    ap_block_pp0_stage0_subdone_grp5_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter18, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state73_pp0_stage0_iter18_grp5)
    begin
                ap_block_pp0_stage0_subdone_grp5 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state73_pp0_stage0_iter18_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_done_reg, ap_block_state2_pp0_stage1_iter0_grp1)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage1_11001_grp0_assign_proc : process(ap_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_pp0_stage1_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_done_reg, ap_block_state2_pp0_stage1_iter0_grp1)
    begin
                ap_block_pp0_stage1_11001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage1_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_done_reg, ap_block_state2_pp0_stage1_iter0_grp1)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage1_subdone_grp0_assign_proc : process(ap_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp0 <= (ap_done_reg = ap_const_logic_1);
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_assign_proc : process(stream_1_empty_n, ap_block_state4_io_grp2, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_block_pp0_stage3_subdone_grp3_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage3_11001 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp3_done_reg) and (stream_1_empty_n = ap_const_logic_0)) or ((ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg))));
    end process;

        ap_block_pp0_stage3_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_grp2_assign_proc : process(ap_block_state4_io_grp2, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage3_11001_grp2 <= ((ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage3_11001_grp3_assign_proc : process(stream_1_empty_n, ap_block_pp0_stage3_subdone_grp3_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage3_11001_grp3 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp3_done_reg) and (stream_1_empty_n = ap_const_logic_0));
    end process;

        ap_block_pp0_stage3_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(stream_1_empty_n, ap_block_state4_io_grp2, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_block_pp0_stage3_subdone_grp3_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp3_done_reg) and (stream_1_empty_n = ap_const_logic_0)) or ((ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg))));
    end process;

        ap_block_pp0_stage3_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_grp2_assign_proc : process(ap_block_state4_io_grp2, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage3_subdone_grp2 <= ((ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage3_subdone_grp3_assign_proc : process(stream_1_empty_n, ap_block_pp0_stage3_subdone_grp3_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage3_subdone_grp3 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp3_done_reg) and (stream_1_empty_n = ap_const_logic_0));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage1_iter0_grp1_assign_proc : process(mem_empty_n, first_iter_010_reg_164)
    begin
                ap_block_state2_pp0_stage1_iter0_grp1 <= ((first_iter_010_reg_164 = ap_const_lv1_1) and (mem_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_io_grp2_assign_proc : process(m_axi_mem_1_0_AWREADY, first_iter_0_reg_456)
    begin
                ap_block_state4_io_grp2 <= ((m_axi_mem_1_0_AWREADY = ap_const_logic_0) and (first_iter_0_reg_456 = ap_const_lv1_1));
    end process;


    ap_block_state5_io_grp4_assign_proc : process(m_axi_mem_1_0_WREADY, icmp_ln28_reg_465)
    begin
                ap_block_state5_io_grp4 <= ((icmp_ln28_reg_465 = ap_const_lv1_1) and (m_axi_mem_1_0_WREADY = ap_const_logic_0));
    end process;


    ap_block_state73_pp0_stage0_iter18_grp5_assign_proc : process(m_axi_mem_1_0_BVALID, icmp_ln26_reg_494_pp0_iter17_reg)
    begin
                ap_block_state73_pp0_stage0_iter18_grp5 <= ((icmp_ln26_reg_494_pp0_iter17_reg = ap_const_lv1_1) and (m_axi_mem_1_0_BVALID = ap_const_logic_0));
    end process;


    ap_condition_731_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln24_reg_499, ap_block_pp0_stage1)
    begin
                ap_condition_731 <= ((icmp_ln24_reg_499 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1));
    end process;


    ap_condition_735_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln24_reg_499, ap_block_pp0_stage0_11001)
    begin
                ap_condition_735 <= ((icmp_ln24_reg_499 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_739_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln24_reg_499, ap_block_pp0_stage1_11001)
    begin
                ap_condition_739 <= ((icmp_ln24_reg_499 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001));
    end process;


    ap_condition_745_assign_proc : process(ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0_subdone_grp0_done_reg_iter0)
    begin
                ap_condition_745 <= ((ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg_iter0));
    end process;


    ap_condition_exit_pp0_iter0_stage3_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln24_fu_353_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (icmp_ln24_fu_353_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter18_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter18, ap_block_pp0_stage0_subdone, icmp_ln24_reg_499_pp0_iter17_reg)
    begin
        if (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (icmp_ln24_reg_499_pp0_iter17_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter18_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter18_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter18_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter18_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18)
    begin
        if (((ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to17_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17)
    begin
        if (((ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to17 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to17 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to18_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18)
    begin
        if (((ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to18 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to18 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage3;

    ap_phi_mux_icmp_ln266_phi_fu_180_p4_assign_proc : process(icmp_ln26_reg_494, ap_CS_fsm_pp0_stage1, ap_loop_init, ap_condition_731)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
            if ((ap_const_boolean_1 = ap_condition_731)) then 
                ap_phi_mux_icmp_ln266_phi_fu_180_p4 <= icmp_ln26_reg_494;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln266_phi_fu_180_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln266_phi_fu_180_p4 <= icmp_ln26_reg_494;
            end if;
        else 
            ap_phi_mux_icmp_ln266_phi_fu_180_p4 <= icmp_ln26_reg_494;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    first_iter_0_fu_250_p2 <= "1" when (select_ln24_fu_242_p3 = ap_const_lv8_0) else "0";
    i_fu_224_p3 <= 
        add_ln247_fu_124 when (ap_phi_mux_icmp_ln266_phi_fu_180_p4(0) = '1') else 
        i3_fu_112;
    icmp_ln24_fu_353_p2 <= "1" when (indvar_flatten2_fu_108 = ap_const_lv10_3FF) else "0";
    icmp_ln26_fu_345_p2 <= "1" when (j_reg_470 = ap_const_lv8_80) else "0";
    icmp_ln28_fu_289_p2 <= "1" when (trunc_ln26_fu_285_p1 = ap_const_lv4_F) else "0";
    j_fu_295_p2 <= std_logic_vector(unsigned(select_ln24_fu_242_p3) + unsigned(ap_const_lv8_1));
    m_axi_mem_1_0_ARADDR <= ap_const_lv64_0;
    m_axi_mem_1_0_ARBURST <= ap_const_lv2_0;
    m_axi_mem_1_0_ARCACHE <= ap_const_lv4_0;
    m_axi_mem_1_0_ARID <= ap_const_lv1_0;
    m_axi_mem_1_0_ARLEN <= ap_const_lv32_0;
    m_axi_mem_1_0_ARLOCK <= ap_const_lv2_0;
    m_axi_mem_1_0_ARPROT <= ap_const_lv3_0;
    m_axi_mem_1_0_ARQOS <= ap_const_lv4_0;
    m_axi_mem_1_0_ARREGION <= ap_const_lv4_0;
    m_axi_mem_1_0_ARSIZE <= ap_const_lv3_0;
    m_axi_mem_1_0_ARUSER <= ap_const_lv1_0;
    m_axi_mem_1_0_ARVALID <= ap_const_logic_0;
    m_axi_mem_1_0_AWADDR <= sext_ln26_fu_318_p1;
    m_axi_mem_1_0_AWBURST <= ap_const_lv2_0;
    m_axi_mem_1_0_AWCACHE <= ap_const_lv4_0;
    m_axi_mem_1_0_AWID <= ap_const_lv1_0;
    m_axi_mem_1_0_AWLEN <= ap_const_lv64_8(32 - 1 downto 0);
    m_axi_mem_1_0_AWLOCK <= ap_const_lv2_0;
    m_axi_mem_1_0_AWPROT <= ap_const_lv3_0;
    m_axi_mem_1_0_AWQOS <= ap_const_lv4_0;
    m_axi_mem_1_0_AWREGION <= ap_const_lv4_0;
    m_axi_mem_1_0_AWSIZE <= ap_const_lv3_0;
    m_axi_mem_1_0_AWUSER <= ap_const_lv1_0;

    m_axi_mem_1_0_AWVALID_assign_proc : process(ap_CS_fsm_pp0_stage3, first_iter_0_reg_456, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage3_11001_grp2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg) and (first_iter_0_reg_456 = ap_const_lv1_1))) then 
            m_axi_mem_1_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_mem_1_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_mem_1_0_BREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter18, icmp_ln26_reg_494_pp0_iter17_reg, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage0_11001_grp5)
    begin
        if (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (icmp_ln26_reg_494_pp0_iter17_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg))) then 
            m_axi_mem_1_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_mem_1_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_mem_1_0_RREADY <= ap_const_logic_0;
    m_axi_mem_1_0_WDATA <= (stream_1_read_reg_482 & select_ln24_2_reg_488);
    m_axi_mem_1_0_WID <= ap_const_lv1_0;
    m_axi_mem_1_0_WLAST <= ap_const_logic_0;
    m_axi_mem_1_0_WSTRB <= ap_const_lv64_FFFFFFFFFFFFFFFF;
    m_axi_mem_1_0_WUSER <= ap_const_lv1_0;

    m_axi_mem_1_0_WVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln28_reg_465, ap_block_pp0_stage0_subdone_grp4_done_reg, ap_block_pp0_stage0_11001_grp4)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln28_reg_465 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg))) then 
            m_axi_mem_1_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_mem_1_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    mem_1_blk_n_AW_assign_proc : process(ap_CS_fsm_pp0_stage3, m_axi_mem_1_0_AWREADY, first_iter_0_reg_456, ap_block_pp0_stage3_subdone_grp2_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage3_grp2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp2_done_reg) and (first_iter_0_reg_456 = ap_const_lv1_1))) then 
            mem_1_blk_n_AW <= m_axi_mem_1_0_AWREADY;
        else 
            mem_1_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    mem_1_blk_n_B_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter18, m_axi_mem_1_0_BVALID, ap_block_pp0_stage0_grp5, icmp_ln26_reg_494_pp0_iter17_reg, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (icmp_ln26_reg_494_pp0_iter17_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp5))) then 
            mem_1_blk_n_B <= m_axi_mem_1_0_BVALID;
        else 
            mem_1_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    mem_1_blk_n_W_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_mem_1_0_WREADY, ap_block_pp0_stage0_grp4, icmp_ln28_reg_465, ap_block_pp0_stage0_subdone_grp4_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln28_reg_465 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp4_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp4))) then 
            mem_1_blk_n_W <= m_axi_mem_1_0_WREADY;
        else 
            mem_1_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    mem_blk_n_assign_proc : process(mem_empty_n, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp1, first_iter_010_reg_164)
    begin
        if (((first_iter_010_reg_164 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1))) then 
            mem_blk_n <= mem_empty_n;
        else 
            mem_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    mem_read_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, first_iter_010_reg_164, ap_block_pp0_stage1_11001_grp1)
    begin
        if (((first_iter_010_reg_164 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1))) then 
            mem_read <= ap_const_logic_1;
        else 
            mem_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln24_2_fu_337_p3 <= 
        ap_const_lv480_lc_1 when (icmp_ln266_reg_177(0) = '1') else 
        phi_ln285_fu_120;
    select_ln24_fu_242_p3 <= 
        ap_const_lv8_0 when (icmp_ln266_reg_177(0) = '1') else 
        j4_fu_116;
    select_ln28_fu_391_p3 <= 
        ap_const_lv480_lc_1 when (icmp_ln28_reg_465(0) = '1') else 
        tmp_2_fu_384_p3;
        sext_ln26_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_460),64));


    stream_1_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage3, stream_1_empty_n, ap_block_pp0_stage3_subdone_grp3_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage3_grp3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp3_done_reg))) then 
            stream_1_blk_n <= stream_1_empty_n;
        else 
            stream_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_1_read_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone_grp3_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage3_11001_grp3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone_grp3_done_reg))) then 
            stream_1_read <= ap_const_logic_1;
        else 
            stream_1_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_375_p4 <= select_ln24_2_reg_488(479 downto 32);
    tmp_2_fu_384_p3 <= (stream_1_read_reg_482 & tmp_1_fu_375_p4);
    trunc_ln25_fu_232_p1 <= i_fu_224_p3(3 - 1 downto 0);
    trunc_ln26_fu_285_p1 <= select_ln24_fu_242_p3(4 - 1 downto 0);
    zext_ln25_cast_fu_256_p4 <= ((ap_const_lv1_1 & trunc_ln25_reg_451) & ap_const_lv10_200);
    zext_ln25_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln25_cast_fu_256_p4),64));
end behav;
