-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matmul_row_col_matmul_row_col_Pipeline_load_ab_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_b_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_b_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_b_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_b_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_b_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_b_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_b_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_b_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_b_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_b_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_b_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_b_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_b_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_b_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_b_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_b_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_b_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_b_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_b_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_b_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_b_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_b_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_b_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_b_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_b_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    gmem_a_load : IN STD_LOGIC_VECTOR (511 downto 0);
    p_cast_cast : IN STD_LOGIC_VECTOR (57 downto 0);
    A_row_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_row_ce0 : OUT STD_LOGIC;
    A_row_we0 : OUT STD_LOGIC;
    A_row_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    tmp_4 : IN STD_LOGIC_VECTOR (8 downto 0);
    B_col_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_col_ce0 : OUT STD_LOGIC;
    B_col_we0 : OUT STD_LOGIC;
    B_col_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matmul_row_col_matmul_row_col_Pipeline_load_ab_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln23_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_b_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln23_fu_155_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln23_reg_230 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln23_reg_230_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_b_addr_read_reg_235 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal shiftreg_fu_66 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal zext_ln25_fu_175_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal k_fu_70 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln23_fu_146_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal A_row_we0_local : STD_LOGIC;
    signal trunc_ln25_fu_160_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal A_row_ce0_local : STD_LOGIC;
    signal B_col_we0_local : STD_LOGIC;
    signal tmp_fu_195_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_col_ce0_local : STD_LOGIC;
    signal lshr_ln_fu_165_p4 : STD_LOGIC_VECTOR (479 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_195_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component matmul_row_col_partselect_32ns_512ns_9ns_32_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER;
        DATA1WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (511 downto 0);
        sel : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matmul_row_col_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    partselect_32ns_512ns_9ns_32_1_1_U1 : component matmul_row_col_partselect_32ns_512ns_9ns_32_1_1
    generic map (
        DATAWIDTH => 512,
        ADDRWIDTH => 9,
        DATA1WIDTH => 32)
    port map (
        din => gmem_b_addr_read_reg_235,
        sel => tmp_4,
        dout => tmp_fu_195_p3);

    flow_control_loop_pipe_sequential_init_U : component matmul_row_col_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    k_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_70 <= ap_const_lv5_0;
                elsif (((icmp_ln23_fu_140_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    k_fu_70 <= add_ln23_fu_146_p2;
                end if;
            end if; 
        end if;
    end process;

    shiftreg_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    shiftreg_fu_66 <= gmem_a_load;
                elsif (((icmp_ln23_fu_140_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    shiftreg_fu_66 <= zext_ln25_fu_175_p1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                    zext_ln23_reg_230(4 downto 0) <= zext_ln23_fu_155_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                gmem_b_addr_read_reg_235 <= m_axi_gmem_b_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                    zext_ln23_reg_230_pp0_iter2_reg(4 downto 0) <= zext_ln23_reg_230(4 downto 0);
            end if;
        end if;
    end process;
    zext_ln23_reg_230(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln23_reg_230_pp0_iter2_reg(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    A_row_address0 <= zext_ln23_fu_155_p1(4 - 1 downto 0);
    A_row_ce0 <= A_row_ce0_local;

    A_row_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_row_ce0_local <= ap_const_logic_1;
        else 
            A_row_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_row_d0 <= trunc_ln25_fu_160_p1;
    A_row_we0 <= A_row_we0_local;

    A_row_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln23_fu_140_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln23_fu_140_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_row_we0_local <= ap_const_logic_1;
        else 
            A_row_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_col_address0 <= zext_ln23_reg_230_pp0_iter2_reg(4 - 1 downto 0);
    B_col_ce0 <= B_col_ce0_local;

    B_col_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            B_col_ce0_local <= ap_const_logic_1;
        else 
            B_col_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_col_d0 <= tmp_fu_195_p3;
    B_col_we0 <= B_col_we0_local;

    B_col_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            B_col_we0_local <= ap_const_logic_1;
        else 
            B_col_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln23_fu_146_p2 <= std_logic_vector(unsigned(k_fu_70) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_b_0_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem_b_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_b_0_RVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((m_axi_gmem_b_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_b_0_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem_b_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln23_fu_140_p2)
    begin
        if (((icmp_ln23_fu_140_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    gmem_b_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_b_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            gmem_b_blk_n_R <= m_axi_gmem_b_0_RVALID;
        else 
            gmem_b_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln23_fu_140_p2 <= "1" when (k_fu_70 = ap_const_lv5_10) else "0";
    lshr_ln_fu_165_p4 <= shiftreg_fu_66(511 downto 32);
    m_axi_gmem_b_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_b_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_b_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_b_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_b_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_b_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_b_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_b_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_b_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_b_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_b_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_b_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_b_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_b_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_b_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_b_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_b_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_b_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_b_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_b_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_b_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_b_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_b_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_b_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_b_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_b_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            m_axi_gmem_b_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_b_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_b_0_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem_b_0_WID <= ap_const_lv1_0;
    m_axi_gmem_b_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_b_0_WSTRB <= ap_const_lv64_0;
    m_axi_gmem_b_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_b_0_WVALID <= ap_const_logic_0;
    trunc_ln25_fu_160_p1 <= shiftreg_fu_66(32 - 1 downto 0);
    zext_ln23_fu_155_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_fu_70),64));
    zext_ln25_fu_175_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_165_p4),512));
end behav;
