// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module read_write_write_r (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_mem_0_0_AWVALID,
        m_axi_mem_0_0_AWREADY,
        m_axi_mem_0_0_AWADDR,
        m_axi_mem_0_0_AWID,
        m_axi_mem_0_0_AWLEN,
        m_axi_mem_0_0_AWSIZE,
        m_axi_mem_0_0_AWBURST,
        m_axi_mem_0_0_AWLOCK,
        m_axi_mem_0_0_AWCACHE,
        m_axi_mem_0_0_AWPROT,
        m_axi_mem_0_0_AWQOS,
        m_axi_mem_0_0_AWREGION,
        m_axi_mem_0_0_AWUSER,
        m_axi_mem_0_0_WVALID,
        m_axi_mem_0_0_WREADY,
        m_axi_mem_0_0_WDATA,
        m_axi_mem_0_0_WSTRB,
        m_axi_mem_0_0_WLAST,
        m_axi_mem_0_0_WID,
        m_axi_mem_0_0_WUSER,
        m_axi_mem_0_0_ARVALID,
        m_axi_mem_0_0_ARREADY,
        m_axi_mem_0_0_ARADDR,
        m_axi_mem_0_0_ARID,
        m_axi_mem_0_0_ARLEN,
        m_axi_mem_0_0_ARSIZE,
        m_axi_mem_0_0_ARBURST,
        m_axi_mem_0_0_ARLOCK,
        m_axi_mem_0_0_ARCACHE,
        m_axi_mem_0_0_ARPROT,
        m_axi_mem_0_0_ARQOS,
        m_axi_mem_0_0_ARREGION,
        m_axi_mem_0_0_ARUSER,
        m_axi_mem_0_0_RVALID,
        m_axi_mem_0_0_RREADY,
        m_axi_mem_0_0_RDATA,
        m_axi_mem_0_0_RLAST,
        m_axi_mem_0_0_RID,
        m_axi_mem_0_0_RFIFONUM,
        m_axi_mem_0_0_RUSER,
        m_axi_mem_0_0_RRESP,
        m_axi_mem_0_0_BVALID,
        m_axi_mem_0_0_BREADY,
        m_axi_mem_0_0_BRESP,
        m_axi_mem_0_0_BID,
        m_axi_mem_0_0_BUSER,
        mem_dout,
        mem_empty_n,
        mem_read,
        mem_num_data_valid,
        mem_fifo_cap,
        stream_0_dout,
        stream_0_empty_n,
        stream_0_read,
        stream_0_num_data_valid,
        stream_0_fifo_cap
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_mem_0_0_AWVALID;
input   m_axi_mem_0_0_AWREADY;
output  [63:0] m_axi_mem_0_0_AWADDR;
output  [0:0] m_axi_mem_0_0_AWID;
output  [31:0] m_axi_mem_0_0_AWLEN;
output  [2:0] m_axi_mem_0_0_AWSIZE;
output  [1:0] m_axi_mem_0_0_AWBURST;
output  [1:0] m_axi_mem_0_0_AWLOCK;
output  [3:0] m_axi_mem_0_0_AWCACHE;
output  [2:0] m_axi_mem_0_0_AWPROT;
output  [3:0] m_axi_mem_0_0_AWQOS;
output  [3:0] m_axi_mem_0_0_AWREGION;
output  [0:0] m_axi_mem_0_0_AWUSER;
output   m_axi_mem_0_0_WVALID;
input   m_axi_mem_0_0_WREADY;
output  [511:0] m_axi_mem_0_0_WDATA;
output  [63:0] m_axi_mem_0_0_WSTRB;
output   m_axi_mem_0_0_WLAST;
output  [0:0] m_axi_mem_0_0_WID;
output  [0:0] m_axi_mem_0_0_WUSER;
output   m_axi_mem_0_0_ARVALID;
input   m_axi_mem_0_0_ARREADY;
output  [63:0] m_axi_mem_0_0_ARADDR;
output  [0:0] m_axi_mem_0_0_ARID;
output  [31:0] m_axi_mem_0_0_ARLEN;
output  [2:0] m_axi_mem_0_0_ARSIZE;
output  [1:0] m_axi_mem_0_0_ARBURST;
output  [1:0] m_axi_mem_0_0_ARLOCK;
output  [3:0] m_axi_mem_0_0_ARCACHE;
output  [2:0] m_axi_mem_0_0_ARPROT;
output  [3:0] m_axi_mem_0_0_ARQOS;
output  [3:0] m_axi_mem_0_0_ARREGION;
output  [0:0] m_axi_mem_0_0_ARUSER;
input   m_axi_mem_0_0_RVALID;
output   m_axi_mem_0_0_RREADY;
input  [511:0] m_axi_mem_0_0_RDATA;
input   m_axi_mem_0_0_RLAST;
input  [0:0] m_axi_mem_0_0_RID;
input  [8:0] m_axi_mem_0_0_RFIFONUM;
input  [0:0] m_axi_mem_0_0_RUSER;
input  [1:0] m_axi_mem_0_0_RRESP;
input   m_axi_mem_0_0_BVALID;
output   m_axi_mem_0_0_BREADY;
input  [1:0] m_axi_mem_0_0_BRESP;
input  [0:0] m_axi_mem_0_0_BID;
input  [0:0] m_axi_mem_0_0_BUSER;
input  [63:0] mem_dout;
input   mem_empty_n;
output   mem_read;
input  [2:0] mem_num_data_valid;
input  [2:0] mem_fifo_cap;
input  [31:0] stream_0_dout;
input   stream_0_empty_n;
output   stream_0_read;
input  [2:0] stream_0_num_data_valid;
input  [2:0] stream_0_fifo_cap;

reg ap_idle;
reg m_axi_mem_0_0_AWVALID;
reg m_axi_mem_0_0_WVALID;
reg m_axi_mem_0_0_BREADY;
reg mem_read;
reg stream_0_read;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg   [0:0] first_iter_0_reg_454;
reg    ap_block_state4_io_grp2;
reg    ap_block_pp0_stage3_subdone_grp2_done_reg;
reg    ap_block_pp0_stage3_subdone_grp2;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage3_subdone_grp3_done_reg;
reg    ap_block_pp0_stage3_subdone_grp3;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln24_fu_351_p2;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    mem_0_blk_n_AW;
wire    ap_block_pp0_stage3_grp2;
reg    mem_0_blk_n_W;
wire    ap_block_pp0_stage0_grp4;
reg   [0:0] icmp_ln28_reg_463;
reg    ap_block_pp0_stage0_subdone_grp4_done_reg;
reg    ap_block_pp0_stage0_subdone_grp4;
reg    ap_block_pp0_stage0_subdone;
reg    mem_0_blk_n_B;
wire    ap_block_pp0_stage0_grp5;
reg   [0:0] icmp_ln26_reg_492;
reg   [0:0] icmp_ln26_reg_492_pp0_iter17_reg;
reg    ap_block_pp0_stage0_subdone_grp5_done_reg;
reg    ap_block_pp0_stage0_subdone_grp5;
reg    mem_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
reg   [0:0] first_iter_010_reg_162;
reg    stream_0_blk_n;
wire    ap_block_pp0_stage3_grp3;
reg   [0:0] icmp_ln266_reg_175;
wire   [3:0] i_fu_222_p3;
reg   [3:0] i_reg_443;
reg    ap_done_reg;
reg    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
reg    ap_block_pp0_stage1_subdone_grp0;
reg    ap_block_pp0_stage1_subdone;
wire   [2:0] trunc_ln25_fu_230_p1;
reg   [2:0] trunc_ln25_reg_449;
wire   [0:0] first_iter_0_fu_248_p2;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [57:0] trunc_ln_reg_458;
wire   [0:0] icmp_ln28_fu_287_p2;
wire   [7:0] j_fu_293_p2;
reg   [7:0] j_reg_468;
reg    ap_block_pp0_stage3_11001_grp2;
reg   [31:0] stream_0_read_reg_480;
reg    ap_block_pp0_stage3_11001_grp3;
wire   [479:0] select_ln24_4_fu_335_p3;
reg   [479:0] select_ln24_4_reg_486;
wire    ap_block_pp0_stage3_11001_grp0;
reg    ap_block_pp0_stage3_subdone_grp0_done_reg;
wire    ap_block_pp0_stage3_subdone_grp0;
wire   [0:0] icmp_ln26_fu_343_p2;
reg    ap_block_pp0_stage3_11001;
reg   [0:0] icmp_ln26_reg_492_pp0_iter1_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter2_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter3_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter4_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter5_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter6_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter7_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter8_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter9_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter10_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter11_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter12_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter13_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter14_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter15_reg;
reg   [0:0] icmp_ln26_reg_492_pp0_iter16_reg;
reg   [0:0] icmp_ln24_reg_497;
reg   [0:0] icmp_ln24_reg_497_pp0_iter1_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter2_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter3_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter4_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter5_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter6_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter7_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter8_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter9_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter10_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter11_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter12_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter13_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter14_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter15_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter16_reg;
reg   [0:0] icmp_ln24_reg_497_pp0_iter17_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state5_io_grp4;
reg    ap_block_state73_pp0_stage0_iter18_grp5;
wire    ap_loop_init;
reg    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage0;
reg   [0:0] ap_phi_mux_icmp_ln266_phi_fu_178_p4;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage1;
wire  signed [63:0] sext_ln26_fu_316_p1;
reg    ap_block_pp0_stage0_11001_grp4;
reg    ap_block_pp0_stage0_01001_grp4;
reg    ap_block_pp0_stage0_11001_grp5;
reg   [9:0] indvar_flatten2_fu_106;
wire   [9:0] add_ln24_2_fu_326_p2;
reg    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg_iter0;
reg    ap_block_pp0_stage0_subdone_grp0;
wire    ap_block_pp0_stage3;
reg   [3:0] i3_fu_110;
wire    ap_block_pp0_stage1_grp0;
reg   [7:0] j4_fu_114;
wire    ap_block_pp0_stage2;
reg   [479:0] phi_ln285_fu_118;
wire   [479:0] select_ln28_fu_389_p3;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage3_grp0;
reg   [3:0] add_ln247_fu_122;
wire   [3:0] add_ln24_fu_299_p2;
reg   [63:0] mem_211_fu_126;
reg    ap_block_pp0_stage1_11001_grp1;
wire   [7:0] select_ln24_fu_240_p3;
wire   [13:0] zext_ln25_cast_fu_254_p4;
wire   [63:0] zext_ln25_fu_263_p1;
wire   [63:0] add_ln25_fu_267_p2;
wire   [3:0] trunc_ln26_fu_283_p1;
wire    ap_block_pp0_stage0_grp0;
wire   [447:0] tmp_3_fu_373_p4;
wire   [479:0] tmp_4_fu_382_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter18_stage0;
reg    ap_idle_pp0_0to17;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to18;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_730;
reg    ap_condition_734;
reg    ap_condition_738;
reg    ap_condition_744;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp3_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp4_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp5_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp0_done_reg = 1'b0;
#0 indvar_flatten2_fu_106 = 10'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 = 1'b0;
#0 i3_fu_110 = 4'd0;
#0 j4_fu_114 = 8'd0;
#0 phi_ln285_fu_118 = 480'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 add_ln247_fu_122 = 4'd0;
#0 mem_211_fu_126 = 64'd0;
end

read_write_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp4)) begin
                ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp5_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp5_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp5)) begin
                ap_block_pp0_stage0_subdone_grp5_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp0)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp2)) begin
                ap_block_pp0_stage3_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp3_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp3)) begin
                ap_block_pp0_stage3_subdone_grp3_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter18 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        add_ln247_fu_122 <= 4'd1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        add_ln247_fu_122 <= add_ln24_fu_299_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready_pp0_iter17_reg == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0)))) begin
        ap_loop_exit_ready_pp0_iter18_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_734)) begin
            first_iter_010_reg_162 <= 1'd0;
        end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            first_iter_010_reg_162 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        i3_fu_110 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        i3_fu_110 <= i_reg_443;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
        if ((1'b1 == ap_condition_738)) begin
            icmp_ln266_reg_175 <= icmp_ln26_reg_492;
        end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            icmp_ln266_reg_175 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvar_flatten2_fu_106 <= 10'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        indvar_flatten2_fu_106 <= add_ln24_2_fu_326_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        j4_fu_114 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0))) begin
        j4_fu_114 <= j_reg_468;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if ((1'b1 == ap_condition_744)) begin
            phi_ln285_fu_118 <= 480'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg))) begin
            phi_ln285_fu_118 <= select_ln28_fu_389_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        first_iter_0_reg_454 <= first_iter_0_fu_248_p2;
        icmp_ln28_reg_463 <= icmp_ln28_fu_287_p2;
        j_reg_468 <= j_fu_293_p2;
        trunc_ln_reg_458 <= {{add_ln25_fu_267_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        i_reg_443 <= i_fu_222_p3;
        trunc_ln25_reg_449 <= trunc_ln25_fu_230_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        icmp_ln24_reg_497 <= icmp_ln24_fu_351_p2;
        icmp_ln24_reg_497_pp0_iter10_reg <= icmp_ln24_reg_497_pp0_iter9_reg;
        icmp_ln24_reg_497_pp0_iter11_reg <= icmp_ln24_reg_497_pp0_iter10_reg;
        icmp_ln24_reg_497_pp0_iter12_reg <= icmp_ln24_reg_497_pp0_iter11_reg;
        icmp_ln24_reg_497_pp0_iter13_reg <= icmp_ln24_reg_497_pp0_iter12_reg;
        icmp_ln24_reg_497_pp0_iter14_reg <= icmp_ln24_reg_497_pp0_iter13_reg;
        icmp_ln24_reg_497_pp0_iter15_reg <= icmp_ln24_reg_497_pp0_iter14_reg;
        icmp_ln24_reg_497_pp0_iter16_reg <= icmp_ln24_reg_497_pp0_iter15_reg;
        icmp_ln24_reg_497_pp0_iter17_reg <= icmp_ln24_reg_497_pp0_iter16_reg;
        icmp_ln24_reg_497_pp0_iter1_reg <= icmp_ln24_reg_497;
        icmp_ln24_reg_497_pp0_iter2_reg <= icmp_ln24_reg_497_pp0_iter1_reg;
        icmp_ln24_reg_497_pp0_iter3_reg <= icmp_ln24_reg_497_pp0_iter2_reg;
        icmp_ln24_reg_497_pp0_iter4_reg <= icmp_ln24_reg_497_pp0_iter3_reg;
        icmp_ln24_reg_497_pp0_iter5_reg <= icmp_ln24_reg_497_pp0_iter4_reg;
        icmp_ln24_reg_497_pp0_iter6_reg <= icmp_ln24_reg_497_pp0_iter5_reg;
        icmp_ln24_reg_497_pp0_iter7_reg <= icmp_ln24_reg_497_pp0_iter6_reg;
        icmp_ln24_reg_497_pp0_iter8_reg <= icmp_ln24_reg_497_pp0_iter7_reg;
        icmp_ln24_reg_497_pp0_iter9_reg <= icmp_ln24_reg_497_pp0_iter8_reg;
        icmp_ln26_reg_492_pp0_iter10_reg <= icmp_ln26_reg_492_pp0_iter9_reg;
        icmp_ln26_reg_492_pp0_iter11_reg <= icmp_ln26_reg_492_pp0_iter10_reg;
        icmp_ln26_reg_492_pp0_iter12_reg <= icmp_ln26_reg_492_pp0_iter11_reg;
        icmp_ln26_reg_492_pp0_iter13_reg <= icmp_ln26_reg_492_pp0_iter12_reg;
        icmp_ln26_reg_492_pp0_iter14_reg <= icmp_ln26_reg_492_pp0_iter13_reg;
        icmp_ln26_reg_492_pp0_iter15_reg <= icmp_ln26_reg_492_pp0_iter14_reg;
        icmp_ln26_reg_492_pp0_iter16_reg <= icmp_ln26_reg_492_pp0_iter15_reg;
        icmp_ln26_reg_492_pp0_iter17_reg <= icmp_ln26_reg_492_pp0_iter16_reg;
        icmp_ln26_reg_492_pp0_iter1_reg <= icmp_ln26_reg_492;
        icmp_ln26_reg_492_pp0_iter2_reg <= icmp_ln26_reg_492_pp0_iter1_reg;
        icmp_ln26_reg_492_pp0_iter3_reg <= icmp_ln26_reg_492_pp0_iter2_reg;
        icmp_ln26_reg_492_pp0_iter4_reg <= icmp_ln26_reg_492_pp0_iter3_reg;
        icmp_ln26_reg_492_pp0_iter5_reg <= icmp_ln26_reg_492_pp0_iter4_reg;
        icmp_ln26_reg_492_pp0_iter6_reg <= icmp_ln26_reg_492_pp0_iter5_reg;
        icmp_ln26_reg_492_pp0_iter7_reg <= icmp_ln26_reg_492_pp0_iter6_reg;
        icmp_ln26_reg_492_pp0_iter8_reg <= icmp_ln26_reg_492_pp0_iter7_reg;
        icmp_ln26_reg_492_pp0_iter9_reg <= icmp_ln26_reg_492_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        icmp_ln26_reg_492 <= icmp_ln26_fu_343_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((first_iter_010_reg_162 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1))) begin
        mem_211_fu_126 <= mem_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0))) begin
        select_ln24_4_reg_486 <= select_ln24_4_fu_335_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (1'b0 == ap_block_pp0_stage3_subdone_grp3_done_reg))) begin
        stream_0_read_reg_480 <= stream_0_dout;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln24_fu_351_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (icmp_ln24_reg_497_pp0_iter17_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter18_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter18_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to17 = 1'b1;
    end else begin
        ap_idle_pp0_0to17 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to18 = 1'b1;
    end else begin
        ap_idle_pp0_1to18 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
        if ((1'b1 == ap_condition_730)) begin
            ap_phi_mux_icmp_ln266_phi_fu_178_p4 = icmp_ln26_reg_492;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln266_phi_fu_178_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln266_phi_fu_178_p4 = icmp_ln26_reg_492;
        end
    end else begin
        ap_phi_mux_icmp_ln266_phi_fu_178_p4 = icmp_ln26_reg_492;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (first_iter_0_reg_454 == 1'd1))) begin
        m_axi_mem_0_0_AWVALID = 1'b1;
    end else begin
        m_axi_mem_0_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (icmp_ln26_reg_492_pp0_iter17_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg))) begin
        m_axi_mem_0_0_BREADY = 1'b1;
    end else begin
        m_axi_mem_0_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln28_reg_463 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg))) begin
        m_axi_mem_0_0_WVALID = 1'b1;
    end else begin
        m_axi_mem_0_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (first_iter_0_reg_454 == 1'd1))) begin
        mem_0_blk_n_AW = m_axi_mem_0_0_AWREADY;
    end else begin
        mem_0_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (icmp_ln26_reg_492_pp0_iter17_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg) & (1'b0 == ap_block_pp0_stage0_grp5))) begin
        mem_0_blk_n_B = m_axi_mem_0_0_BVALID;
    end else begin
        mem_0_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln28_reg_463 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (1'b0 == ap_block_pp0_stage0_grp4))) begin
        mem_0_blk_n_W = m_axi_mem_0_0_WREADY;
    end else begin
        mem_0_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((first_iter_010_reg_162 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1))) begin
        mem_blk_n = mem_empty_n;
    end else begin
        mem_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((first_iter_010_reg_162 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1))) begin
        mem_read = 1'b1;
    end else begin
        mem_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp3) & (1'b0 == ap_block_pp0_stage3_subdone_grp3_done_reg))) begin
        stream_0_blk_n = stream_0_empty_n;
    end else begin
        stream_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (1'b0 == ap_block_pp0_stage3_subdone_grp3_done_reg))) begin
        stream_0_read = 1'b1;
    end else begin
        stream_0_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to17 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter18_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to18 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln24_2_fu_326_p2 = (indvar_flatten2_fu_106 + 10'd1);

assign add_ln24_fu_299_p2 = (i_reg_443 + 4'd1);

assign add_ln25_fu_267_p2 = (zext_ln25_fu_263_p1 + mem_211_fu_126);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp4 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state73_pp0_stage0_iter18_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp0 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp4 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp5 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state73_pp0_stage0_iter18_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg)));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state73_pp0_stage0_iter18_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp0 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp4 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp5 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state73_pp0_stage0_iter18_grp5) & (1'b0 == ap_block_pp0_stage0_subdone_grp5_done_reg)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_done_reg == 1'b1) | ((1'b1 == ap_block_state2_pp0_stage1_iter0_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_done_reg == 1'b1) | ((1'b1 == ap_block_state2_pp0_stage1_iter0_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_done_reg == 1'b1) | ((1'b1 == ap_block_state2_pp0_stage1_iter0_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp0 = (ap_done_reg == 1'b1);
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b0 == ap_block_pp0_stage3_subdone_grp3_done_reg) & (stream_0_empty_n == 1'b0)) | ((1'b1 == ap_block_state4_io_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg))));
end

assign ap_block_pp0_stage3_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001_grp2 = ((1'b1 == ap_block_state4_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp3_done_reg) & (stream_0_empty_n == 1'b0));
end

assign ap_block_pp0_stage3_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (((1'b0 == ap_block_pp0_stage3_subdone_grp3_done_reg) & (stream_0_empty_n == 1'b0)) | ((1'b1 == ap_block_state4_io_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg))));
end

assign ap_block_pp0_stage3_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp2 = ((1'b1 == ap_block_state4_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp3_done_reg) & (stream_0_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = ((first_iter_010_reg_162 == 1'd1) & (mem_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_io_grp2 = ((m_axi_mem_0_0_AWREADY == 1'b0) & (first_iter_0_reg_454 == 1'd1));
end

always @ (*) begin
    ap_block_state5_io_grp4 = ((icmp_ln28_reg_463 == 1'd1) & (m_axi_mem_0_0_WREADY == 1'b0));
end

always @ (*) begin
    ap_block_state73_pp0_stage0_iter18_grp5 = ((icmp_ln26_reg_492_pp0_iter17_reg == 1'd1) & (m_axi_mem_0_0_BVALID == 1'b0));
end

always @ (*) begin
    ap_condition_730 = ((icmp_ln24_reg_497 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1));
end

always @ (*) begin
    ap_condition_734 = ((icmp_ln24_reg_497 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_738 = ((icmp_ln24_reg_497 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001));
end

always @ (*) begin
    ap_condition_744 = ((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg_iter0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign ap_ready = ap_ready_sig;

assign first_iter_0_fu_248_p2 = ((select_ln24_fu_240_p3 == 8'd0) ? 1'b1 : 1'b0);

assign i_fu_222_p3 = ((ap_phi_mux_icmp_ln266_phi_fu_178_p4[0:0] == 1'b1) ? add_ln247_fu_122 : i3_fu_110);

assign icmp_ln24_fu_351_p2 = ((indvar_flatten2_fu_106 == 10'd1023) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_343_p2 = ((j_reg_468 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_287_p2 = ((trunc_ln26_fu_283_p1 == 4'd15) ? 1'b1 : 1'b0);

assign j_fu_293_p2 = (select_ln24_fu_240_p3 + 8'd1);

assign m_axi_mem_0_0_ARADDR = 64'd0;

assign m_axi_mem_0_0_ARBURST = 2'd0;

assign m_axi_mem_0_0_ARCACHE = 4'd0;

assign m_axi_mem_0_0_ARID = 1'd0;

assign m_axi_mem_0_0_ARLEN = 32'd0;

assign m_axi_mem_0_0_ARLOCK = 2'd0;

assign m_axi_mem_0_0_ARPROT = 3'd0;

assign m_axi_mem_0_0_ARQOS = 4'd0;

assign m_axi_mem_0_0_ARREGION = 4'd0;

assign m_axi_mem_0_0_ARSIZE = 3'd0;

assign m_axi_mem_0_0_ARUSER = 1'd0;

assign m_axi_mem_0_0_ARVALID = 1'b0;

assign m_axi_mem_0_0_AWADDR = sext_ln26_fu_316_p1;

assign m_axi_mem_0_0_AWBURST = 2'd0;

assign m_axi_mem_0_0_AWCACHE = 4'd0;

assign m_axi_mem_0_0_AWID = 1'd0;

assign m_axi_mem_0_0_AWLEN = 64'd8;

assign m_axi_mem_0_0_AWLOCK = 2'd0;

assign m_axi_mem_0_0_AWPROT = 3'd0;

assign m_axi_mem_0_0_AWQOS = 4'd0;

assign m_axi_mem_0_0_AWREGION = 4'd0;

assign m_axi_mem_0_0_AWSIZE = 3'd0;

assign m_axi_mem_0_0_AWUSER = 1'd0;

assign m_axi_mem_0_0_RREADY = 1'b0;

assign m_axi_mem_0_0_WDATA = {{stream_0_read_reg_480}, {select_ln24_4_reg_486}};

assign m_axi_mem_0_0_WID = 1'd0;

assign m_axi_mem_0_0_WLAST = 1'b0;

assign m_axi_mem_0_0_WSTRB = 64'd18446744073709551615;

assign m_axi_mem_0_0_WUSER = 1'd0;

assign select_ln24_4_fu_335_p3 = ((icmp_ln266_reg_175[0:0] == 1'b1) ? 480'd0 : phi_ln285_fu_118);

assign select_ln24_fu_240_p3 = ((icmp_ln266_reg_175[0:0] == 1'b1) ? 8'd0 : j4_fu_114);

assign select_ln28_fu_389_p3 = ((icmp_ln28_reg_463[0:0] == 1'b1) ? 480'd0 : tmp_4_fu_382_p3);

assign sext_ln26_fu_316_p1 = $signed(trunc_ln_reg_458);

assign tmp_3_fu_373_p4 = {{select_ln24_4_reg_486[479:32]}};

assign tmp_4_fu_382_p3 = {{stream_0_read_reg_480}, {tmp_3_fu_373_p4}};

assign trunc_ln25_fu_230_p1 = i_fu_222_p3[2:0];

assign trunc_ln26_fu_283_p1 = select_ln24_fu_240_p3[3:0];

assign zext_ln25_cast_fu_254_p4 = {{{{1'd1}, {trunc_ln25_reg_449}}}, {10'd0}};

assign zext_ln25_fu_263_p1 = zext_ln25_cast_fu_254_p4;

endmodule //read_write_write_r
