// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matrix_mul_matrix_mul_Pipeline_compute_row_loop_compute_col_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_tile_address0,
        A_tile_ce0,
        A_tile_q0,
        A_tile_1_address0,
        A_tile_1_ce0,
        A_tile_1_q0,
        A_tile_2_address0,
        A_tile_2_ce0,
        A_tile_2_q0,
        A_tile_3_address0,
        A_tile_3_ce0,
        A_tile_3_q0,
        C_local_address0,
        C_local_ce0,
        C_local_we0,
        C_local_d0,
        C_local_address1,
        C_local_ce1,
        C_local_q1,
        C_local_1_address0,
        C_local_1_ce0,
        C_local_1_we0,
        C_local_1_d0,
        C_local_1_address1,
        C_local_1_ce1,
        C_local_1_q1,
        C_local_2_address0,
        C_local_2_ce0,
        C_local_2_we0,
        C_local_2_d0,
        C_local_2_address1,
        C_local_2_ce1,
        C_local_2_q1,
        C_local_3_address0,
        C_local_3_ce0,
        C_local_3_we0,
        C_local_3_d0,
        C_local_3_address1,
        C_local_3_ce1,
        C_local_3_q1,
        B_tile_address0,
        B_tile_ce0,
        B_tile_q0,
        B_tile_1_address0,
        B_tile_1_ce0,
        B_tile_1_q0,
        B_tile_2_address0,
        B_tile_2_ce0,
        B_tile_2_q0,
        B_tile_3_address0,
        B_tile_3_ce0,
        B_tile_3_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] A_tile_address0;
output   A_tile_ce0;
input  [31:0] A_tile_q0;
output  [3:0] A_tile_1_address0;
output   A_tile_1_ce0;
input  [31:0] A_tile_1_q0;
output  [3:0] A_tile_2_address0;
output   A_tile_2_ce0;
input  [31:0] A_tile_2_q0;
output  [3:0] A_tile_3_address0;
output   A_tile_3_ce0;
input  [31:0] A_tile_3_q0;
output  [5:0] C_local_address0;
output   C_local_ce0;
output   C_local_we0;
output  [31:0] C_local_d0;
output  [5:0] C_local_address1;
output   C_local_ce1;
input  [31:0] C_local_q1;
output  [5:0] C_local_1_address0;
output   C_local_1_ce0;
output   C_local_1_we0;
output  [31:0] C_local_1_d0;
output  [5:0] C_local_1_address1;
output   C_local_1_ce1;
input  [31:0] C_local_1_q1;
output  [5:0] C_local_2_address0;
output   C_local_2_ce0;
output   C_local_2_we0;
output  [31:0] C_local_2_d0;
output  [5:0] C_local_2_address1;
output   C_local_2_ce1;
input  [31:0] C_local_2_q1;
output  [5:0] C_local_3_address0;
output   C_local_3_ce0;
output   C_local_3_we0;
output  [31:0] C_local_3_d0;
output  [5:0] C_local_3_address1;
output   C_local_3_ce1;
input  [31:0] C_local_3_q1;
output  [3:0] B_tile_address0;
output   B_tile_ce0;
input  [31:0] B_tile_q0;
output  [3:0] B_tile_1_address0;
output   B_tile_1_ce0;
input  [31:0] B_tile_1_q0;
output  [3:0] B_tile_2_address0;
output   B_tile_2_ce0;
input  [31:0] B_tile_2_q0;
output  [3:0] B_tile_3_address0;
output   B_tile_3_ce0;
input  [31:0] B_tile_3_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln57_fu_292_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] trunc_ln57_fu_338_p1;
reg   [3:0] trunc_ln57_reg_489;
reg   [3:0] trunc_ln57_reg_489_pp0_iter1_reg;
wire   [1:0] trunc_ln59_fu_358_p1;
reg   [1:0] trunc_ln59_reg_514;
reg   [1:0] trunc_ln59_reg_514_pp0_iter1_reg;
reg   [1:0] trunc_ln59_reg_514_pp0_iter2_reg;
reg   [1:0] lshr_ln3_reg_519;
reg   [1:0] lshr_ln3_reg_519_pp0_iter1_reg;
reg  signed [31:0] A_tile_load_reg_544;
reg  signed [31:0] A_tile_1_load_reg_549;
reg  signed [31:0] A_tile_2_load_reg_554;
reg  signed [31:0] A_tile_3_load_reg_559;
reg  signed [31:0] B_tile_load_reg_564;
reg  signed [31:0] B_tile_1_load_reg_569;
reg  signed [31:0] B_tile_2_load_reg_574;
reg  signed [31:0] B_tile_3_load_reg_579;
reg   [5:0] C_local_addr_reg_584;
reg   [5:0] C_local_1_addr_reg_590;
reg   [5:0] C_local_2_addr_reg_596;
reg   [5:0] C_local_3_addr_reg_602;
wire   [31:0] mul_ln68_fu_258_p2;
reg   [31:0] mul_ln68_reg_608;
wire   [31:0] mul_ln68_1_fu_262_p2;
reg   [31:0] mul_ln68_1_reg_613;
wire   [31:0] mul_ln68_2_fu_266_p2;
reg   [31:0] mul_ln68_2_reg_618;
wire   [31:0] mul_ln68_3_fu_270_p2;
reg   [31:0] mul_ln68_3_reg_623;
wire   [63:0] zext_ln57_fu_342_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln59_fu_350_p1;
wire   [63:0] zext_ln63_fu_409_p1;
reg   [4:0] col_fu_74;
wire   [4:0] add_ln59_fu_382_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_col_load;
reg   [4:0] row_fu_78;
wire   [4:0] select_ln57_1_fu_330_p3;
reg   [4:0] ap_sig_allocacmp_row_load;
reg   [8:0] indvar_flatten22_fu_82;
wire   [8:0] add_ln57_1_fu_298_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten22_load;
reg    A_tile_ce0_local;
reg    A_tile_1_ce0_local;
reg    A_tile_2_ce0_local;
reg    A_tile_3_ce0_local;
reg    B_tile_ce0_local;
reg    B_tile_1_ce0_local;
reg    B_tile_2_ce0_local;
reg    B_tile_3_ce0_local;
reg    C_local_ce1_local;
reg    C_local_we0_local;
wire   [31:0] sum_1_fu_454_p2;
reg    C_local_ce0_local;
reg    C_local_1_ce1_local;
reg    C_local_1_we0_local;
reg    C_local_1_ce0_local;
reg    C_local_2_ce1_local;
reg    C_local_2_we0_local;
reg    C_local_2_ce0_local;
reg    C_local_3_ce1_local;
reg    C_local_3_we0_local;
reg    C_local_3_ce0_local;
wire   [0:0] icmp_ln59_fu_316_p2;
wire   [4:0] add_ln57_fu_310_p2;
wire   [4:0] select_ln57_fu_322_p3;
wire   [5:0] tmp_5_fu_403_p3;
wire   [31:0] sum_fu_417_p9;
wire   [31:0] add_ln68_1_fu_444_p2;
wire   [31:0] sum_fu_417_p11;
wire   [31:0] add_ln68_2_fu_448_p2;
wire   [31:0] add_ln68_fu_440_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] sum_fu_417_p1;
wire   [1:0] sum_fu_417_p3;
wire  signed [1:0] sum_fu_417_p5;
wire  signed [1:0] sum_fu_417_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 col_fu_74 = 5'd0;
#0 row_fu_78 = 5'd0;
#0 indvar_flatten22_fu_82 = 9'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mul_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U18(
    .din0(B_tile_load_reg_564),
    .din1(A_tile_load_reg_544),
    .dout(mul_ln68_fu_258_p2)
);

matrix_mul_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U19(
    .din0(B_tile_3_load_reg_579),
    .din1(A_tile_3_load_reg_559),
    .dout(mul_ln68_1_fu_262_p2)
);

matrix_mul_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U20(
    .din0(B_tile_2_load_reg_574),
    .din1(A_tile_2_load_reg_554),
    .dout(mul_ln68_2_fu_266_p2)
);

matrix_mul_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U21(
    .din0(B_tile_1_load_reg_569),
    .din1(A_tile_1_load_reg_549),
    .dout(mul_ln68_3_fu_270_p2)
);

(* dissolve_hierarchy = "yes" *) matrix_mul_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U22(
    .din0(C_local_q1),
    .din1(C_local_1_q1),
    .din2(C_local_2_q1),
    .din3(C_local_3_q1),
    .def(sum_fu_417_p9),
    .sel(trunc_ln59_reg_514_pp0_iter2_reg),
    .dout(sum_fu_417_p11)
);

matrix_mul_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln57_fu_292_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            col_fu_74 <= add_ln59_fu_382_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_fu_74 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln57_fu_292_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten22_fu_82 <= add_ln57_1_fu_298_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten22_fu_82 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln57_fu_292_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            row_fu_78 <= select_ln57_1_fu_330_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            row_fu_78 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_tile_1_load_reg_549 <= A_tile_1_q0;
        A_tile_2_load_reg_554 <= A_tile_2_q0;
        A_tile_3_load_reg_559 <= A_tile_3_q0;
        A_tile_load_reg_544 <= A_tile_q0;
        B_tile_1_load_reg_569 <= B_tile_1_q0;
        B_tile_2_load_reg_574 <= B_tile_2_q0;
        B_tile_3_load_reg_579 <= B_tile_3_q0;
        B_tile_load_reg_564 <= B_tile_q0;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        lshr_ln3_reg_519 <= {{select_ln57_fu_322_p3[3:2]}};
        lshr_ln3_reg_519_pp0_iter1_reg <= lshr_ln3_reg_519;
        trunc_ln57_reg_489 <= trunc_ln57_fu_338_p1;
        trunc_ln57_reg_489_pp0_iter1_reg <= trunc_ln57_reg_489;
        trunc_ln59_reg_514 <= trunc_ln59_fu_358_p1;
        trunc_ln59_reg_514_pp0_iter1_reg <= trunc_ln59_reg_514;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        C_local_1_addr_reg_590 <= zext_ln63_fu_409_p1;
        C_local_2_addr_reg_596 <= zext_ln63_fu_409_p1;
        C_local_3_addr_reg_602 <= zext_ln63_fu_409_p1;
        C_local_addr_reg_584 <= zext_ln63_fu_409_p1;
        mul_ln68_1_reg_613 <= mul_ln68_1_fu_262_p2;
        mul_ln68_2_reg_618 <= mul_ln68_2_fu_266_p2;
        mul_ln68_3_reg_623 <= mul_ln68_3_fu_270_p2;
        mul_ln68_reg_608 <= mul_ln68_fu_258_p2;
        trunc_ln59_reg_514_pp0_iter2_reg <= trunc_ln59_reg_514_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_tile_1_ce0_local = 1'b1;
    end else begin
        A_tile_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_tile_2_ce0_local = 1'b1;
    end else begin
        A_tile_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_tile_3_ce0_local = 1'b1;
    end else begin
        A_tile_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_tile_ce0_local = 1'b1;
    end else begin
        A_tile_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_tile_1_ce0_local = 1'b1;
    end else begin
        B_tile_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_tile_2_ce0_local = 1'b1;
    end else begin
        B_tile_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_tile_3_ce0_local = 1'b1;
    end else begin
        B_tile_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_tile_ce0_local = 1'b1;
    end else begin
        B_tile_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        C_local_1_ce0_local = 1'b1;
    end else begin
        C_local_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_local_1_ce1_local = 1'b1;
    end else begin
        C_local_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln59_reg_514_pp0_iter2_reg == 2'd1))) begin
        C_local_1_we0_local = 1'b1;
    end else begin
        C_local_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        C_local_2_ce0_local = 1'b1;
    end else begin
        C_local_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_local_2_ce1_local = 1'b1;
    end else begin
        C_local_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln59_reg_514_pp0_iter2_reg == 2'd2))) begin
        C_local_2_we0_local = 1'b1;
    end else begin
        C_local_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        C_local_3_ce0_local = 1'b1;
    end else begin
        C_local_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_local_3_ce1_local = 1'b1;
    end else begin
        C_local_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln59_reg_514_pp0_iter2_reg == 2'd3))) begin
        C_local_3_we0_local = 1'b1;
    end else begin
        C_local_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        C_local_ce0_local = 1'b1;
    end else begin
        C_local_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_local_ce1_local = 1'b1;
    end else begin
        C_local_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln59_reg_514_pp0_iter2_reg == 2'd0))) begin
        C_local_we0_local = 1'b1;
    end else begin
        C_local_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln57_fu_292_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_col_load = 5'd0;
    end else begin
        ap_sig_allocacmp_col_load = col_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten22_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten22_load = indvar_flatten22_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_row_load = 5'd0;
    end else begin
        ap_sig_allocacmp_row_load = row_fu_78;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_tile_1_address0 = zext_ln57_fu_342_p1;

assign A_tile_1_ce0 = A_tile_1_ce0_local;

assign A_tile_2_address0 = zext_ln57_fu_342_p1;

assign A_tile_2_ce0 = A_tile_2_ce0_local;

assign A_tile_3_address0 = zext_ln57_fu_342_p1;

assign A_tile_3_ce0 = A_tile_3_ce0_local;

assign A_tile_address0 = zext_ln57_fu_342_p1;

assign A_tile_ce0 = A_tile_ce0_local;

assign B_tile_1_address0 = zext_ln59_fu_350_p1;

assign B_tile_1_ce0 = B_tile_1_ce0_local;

assign B_tile_2_address0 = zext_ln59_fu_350_p1;

assign B_tile_2_ce0 = B_tile_2_ce0_local;

assign B_tile_3_address0 = zext_ln59_fu_350_p1;

assign B_tile_3_ce0 = B_tile_3_ce0_local;

assign B_tile_address0 = zext_ln59_fu_350_p1;

assign B_tile_ce0 = B_tile_ce0_local;

assign C_local_1_address0 = C_local_1_addr_reg_590;

assign C_local_1_address1 = zext_ln63_fu_409_p1;

assign C_local_1_ce0 = C_local_1_ce0_local;

assign C_local_1_ce1 = C_local_1_ce1_local;

assign C_local_1_d0 = sum_1_fu_454_p2;

assign C_local_1_we0 = C_local_1_we0_local;

assign C_local_2_address0 = C_local_2_addr_reg_596;

assign C_local_2_address1 = zext_ln63_fu_409_p1;

assign C_local_2_ce0 = C_local_2_ce0_local;

assign C_local_2_ce1 = C_local_2_ce1_local;

assign C_local_2_d0 = sum_1_fu_454_p2;

assign C_local_2_we0 = C_local_2_we0_local;

assign C_local_3_address0 = C_local_3_addr_reg_602;

assign C_local_3_address1 = zext_ln63_fu_409_p1;

assign C_local_3_ce0 = C_local_3_ce0_local;

assign C_local_3_ce1 = C_local_3_ce1_local;

assign C_local_3_d0 = sum_1_fu_454_p2;

assign C_local_3_we0 = C_local_3_we0_local;

assign C_local_address0 = C_local_addr_reg_584;

assign C_local_address1 = zext_ln63_fu_409_p1;

assign C_local_ce0 = C_local_ce0_local;

assign C_local_ce1 = C_local_ce1_local;

assign C_local_d0 = sum_1_fu_454_p2;

assign C_local_we0 = C_local_we0_local;

assign add_ln57_1_fu_298_p2 = (ap_sig_allocacmp_indvar_flatten22_load + 9'd1);

assign add_ln57_fu_310_p2 = (ap_sig_allocacmp_row_load + 5'd1);

assign add_ln59_fu_382_p2 = (select_ln57_fu_322_p3 + 5'd1);

assign add_ln68_1_fu_444_p2 = (mul_ln68_reg_608 + mul_ln68_1_reg_613);

assign add_ln68_2_fu_448_p2 = (add_ln68_1_fu_444_p2 + sum_fu_417_p11);

assign add_ln68_fu_440_p2 = (mul_ln68_3_reg_623 + mul_ln68_2_reg_618);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln57_fu_292_p2 = ((ap_sig_allocacmp_indvar_flatten22_load == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_316_p2 = ((ap_sig_allocacmp_col_load == 5'd16) ? 1'b1 : 1'b0);

assign select_ln57_1_fu_330_p3 = ((icmp_ln59_fu_316_p2[0:0] == 1'b1) ? add_ln57_fu_310_p2 : ap_sig_allocacmp_row_load);

assign select_ln57_fu_322_p3 = ((icmp_ln59_fu_316_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_col_load);

assign sum_1_fu_454_p2 = (add_ln68_2_fu_448_p2 + add_ln68_fu_440_p2);

assign sum_fu_417_p9 = 'bx;

assign tmp_5_fu_403_p3 = {{trunc_ln57_reg_489_pp0_iter1_reg}, {lshr_ln3_reg_519_pp0_iter1_reg}};

assign trunc_ln57_fu_338_p1 = select_ln57_1_fu_330_p3[3:0];

assign trunc_ln59_fu_358_p1 = select_ln57_fu_322_p3[1:0];

assign zext_ln57_fu_342_p1 = select_ln57_1_fu_330_p3;

assign zext_ln59_fu_350_p1 = select_ln57_fu_322_p3;

assign zext_ln63_fu_409_p1 = tmp_5_fu_403_p3;

endmodule //matrix_mul_matrix_mul_Pipeline_compute_row_loop_compute_col_loop
