

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_tile_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_tile_1_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_tile_2_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_tile_3_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_tile_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_tile_1_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_tile_2_U"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_tile_3_U"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_local_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_local_1_U"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_local_2_U"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_local_3_U"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_init_c_loop_init_c_col_loop_fu_197"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_init_c_loop_init_c_col_loop_fu_197.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_load_a_tile_row_loop_load_a_tile_lane_loop_fu_209"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_load_a_tile_row_loop_load_a_tile_lane_loop_fu_209.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_load_b_tile_lane_loop_load_b_tile_col_loop_fu_221"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_load_b_tile_lane_loop_load_b_tile_col_loop_fu_221.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_compute_row_loop_compute_col_loop_fu_232"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_compute_row_loop_compute_col_loop_fu_232.mul_32s_32s_32_1_1_U18"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_compute_row_loop_compute_col_loop_fu_232.mul_32s_32s_32_1_1_U19"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_compute_row_loop_compute_col_loop_fu_232.mul_32s_32s_32_1_1_U20"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_compute_row_loop_compute_col_loop_fu_232.mul_32s_32s_32_1_1_U21"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_compute_row_loop_compute_col_loop_fu_232.sparsemux_9_2_32_1_1_U22"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_compute_row_loop_compute_col_loop_fu_232.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_store_c_loop_fu_248"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_store_c_loop_fu_248.sparsemux_9_2_32_1_1_U37"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matrix_mul_Pipeline_store_c_loop_fu_248.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_a_m_axi_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_b_m_axi_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_c_m_axi_U"}]}
set DependenceCheckSize 0
