// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matrix_mul_matrix_mul_Pipeline_init_c_loop_init_c_col_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        C_local_address0,
        C_local_ce0,
        C_local_we0,
        C_local_d0,
        C_local_1_address0,
        C_local_1_ce0,
        C_local_1_we0,
        C_local_1_d0,
        C_local_2_address0,
        C_local_2_ce0,
        C_local_2_we0,
        C_local_2_d0,
        C_local_3_address0,
        C_local_3_ce0,
        C_local_3_we0,
        C_local_3_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] C_local_address0;
output   C_local_ce0;
output   C_local_we0;
output  [31:0] C_local_d0;
output  [5:0] C_local_1_address0;
output   C_local_1_ce0;
output   C_local_1_we0;
output  [31:0] C_local_1_d0;
output  [5:0] C_local_2_address0;
output   C_local_2_ce0;
output   C_local_2_we0;
output  [31:0] C_local_2_d0;
output  [5:0] C_local_3_address0;
output   C_local_3_ce0;
output   C_local_3_we0;
output  [31:0] C_local_3_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln27_fu_138_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln31_fu_210_p1;
reg   [4:0] col_fu_52;
wire   [4:0] add_ln29_fu_228_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_col_load;
reg   [4:0] row_fu_56;
wire   [4:0] select_ln27_1_fu_176_p3;
reg   [4:0] ap_sig_allocacmp_row_load;
reg   [8:0] indvar_flatten_fu_60;
wire   [8:0] add_ln27_1_fu_144_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten_load;
reg    C_local_2_we0_local;
wire   [1:0] trunc_ln29_1_fu_188_p1;
reg    C_local_2_ce0_local;
reg    C_local_1_we0_local;
reg    C_local_1_ce0_local;
reg    C_local_we0_local;
reg    C_local_ce0_local;
reg    C_local_3_we0_local;
reg    C_local_3_ce0_local;
wire   [0:0] icmp_ln29_fu_162_p2;
wire   [4:0] add_ln27_fu_156_p2;
wire   [4:0] select_ln27_fu_168_p3;
wire   [3:0] trunc_ln29_fu_184_p1;
wire   [1:0] lshr_ln_fu_192_p4;
wire   [5:0] tmp_1_fu_202_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 col_fu_52 = 5'd0;
#0 row_fu_56 = 5'd0;
#0 indvar_flatten_fu_60 = 9'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mul_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln27_fu_138_p2 == 1'd0)) begin
            col_fu_52 <= add_ln29_fu_228_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_fu_52 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln27_fu_138_p2 == 1'd0)) begin
            indvar_flatten_fu_60 <= add_ln27_1_fu_144_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_60 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln27_fu_138_p2 == 1'd0)) begin
            row_fu_56 <= select_ln27_1_fu_176_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            row_fu_56 <= 5'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_local_1_ce0_local = 1'b1;
    end else begin
        C_local_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln29_1_fu_188_p1 == 2'd1) & (icmp_ln27_fu_138_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_local_1_we0_local = 1'b1;
    end else begin
        C_local_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_local_2_ce0_local = 1'b1;
    end else begin
        C_local_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln29_1_fu_188_p1 == 2'd2) & (icmp_ln27_fu_138_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_local_2_we0_local = 1'b1;
    end else begin
        C_local_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_local_3_ce0_local = 1'b1;
    end else begin
        C_local_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln29_1_fu_188_p1 == 2'd3) & (icmp_ln27_fu_138_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_local_3_we0_local = 1'b1;
    end else begin
        C_local_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_local_ce0_local = 1'b1;
    end else begin
        C_local_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln29_1_fu_188_p1 == 2'd0) & (icmp_ln27_fu_138_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        C_local_we0_local = 1'b1;
    end else begin
        C_local_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_fu_138_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_col_load = 5'd0;
    end else begin
        ap_sig_allocacmp_col_load = col_fu_52;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_60;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_row_load = 5'd0;
    end else begin
        ap_sig_allocacmp_row_load = row_fu_56;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_local_1_address0 = zext_ln31_fu_210_p1;

assign C_local_1_ce0 = C_local_1_ce0_local;

assign C_local_1_d0 = 32'd0;

assign C_local_1_we0 = C_local_1_we0_local;

assign C_local_2_address0 = zext_ln31_fu_210_p1;

assign C_local_2_ce0 = C_local_2_ce0_local;

assign C_local_2_d0 = 32'd0;

assign C_local_2_we0 = C_local_2_we0_local;

assign C_local_3_address0 = zext_ln31_fu_210_p1;

assign C_local_3_ce0 = C_local_3_ce0_local;

assign C_local_3_d0 = 32'd0;

assign C_local_3_we0 = C_local_3_we0_local;

assign C_local_address0 = zext_ln31_fu_210_p1;

assign C_local_ce0 = C_local_ce0_local;

assign C_local_d0 = 32'd0;

assign C_local_we0 = C_local_we0_local;

assign add_ln27_1_fu_144_p2 = (ap_sig_allocacmp_indvar_flatten_load + 9'd1);

assign add_ln27_fu_156_p2 = (ap_sig_allocacmp_row_load + 5'd1);

assign add_ln29_fu_228_p2 = (select_ln27_fu_168_p3 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln27_fu_138_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_162_p2 = ((ap_sig_allocacmp_col_load == 5'd16) ? 1'b1 : 1'b0);

assign lshr_ln_fu_192_p4 = {{select_ln27_fu_168_p3[3:2]}};

assign select_ln27_1_fu_176_p3 = ((icmp_ln29_fu_162_p2[0:0] == 1'b1) ? add_ln27_fu_156_p2 : ap_sig_allocacmp_row_load);

assign select_ln27_fu_168_p3 = ((icmp_ln29_fu_162_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_col_load);

assign tmp_1_fu_202_p3 = {{trunc_ln29_fu_184_p1}, {lshr_ln_fu_192_p4}};

assign trunc_ln29_1_fu_188_p1 = select_ln27_fu_168_p3[1:0];

assign trunc_ln29_fu_184_p1 = select_ln27_1_fu_176_p3[3:0];

assign zext_ln31_fu_210_p1 = tmp_1_fu_202_p3;

endmodule //matrix_mul_matrix_mul_Pipeline_init_c_loop_init_c_col_loop
