-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mul_matrix_mul_Pipeline_load_b_tile_lane_loop_load_b_tile_col_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_b_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_b_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_b_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_b_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_b_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_b_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_b_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_b_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_b_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_b_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_b_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_b_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_b_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_b_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_b_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_b_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_b_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_b_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_b_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_b_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_b_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_b_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_RFIFONUM : IN STD_LOGIC_VECTOR (4 downto 0);
    m_axi_gmem_b_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_b_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_b_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    B_tile_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_tile_3_ce0 : OUT STD_LOGIC;
    B_tile_3_we0 : OUT STD_LOGIC;
    B_tile_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_tile_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_tile_2_ce0 : OUT STD_LOGIC;
    B_tile_2_we0 : OUT STD_LOGIC;
    B_tile_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_tile_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_tile_1_ce0 : OUT STD_LOGIC;
    B_tile_1_we0 : OUT STD_LOGIC;
    B_tile_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_tile_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_tile_ce0 : OUT STD_LOGIC;
    B_tile_we0 : OUT STD_LOGIC;
    B_tile_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    sext_ln36 : IN STD_LOGIC_VECTOR (57 downto 0) );
end;


architecture behav of matrix_mul_matrix_mul_Pipeline_load_b_tile_lane_loop_load_b_tile_col_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln48_reg_349 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_2_reg_358 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op38_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln48_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_b_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln48_reg_349_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln48_fu_216_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln48_reg_353 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln48_reg_353_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal first_iter_2_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_2_reg_358_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln48_fu_238_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_362 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_362_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_b_addr_read_reg_366 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_mux_gmem_b_addr_read2_phi_fu_158_p4 : STD_LOGIC_VECTOR (511 downto 0);
    signal shiftreg11_cast_fu_282_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter2_gmem_b_addr_read2_reg_155 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln50_fu_287_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shiftreg11_fu_76 : STD_LOGIC_VECTOR (479 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal col_fu_80 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln50_fu_252_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_col_load : STD_LOGIC_VECTOR (4 downto 0);
    signal lane_fu_84 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln48_1_fu_224_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_lane_load : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten15_fu_88 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln48_1_fu_192_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_indvar_flatten15_load : STD_LOGIC_VECTOR (6 downto 0);
    signal B_tile_2_we0_local : STD_LOGIC;
    signal trunc_ln52_fu_294_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_tile_2_ce0_local : STD_LOGIC;
    signal B_tile_1_we0_local : STD_LOGIC;
    signal B_tile_1_ce0_local : STD_LOGIC;
    signal B_tile_we0_local : STD_LOGIC;
    signal B_tile_ce0_local : STD_LOGIC;
    signal B_tile_3_we0_local : STD_LOGIC;
    signal B_tile_3_ce0_local : STD_LOGIC;
    signal icmp_ln50_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln48_fu_204_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mul_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component matrix_mul_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    col_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln48_fu_186_p2 = ap_const_lv1_0))) then 
                    col_fu_80 <= add_ln50_fu_252_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    col_fu_80 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten15_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln48_fu_186_p2 = ap_const_lv1_0))) then 
                    indvar_flatten15_fu_88 <= add_ln48_1_fu_192_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten15_fu_88 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    lane_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln48_fu_186_p2 = ap_const_lv1_0))) then 
                    lane_fu_84 <= select_ln48_1_fu_224_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    lane_fu_84 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                first_iter_2_reg_358 <= first_iter_2_fu_232_p2;
                first_iter_2_reg_358_pp0_iter1_reg <= first_iter_2_reg_358;
                gmem_b_addr_read_reg_366 <= m_axi_gmem_b_0_RDATA;
                icmp_ln48_reg_349 <= icmp_ln48_fu_186_p2;
                icmp_ln48_reg_349_pp0_iter1_reg <= icmp_ln48_reg_349;
                select_ln48_reg_353 <= select_ln48_fu_216_p3;
                select_ln48_reg_353_pp0_iter1_reg <= select_ln48_reg_353;
                trunc_ln48_reg_362 <= trunc_ln48_fu_238_p1;
                trunc_ln48_reg_362_pp0_iter1_reg <= trunc_ln48_reg_362;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln48_reg_349_pp0_iter1_reg = ap_const_lv1_0))) then
                shiftreg11_fu_76 <= ap_phi_mux_gmem_b_addr_read2_phi_fu_158_p4(511 downto 32);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    B_tile_1_address0 <= zext_ln50_fu_287_p1(4 - 1 downto 0);
    B_tile_1_ce0 <= B_tile_1_ce0_local;

    B_tile_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_tile_1_ce0_local <= ap_const_logic_1;
        else 
            B_tile_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_tile_1_d0 <= trunc_ln52_fu_294_p1;
    B_tile_1_we0 <= B_tile_1_we0_local;

    B_tile_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln48_reg_349_pp0_iter1_reg, trunc_ln48_reg_362_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln48_reg_362_pp0_iter1_reg = ap_const_lv2_1) and (icmp_ln48_reg_349_pp0_iter1_reg = ap_const_lv1_0))) then 
            B_tile_1_we0_local <= ap_const_logic_1;
        else 
            B_tile_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_tile_2_address0 <= zext_ln50_fu_287_p1(4 - 1 downto 0);
    B_tile_2_ce0 <= B_tile_2_ce0_local;

    B_tile_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_tile_2_ce0_local <= ap_const_logic_1;
        else 
            B_tile_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_tile_2_d0 <= trunc_ln52_fu_294_p1;
    B_tile_2_we0 <= B_tile_2_we0_local;

    B_tile_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln48_reg_349_pp0_iter1_reg, trunc_ln48_reg_362_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln48_reg_362_pp0_iter1_reg = ap_const_lv2_2) and (icmp_ln48_reg_349_pp0_iter1_reg = ap_const_lv1_0))) then 
            B_tile_2_we0_local <= ap_const_logic_1;
        else 
            B_tile_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_tile_3_address0 <= zext_ln50_fu_287_p1(4 - 1 downto 0);
    B_tile_3_ce0 <= B_tile_3_ce0_local;

    B_tile_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_tile_3_ce0_local <= ap_const_logic_1;
        else 
            B_tile_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_tile_3_d0 <= trunc_ln52_fu_294_p1;
    B_tile_3_we0 <= B_tile_3_we0_local;

    B_tile_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln48_reg_349_pp0_iter1_reg, trunc_ln48_reg_362_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln48_reg_362_pp0_iter1_reg = ap_const_lv2_3) and (icmp_ln48_reg_349_pp0_iter1_reg = ap_const_lv1_0))) then 
            B_tile_3_we0_local <= ap_const_logic_1;
        else 
            B_tile_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_tile_address0 <= zext_ln50_fu_287_p1(4 - 1 downto 0);
    B_tile_ce0 <= B_tile_ce0_local;

    B_tile_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_tile_ce0_local <= ap_const_logic_1;
        else 
            B_tile_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_tile_d0 <= trunc_ln52_fu_294_p1;
    B_tile_we0 <= B_tile_we0_local;

    B_tile_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln48_reg_349_pp0_iter1_reg, trunc_ln48_reg_362_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln48_reg_362_pp0_iter1_reg = ap_const_lv2_0) and (icmp_ln48_reg_349_pp0_iter1_reg = ap_const_lv1_0))) then 
            B_tile_we0_local <= ap_const_logic_1;
        else 
            B_tile_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln48_1_fu_192_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten15_load) + unsigned(ap_const_lv7_1));
    add_ln48_fu_204_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_lane_load) + unsigned(ap_const_lv3_1));
    add_ln50_fu_252_p2 <= std_logic_vector(unsigned(select_ln48_fu_216_p3) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_gmem_b_0_RVALID, ap_predicate_op38_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_predicate_op38_read_state2 = ap_const_boolean_1) and (m_axi_gmem_b_0_RVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln48_fu_186_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln48_fu_186_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_gmem_b_addr_read2_phi_fu_158_p4_assign_proc : process(icmp_ln48_reg_349_pp0_iter1_reg, first_iter_2_reg_358_pp0_iter1_reg, gmem_b_addr_read_reg_366, shiftreg11_cast_fu_282_p1, ap_phi_reg_pp0_iter2_gmem_b_addr_read2_reg_155)
    begin
        if ((icmp_ln48_reg_349_pp0_iter1_reg = ap_const_lv1_0)) then
            if ((first_iter_2_reg_358_pp0_iter1_reg = ap_const_lv1_1)) then 
                ap_phi_mux_gmem_b_addr_read2_phi_fu_158_p4 <= gmem_b_addr_read_reg_366;
            elsif ((first_iter_2_reg_358_pp0_iter1_reg = ap_const_lv1_0)) then 
                ap_phi_mux_gmem_b_addr_read2_phi_fu_158_p4 <= shiftreg11_cast_fu_282_p1;
            else 
                ap_phi_mux_gmem_b_addr_read2_phi_fu_158_p4 <= ap_phi_reg_pp0_iter2_gmem_b_addr_read2_reg_155;
            end if;
        else 
            ap_phi_mux_gmem_b_addr_read2_phi_fu_158_p4 <= ap_phi_reg_pp0_iter2_gmem_b_addr_read2_reg_155;
        end if; 
    end process;

    ap_phi_reg_pp0_iter2_gmem_b_addr_read2_reg_155 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op38_read_state2_assign_proc : process(icmp_ln48_reg_349, first_iter_2_reg_358)
    begin
                ap_predicate_op38_read_state2 <= ((first_iter_2_reg_358 = ap_const_lv1_1) and (icmp_ln48_reg_349 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_col_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, col_fu_80, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_col_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_col_load <= col_fu_80;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten15_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten15_fu_88)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten15_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten15_load <= indvar_flatten15_fu_88;
        end if; 
    end process;


    ap_sig_allocacmp_lane_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, lane_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_lane_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_lane_load <= lane_fu_84;
        end if; 
    end process;

    first_iter_2_fu_232_p2 <= "1" when (select_ln48_fu_216_p3 = ap_const_lv5_0) else "0";

    gmem_b_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_b_0_RVALID, ap_predicate_op38_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op38_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem_b_blk_n_R <= m_axi_gmem_b_0_RVALID;
        else 
            gmem_b_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln48_fu_186_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten15_load = ap_const_lv7_40) else "0";
    icmp_ln50_fu_210_p2 <= "1" when (ap_sig_allocacmp_col_load = ap_const_lv5_10) else "0";
    m_axi_gmem_b_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_b_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_b_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_b_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_b_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_b_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_b_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_b_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_b_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_b_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_b_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_b_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_b_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_b_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_b_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_b_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_b_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_b_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_b_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_b_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_b_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_b_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_b_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_b_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_b_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_b_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op38_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op38_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem_b_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_b_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_b_0_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem_b_0_WID <= ap_const_lv1_0;
    m_axi_gmem_b_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_b_0_WSTRB <= ap_const_lv64_0;
    m_axi_gmem_b_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_b_0_WVALID <= ap_const_logic_0;
    select_ln48_1_fu_224_p3 <= 
        add_ln48_fu_204_p2 when (icmp_ln50_fu_210_p2(0) = '1') else 
        ap_sig_allocacmp_lane_load;
    select_ln48_fu_216_p3 <= 
        ap_const_lv5_0 when (icmp_ln50_fu_210_p2(0) = '1') else 
        ap_sig_allocacmp_col_load;
    shiftreg11_cast_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shiftreg11_fu_76),512));
    trunc_ln48_fu_238_p1 <= select_ln48_1_fu_224_p3(2 - 1 downto 0);
    trunc_ln52_fu_294_p1 <= ap_phi_mux_gmem_b_addr_read2_phi_fu_158_p4(32 - 1 downto 0);
    zext_ln50_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln48_reg_353_pp0_iter1_reg),64));
end behav;
