// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matmul_row_col_matmul_row_col_Pipeline_load_ab_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_b_0_AWVALID,
        m_axi_gmem_b_0_AWREADY,
        m_axi_gmem_b_0_AWADDR,
        m_axi_gmem_b_0_AWID,
        m_axi_gmem_b_0_AWLEN,
        m_axi_gmem_b_0_AWSIZE,
        m_axi_gmem_b_0_AWBURST,
        m_axi_gmem_b_0_AWLOCK,
        m_axi_gmem_b_0_AWCACHE,
        m_axi_gmem_b_0_AWPROT,
        m_axi_gmem_b_0_AWQOS,
        m_axi_gmem_b_0_AWREGION,
        m_axi_gmem_b_0_AWUSER,
        m_axi_gmem_b_0_WVALID,
        m_axi_gmem_b_0_WREADY,
        m_axi_gmem_b_0_WDATA,
        m_axi_gmem_b_0_WSTRB,
        m_axi_gmem_b_0_WLAST,
        m_axi_gmem_b_0_WID,
        m_axi_gmem_b_0_WUSER,
        m_axi_gmem_b_0_ARVALID,
        m_axi_gmem_b_0_ARREADY,
        m_axi_gmem_b_0_ARADDR,
        m_axi_gmem_b_0_ARID,
        m_axi_gmem_b_0_ARLEN,
        m_axi_gmem_b_0_ARSIZE,
        m_axi_gmem_b_0_ARBURST,
        m_axi_gmem_b_0_ARLOCK,
        m_axi_gmem_b_0_ARCACHE,
        m_axi_gmem_b_0_ARPROT,
        m_axi_gmem_b_0_ARQOS,
        m_axi_gmem_b_0_ARREGION,
        m_axi_gmem_b_0_ARUSER,
        m_axi_gmem_b_0_RVALID,
        m_axi_gmem_b_0_RREADY,
        m_axi_gmem_b_0_RDATA,
        m_axi_gmem_b_0_RLAST,
        m_axi_gmem_b_0_RID,
        m_axi_gmem_b_0_RFIFONUM,
        m_axi_gmem_b_0_RUSER,
        m_axi_gmem_b_0_RRESP,
        m_axi_gmem_b_0_BVALID,
        m_axi_gmem_b_0_BREADY,
        m_axi_gmem_b_0_BRESP,
        m_axi_gmem_b_0_BID,
        m_axi_gmem_b_0_BUSER,
        gmem_a_load,
        p_cast_cast,
        A_row_address0,
        A_row_ce0,
        A_row_we0,
        A_row_d0,
        tmp_4,
        B_col_address0,
        B_col_ce0,
        B_col_we0,
        B_col_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_b_0_AWVALID;
input   m_axi_gmem_b_0_AWREADY;
output  [63:0] m_axi_gmem_b_0_AWADDR;
output  [0:0] m_axi_gmem_b_0_AWID;
output  [31:0] m_axi_gmem_b_0_AWLEN;
output  [2:0] m_axi_gmem_b_0_AWSIZE;
output  [1:0] m_axi_gmem_b_0_AWBURST;
output  [1:0] m_axi_gmem_b_0_AWLOCK;
output  [3:0] m_axi_gmem_b_0_AWCACHE;
output  [2:0] m_axi_gmem_b_0_AWPROT;
output  [3:0] m_axi_gmem_b_0_AWQOS;
output  [3:0] m_axi_gmem_b_0_AWREGION;
output  [0:0] m_axi_gmem_b_0_AWUSER;
output   m_axi_gmem_b_0_WVALID;
input   m_axi_gmem_b_0_WREADY;
output  [511:0] m_axi_gmem_b_0_WDATA;
output  [63:0] m_axi_gmem_b_0_WSTRB;
output   m_axi_gmem_b_0_WLAST;
output  [0:0] m_axi_gmem_b_0_WID;
output  [0:0] m_axi_gmem_b_0_WUSER;
output   m_axi_gmem_b_0_ARVALID;
input   m_axi_gmem_b_0_ARREADY;
output  [63:0] m_axi_gmem_b_0_ARADDR;
output  [0:0] m_axi_gmem_b_0_ARID;
output  [31:0] m_axi_gmem_b_0_ARLEN;
output  [2:0] m_axi_gmem_b_0_ARSIZE;
output  [1:0] m_axi_gmem_b_0_ARBURST;
output  [1:0] m_axi_gmem_b_0_ARLOCK;
output  [3:0] m_axi_gmem_b_0_ARCACHE;
output  [2:0] m_axi_gmem_b_0_ARPROT;
output  [3:0] m_axi_gmem_b_0_ARQOS;
output  [3:0] m_axi_gmem_b_0_ARREGION;
output  [0:0] m_axi_gmem_b_0_ARUSER;
input   m_axi_gmem_b_0_RVALID;
output   m_axi_gmem_b_0_RREADY;
input  [511:0] m_axi_gmem_b_0_RDATA;
input   m_axi_gmem_b_0_RLAST;
input  [0:0] m_axi_gmem_b_0_RID;
input  [8:0] m_axi_gmem_b_0_RFIFONUM;
input  [0:0] m_axi_gmem_b_0_RUSER;
input  [1:0] m_axi_gmem_b_0_RRESP;
input   m_axi_gmem_b_0_BVALID;
output   m_axi_gmem_b_0_BREADY;
input  [1:0] m_axi_gmem_b_0_BRESP;
input  [0:0] m_axi_gmem_b_0_BID;
input  [0:0] m_axi_gmem_b_0_BUSER;
input  [511:0] gmem_a_load;
input  [57:0] p_cast_cast;
output  [3:0] A_row_address0;
output   A_row_ce0;
output   A_row_we0;
output  [31:0] A_row_d0;
input  [8:0] tmp_4;
output  [3:0] B_col_address0;
output   B_col_ce0;
output   B_col_we0;
output  [31:0] B_col_d0;

reg ap_idle;
reg m_axi_gmem_b_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln23_fu_140_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_b_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln23_fu_155_p1;
reg   [63:0] zext_ln23_reg_230;
reg   [63:0] zext_ln23_reg_230_pp0_iter2_reg;
reg   [511:0] gmem_b_addr_read_reg_235;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_grp0;
reg   [511:0] shiftreg_fu_66;
wire   [511:0] zext_ln25_fu_175_p1;
wire    ap_loop_init;
reg   [4:0] k_fu_70;
wire   [4:0] add_ln23_fu_146_p2;
reg    A_row_we0_local;
wire   [31:0] trunc_ln25_fu_160_p1;
reg    A_row_ce0_local;
reg    B_col_we0_local;
wire   [31:0] tmp_fu_195_p3;
reg    B_col_ce0_local;
wire   [479:0] lshr_ln_fu_165_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [31:0] tmp_fu_195_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 shiftreg_fu_66 = 512'd0;
#0 k_fu_70 = 5'd0;
#0 ap_done_reg = 1'b0;
end

matmul_row_col_partselect_32ns_512ns_9ns_32_1_1 #(
    .DATAWIDTH( 512 ),
    .ADDRWIDTH( 9 ),
    .DATA1WIDTH( 32 ))
partselect_32ns_512ns_9ns_32_1_1_U1(
    .din(gmem_b_addr_read_reg_235),
    .sel(tmp_4),
    .dout(tmp_fu_195_p3)
);

matmul_row_col_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_70 <= 5'd0;
        end else if (((icmp_ln23_fu_140_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            k_fu_70 <= add_ln23_fu_146_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            shiftreg_fu_66 <= gmem_a_load;
        end else if (((icmp_ln23_fu_140_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            shiftreg_fu_66 <= zext_ln25_fu_175_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        zext_ln23_reg_230[4 : 0] <= zext_ln23_fu_155_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        gmem_b_addr_read_reg_235 <= m_axi_gmem_b_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        zext_ln23_reg_230_pp0_iter2_reg[4 : 0] <= zext_ln23_reg_230[4 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_row_ce0_local = 1'b1;
    end else begin
        A_row_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln23_fu_140_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_row_we0_local = 1'b1;
    end else begin
        A_row_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        B_col_ce0_local = 1'b1;
    end else begin
        B_col_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        B_col_we0_local = 1'b1;
    end else begin
        B_col_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln23_fu_140_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gmem_b_blk_n_R = m_axi_gmem_b_0_RVALID;
    end else begin
        gmem_b_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axi_gmem_b_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_b_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_row_address0 = zext_ln23_fu_155_p1;

assign A_row_ce0 = A_row_ce0_local;

assign A_row_d0 = trunc_ln25_fu_160_p1;

assign A_row_we0 = A_row_we0_local;

assign B_col_address0 = zext_ln23_reg_230_pp0_iter2_reg;

assign B_col_ce0 = B_col_ce0_local;

assign B_col_d0 = tmp_fu_195_p3;

assign B_col_we0 = B_col_we0_local;

assign add_ln23_fu_146_p2 = (k_fu_70 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem_b_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem_b_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem_b_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln23_fu_140_p2 = ((k_fu_70 == 5'd16) ? 1'b1 : 1'b0);

assign lshr_ln_fu_165_p4 = {{shiftreg_fu_66[511:32]}};

assign m_axi_gmem_b_0_ARADDR = 64'd0;

assign m_axi_gmem_b_0_ARBURST = 2'd0;

assign m_axi_gmem_b_0_ARCACHE = 4'd0;

assign m_axi_gmem_b_0_ARID = 1'd0;

assign m_axi_gmem_b_0_ARLEN = 32'd0;

assign m_axi_gmem_b_0_ARLOCK = 2'd0;

assign m_axi_gmem_b_0_ARPROT = 3'd0;

assign m_axi_gmem_b_0_ARQOS = 4'd0;

assign m_axi_gmem_b_0_ARREGION = 4'd0;

assign m_axi_gmem_b_0_ARSIZE = 3'd0;

assign m_axi_gmem_b_0_ARUSER = 1'd0;

assign m_axi_gmem_b_0_ARVALID = 1'b0;

assign m_axi_gmem_b_0_AWADDR = 64'd0;

assign m_axi_gmem_b_0_AWBURST = 2'd0;

assign m_axi_gmem_b_0_AWCACHE = 4'd0;

assign m_axi_gmem_b_0_AWID = 1'd0;

assign m_axi_gmem_b_0_AWLEN = 32'd0;

assign m_axi_gmem_b_0_AWLOCK = 2'd0;

assign m_axi_gmem_b_0_AWPROT = 3'd0;

assign m_axi_gmem_b_0_AWQOS = 4'd0;

assign m_axi_gmem_b_0_AWREGION = 4'd0;

assign m_axi_gmem_b_0_AWSIZE = 3'd0;

assign m_axi_gmem_b_0_AWUSER = 1'd0;

assign m_axi_gmem_b_0_AWVALID = 1'b0;

assign m_axi_gmem_b_0_BREADY = 1'b0;

assign m_axi_gmem_b_0_WDATA = 512'd0;

assign m_axi_gmem_b_0_WID = 1'd0;

assign m_axi_gmem_b_0_WLAST = 1'b0;

assign m_axi_gmem_b_0_WSTRB = 64'd0;

assign m_axi_gmem_b_0_WUSER = 1'd0;

assign m_axi_gmem_b_0_WVALID = 1'b0;

assign trunc_ln25_fu_160_p1 = shiftreg_fu_66[31:0];

assign zext_ln23_fu_155_p1 = k_fu_70;

assign zext_ln25_fu_175_p1 = lshr_ln_fu_165_p4;

always @ (posedge ap_clk) begin
    zext_ln23_reg_230[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln23_reg_230_pp0_iter2_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //matmul_row_col_matmul_row_col_Pipeline_load_ab_loop
