

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "30", "78", "80", "81", "82", "83"],
		"CDFG" : "matmul_full_contiguous",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "801", "EstimateLatencyMax" : "801",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_a", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_a_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "27", "SubInstance" : "grp_matmul_full_contiguous_Pipeline_load_ab_full_loop_fu_438", "Port" : "gmem_a", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "gmem_b", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_b_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "27", "SubInstance" : "grp_matmul_full_contiguous_Pipeline_load_ab_full_loop_fu_438", "Port" : "gmem_b", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "gmem_c", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_c_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_c_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "78", "SubInstance" : "grp_matmul_full_contiguous_Pipeline_store_c_full_loop_fu_519", "Port" : "gmem_c", "Inst_start_state" : "16", "Inst_end_state" : "17"}]},
			{"Name" : "a", "Type" : "None", "Direction" : "I"},
			{"Name" : "b", "Type" : "None", "Direction" : "I"},
			{"Name" : "c", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_local_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_local_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_local_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_local_3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_local_4_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_local_5_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_local_6_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_local_7_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_1_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_2_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_3_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_4_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_5_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_6_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_7_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_8_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_9_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_10_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_11_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_12_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_13_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_14_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_15_U", "Parent" : "0"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B_local_16_U", "Parent" : "0"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_local_U", "Parent" : "0"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_load_ab_full_loop_fu_438", "Parent" : "0", "Child" : ["28", "29"],
		"CDFG" : "matmul_full_contiguous_Pipeline_load_ab_full_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "259", "EstimateLatencyMax" : "259",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_b", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_b_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem_a", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_a_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "B_local", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_9", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_13", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_15", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B_local_16", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "A_local", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "A_local_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "A_local_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "A_local_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "A_local_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "A_local_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "A_local_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "A_local_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "sext_ln20", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln20_1", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "load_ab_full_loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_load_ab_full_loop_fu_438.mul_8ns_10ns_17_1_1_U1", "Parent" : "27"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_load_ab_full_loop_fu_438.flow_control_loop_pipe_sequential_init_U", "Parent" : "27"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473", "Parent" : "0", "Child" : ["31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77"],
		"CDFG" : "matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "262", "EstimateLatencyMax" : "262",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A_local", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_local_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_local_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_local_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_local_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_local_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_local_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_local_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_1_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_2_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_3_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_4_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_5_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_6_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_7_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_8_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_9_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_10_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_11_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_12_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_13_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_14_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local_15_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "B_local", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_9", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_11", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_13", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_16", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "B_local_15", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "C_local", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "compute_row_loop_compute_col_loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U32", "Parent" : "30"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U33", "Parent" : "30"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U34", "Parent" : "30"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U35", "Parent" : "30"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U36", "Parent" : "30"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U37", "Parent" : "30"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U38", "Parent" : "30"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U39", "Parent" : "30"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U40", "Parent" : "30"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U41", "Parent" : "30"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U42", "Parent" : "30"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U43", "Parent" : "30"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U44", "Parent" : "30"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U45", "Parent" : "30"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U46", "Parent" : "30"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_32s_32s_32_1_1_U47", "Parent" : "30"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U48", "Parent" : "30"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_6ns_8ns_13_1_1_U49", "Parent" : "30"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_7ns_9ns_15_1_1_U50", "Parent" : "30"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_8ns_10ns_17_1_1_U51", "Parent" : "30"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_8ns_10ns_17_1_1_U52", "Parent" : "30"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_6ns_8ns_13_1_1_U53", "Parent" : "30"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_7ns_9ns_15_1_1_U54", "Parent" : "30"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_7ns_9ns_15_1_1_U55", "Parent" : "30"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_7ns_9ns_15_1_1_U56", "Parent" : "30"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_8ns_10ns_17_1_1_U57", "Parent" : "30"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_8ns_10ns_17_1_1_U58", "Parent" : "30"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_8ns_10ns_17_1_1_U59", "Parent" : "30"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_8ns_10ns_17_1_1_U60", "Parent" : "30"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_8ns_10ns_17_1_1_U61", "Parent" : "30"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.mul_8ns_10ns_17_1_1_U62", "Parent" : "30"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U63", "Parent" : "30"},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U64", "Parent" : "30"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U65", "Parent" : "30"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U66", "Parent" : "30"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U67", "Parent" : "30"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U68", "Parent" : "30"},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U69", "Parent" : "30"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U70", "Parent" : "30"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U71", "Parent" : "30"},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U72", "Parent" : "30"},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U73", "Parent" : "30"},
	{"ID" : "73", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U74", "Parent" : "30"},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U75", "Parent" : "30"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U76", "Parent" : "30"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.sparsemux_33_4_32_1_1_U77", "Parent" : "30"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_compute_row_loop_compute_col_loop_fu_473.flow_control_loop_pipe_sequential_init_U", "Parent" : "30"},
	{"ID" : "78", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_store_c_full_loop_fu_519", "Parent" : "0", "Child" : ["79"],
		"CDFG" : "matmul_full_contiguous_Pipeline_store_c_full_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "259", "EstimateLatencyMax" : "259",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_c", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_c_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln43", "Type" : "None", "Direction" : "I"},
			{"Name" : "C_local", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "store_c_full_loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "79", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_matmul_full_contiguous_Pipeline_store_c_full_loop_fu_519.flow_control_loop_pipe_sequential_init_U", "Parent" : "78"},
	{"ID" : "80", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "81", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_a_m_axi_U", "Parent" : "0"},
	{"ID" : "82", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_b_m_axi_U", "Parent" : "0"},
	{"ID" : "83", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_c_m_axi_U", "Parent" : "0"}]}
