// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="read_write_read_write,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.078000,HLS_SYN_LAT=4239,HLS_SYN_TPT=4096,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=9675,HLS_SYN_LUT=9062,HLS_VERSION=2025_1}" *)

module read_write (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_mem_0_AWVALID,
        m_axi_mem_0_AWREADY,
        m_axi_mem_0_AWADDR,
        m_axi_mem_0_AWID,
        m_axi_mem_0_AWLEN,
        m_axi_mem_0_AWSIZE,
        m_axi_mem_0_AWBURST,
        m_axi_mem_0_AWLOCK,
        m_axi_mem_0_AWCACHE,
        m_axi_mem_0_AWPROT,
        m_axi_mem_0_AWQOS,
        m_axi_mem_0_AWREGION,
        m_axi_mem_0_AWUSER,
        m_axi_mem_0_WVALID,
        m_axi_mem_0_WREADY,
        m_axi_mem_0_WDATA,
        m_axi_mem_0_WSTRB,
        m_axi_mem_0_WLAST,
        m_axi_mem_0_WID,
        m_axi_mem_0_WUSER,
        m_axi_mem_0_ARVALID,
        m_axi_mem_0_ARREADY,
        m_axi_mem_0_ARADDR,
        m_axi_mem_0_ARID,
        m_axi_mem_0_ARLEN,
        m_axi_mem_0_ARSIZE,
        m_axi_mem_0_ARBURST,
        m_axi_mem_0_ARLOCK,
        m_axi_mem_0_ARCACHE,
        m_axi_mem_0_ARPROT,
        m_axi_mem_0_ARQOS,
        m_axi_mem_0_ARREGION,
        m_axi_mem_0_ARUSER,
        m_axi_mem_0_RVALID,
        m_axi_mem_0_RREADY,
        m_axi_mem_0_RDATA,
        m_axi_mem_0_RLAST,
        m_axi_mem_0_RID,
        m_axi_mem_0_RUSER,
        m_axi_mem_0_RRESP,
        m_axi_mem_0_BVALID,
        m_axi_mem_0_BREADY,
        m_axi_mem_0_BRESP,
        m_axi_mem_0_BID,
        m_axi_mem_0_BUSER,
        m_axi_mem_1_AWVALID,
        m_axi_mem_1_AWREADY,
        m_axi_mem_1_AWADDR,
        m_axi_mem_1_AWID,
        m_axi_mem_1_AWLEN,
        m_axi_mem_1_AWSIZE,
        m_axi_mem_1_AWBURST,
        m_axi_mem_1_AWLOCK,
        m_axi_mem_1_AWCACHE,
        m_axi_mem_1_AWPROT,
        m_axi_mem_1_AWQOS,
        m_axi_mem_1_AWREGION,
        m_axi_mem_1_AWUSER,
        m_axi_mem_1_WVALID,
        m_axi_mem_1_WREADY,
        m_axi_mem_1_WDATA,
        m_axi_mem_1_WSTRB,
        m_axi_mem_1_WLAST,
        m_axi_mem_1_WID,
        m_axi_mem_1_WUSER,
        m_axi_mem_1_ARVALID,
        m_axi_mem_1_ARREADY,
        m_axi_mem_1_ARADDR,
        m_axi_mem_1_ARID,
        m_axi_mem_1_ARLEN,
        m_axi_mem_1_ARSIZE,
        m_axi_mem_1_ARBURST,
        m_axi_mem_1_ARLOCK,
        m_axi_mem_1_ARCACHE,
        m_axi_mem_1_ARPROT,
        m_axi_mem_1_ARQOS,
        m_axi_mem_1_ARREGION,
        m_axi_mem_1_ARUSER,
        m_axi_mem_1_RVALID,
        m_axi_mem_1_RREADY,
        m_axi_mem_1_RDATA,
        m_axi_mem_1_RLAST,
        m_axi_mem_1_RID,
        m_axi_mem_1_RUSER,
        m_axi_mem_1_RRESP,
        m_axi_mem_1_BVALID,
        m_axi_mem_1_BREADY,
        m_axi_mem_1_BRESP,
        m_axi_mem_1_BID,
        m_axi_mem_1_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_MEM_0_ID_WIDTH = 1;
parameter    C_M_AXI_MEM_0_ADDR_WIDTH = 64;
parameter    C_M_AXI_MEM_0_DATA_WIDTH = 512;
parameter    C_M_AXI_MEM_0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_0_WUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_0_RUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_0_BUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_0_USER_VALUE = 0;
parameter    C_M_AXI_MEM_0_PROT_VALUE = 0;
parameter    C_M_AXI_MEM_0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_MEM_1_ID_WIDTH = 1;
parameter    C_M_AXI_MEM_1_ADDR_WIDTH = 64;
parameter    C_M_AXI_MEM_1_DATA_WIDTH = 512;
parameter    C_M_AXI_MEM_1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_1_WUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_1_RUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_1_BUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_1_USER_VALUE = 0;
parameter    C_M_AXI_MEM_1_PROT_VALUE = 0;
parameter    C_M_AXI_MEM_1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MEM_0_WSTRB_WIDTH = (512 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MEM_1_WSTRB_WIDTH = (512 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_mem_0_AWVALID;
input   m_axi_mem_0_AWREADY;
output  [C_M_AXI_MEM_0_ADDR_WIDTH - 1:0] m_axi_mem_0_AWADDR;
output  [C_M_AXI_MEM_0_ID_WIDTH - 1:0] m_axi_mem_0_AWID;
output  [7:0] m_axi_mem_0_AWLEN;
output  [2:0] m_axi_mem_0_AWSIZE;
output  [1:0] m_axi_mem_0_AWBURST;
output  [1:0] m_axi_mem_0_AWLOCK;
output  [3:0] m_axi_mem_0_AWCACHE;
output  [2:0] m_axi_mem_0_AWPROT;
output  [3:0] m_axi_mem_0_AWQOS;
output  [3:0] m_axi_mem_0_AWREGION;
output  [C_M_AXI_MEM_0_AWUSER_WIDTH - 1:0] m_axi_mem_0_AWUSER;
output   m_axi_mem_0_WVALID;
input   m_axi_mem_0_WREADY;
output  [C_M_AXI_MEM_0_DATA_WIDTH - 1:0] m_axi_mem_0_WDATA;
output  [C_M_AXI_MEM_0_WSTRB_WIDTH - 1:0] m_axi_mem_0_WSTRB;
output   m_axi_mem_0_WLAST;
output  [C_M_AXI_MEM_0_ID_WIDTH - 1:0] m_axi_mem_0_WID;
output  [C_M_AXI_MEM_0_WUSER_WIDTH - 1:0] m_axi_mem_0_WUSER;
output   m_axi_mem_0_ARVALID;
input   m_axi_mem_0_ARREADY;
output  [C_M_AXI_MEM_0_ADDR_WIDTH - 1:0] m_axi_mem_0_ARADDR;
output  [C_M_AXI_MEM_0_ID_WIDTH - 1:0] m_axi_mem_0_ARID;
output  [7:0] m_axi_mem_0_ARLEN;
output  [2:0] m_axi_mem_0_ARSIZE;
output  [1:0] m_axi_mem_0_ARBURST;
output  [1:0] m_axi_mem_0_ARLOCK;
output  [3:0] m_axi_mem_0_ARCACHE;
output  [2:0] m_axi_mem_0_ARPROT;
output  [3:0] m_axi_mem_0_ARQOS;
output  [3:0] m_axi_mem_0_ARREGION;
output  [C_M_AXI_MEM_0_ARUSER_WIDTH - 1:0] m_axi_mem_0_ARUSER;
input   m_axi_mem_0_RVALID;
output   m_axi_mem_0_RREADY;
input  [C_M_AXI_MEM_0_DATA_WIDTH - 1:0] m_axi_mem_0_RDATA;
input   m_axi_mem_0_RLAST;
input  [C_M_AXI_MEM_0_ID_WIDTH - 1:0] m_axi_mem_0_RID;
input  [C_M_AXI_MEM_0_RUSER_WIDTH - 1:0] m_axi_mem_0_RUSER;
input  [1:0] m_axi_mem_0_RRESP;
input   m_axi_mem_0_BVALID;
output   m_axi_mem_0_BREADY;
input  [1:0] m_axi_mem_0_BRESP;
input  [C_M_AXI_MEM_0_ID_WIDTH - 1:0] m_axi_mem_0_BID;
input  [C_M_AXI_MEM_0_BUSER_WIDTH - 1:0] m_axi_mem_0_BUSER;
output   m_axi_mem_1_AWVALID;
input   m_axi_mem_1_AWREADY;
output  [C_M_AXI_MEM_1_ADDR_WIDTH - 1:0] m_axi_mem_1_AWADDR;
output  [C_M_AXI_MEM_1_ID_WIDTH - 1:0] m_axi_mem_1_AWID;
output  [7:0] m_axi_mem_1_AWLEN;
output  [2:0] m_axi_mem_1_AWSIZE;
output  [1:0] m_axi_mem_1_AWBURST;
output  [1:0] m_axi_mem_1_AWLOCK;
output  [3:0] m_axi_mem_1_AWCACHE;
output  [2:0] m_axi_mem_1_AWPROT;
output  [3:0] m_axi_mem_1_AWQOS;
output  [3:0] m_axi_mem_1_AWREGION;
output  [C_M_AXI_MEM_1_AWUSER_WIDTH - 1:0] m_axi_mem_1_AWUSER;
output   m_axi_mem_1_WVALID;
input   m_axi_mem_1_WREADY;
output  [C_M_AXI_MEM_1_DATA_WIDTH - 1:0] m_axi_mem_1_WDATA;
output  [C_M_AXI_MEM_1_WSTRB_WIDTH - 1:0] m_axi_mem_1_WSTRB;
output   m_axi_mem_1_WLAST;
output  [C_M_AXI_MEM_1_ID_WIDTH - 1:0] m_axi_mem_1_WID;
output  [C_M_AXI_MEM_1_WUSER_WIDTH - 1:0] m_axi_mem_1_WUSER;
output   m_axi_mem_1_ARVALID;
input   m_axi_mem_1_ARREADY;
output  [C_M_AXI_MEM_1_ADDR_WIDTH - 1:0] m_axi_mem_1_ARADDR;
output  [C_M_AXI_MEM_1_ID_WIDTH - 1:0] m_axi_mem_1_ARID;
output  [7:0] m_axi_mem_1_ARLEN;
output  [2:0] m_axi_mem_1_ARSIZE;
output  [1:0] m_axi_mem_1_ARBURST;
output  [1:0] m_axi_mem_1_ARLOCK;
output  [3:0] m_axi_mem_1_ARCACHE;
output  [2:0] m_axi_mem_1_ARPROT;
output  [3:0] m_axi_mem_1_ARQOS;
output  [3:0] m_axi_mem_1_ARREGION;
output  [C_M_AXI_MEM_1_ARUSER_WIDTH - 1:0] m_axi_mem_1_ARUSER;
input   m_axi_mem_1_RVALID;
output   m_axi_mem_1_RREADY;
input  [C_M_AXI_MEM_1_DATA_WIDTH - 1:0] m_axi_mem_1_RDATA;
input   m_axi_mem_1_RLAST;
input  [C_M_AXI_MEM_1_ID_WIDTH - 1:0] m_axi_mem_1_RID;
input  [C_M_AXI_MEM_1_RUSER_WIDTH - 1:0] m_axi_mem_1_RUSER;
input  [1:0] m_axi_mem_1_RRESP;
input   m_axi_mem_1_BVALID;
output   m_axi_mem_1_BREADY;
input  [1:0] m_axi_mem_1_BRESP;
input  [C_M_AXI_MEM_1_ID_WIDTH - 1:0] m_axi_mem_1_BID;
input  [C_M_AXI_MEM_1_BUSER_WIDTH - 1:0] m_axi_mem_1_BUSER;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [63:0] mem_0_r;
wire   [63:0] mem_1_r;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    mem_0_0_AWREADY;
wire    mem_0_0_WREADY;
wire    mem_0_0_ARREADY;
wire    mem_0_0_RVALID;
wire   [511:0] mem_0_0_RDATA;
wire    mem_0_0_RLAST;
wire   [0:0] mem_0_0_RID;
wire   [4:0] mem_0_0_RFIFONUM;
wire   [0:0] mem_0_0_RUSER;
wire   [1:0] mem_0_0_RRESP;
wire    mem_0_0_BVALID;
wire   [1:0] mem_0_0_BRESP;
wire   [0:0] mem_0_0_BID;
wire   [0:0] mem_0_0_BUSER;
wire    mem_1_0_AWREADY;
wire    mem_1_0_WREADY;
wire    mem_1_0_ARREADY;
wire    mem_1_0_RVALID;
wire   [511:0] mem_1_0_RDATA;
wire    mem_1_0_RLAST;
wire   [0:0] mem_1_0_RID;
wire   [4:0] mem_1_0_RFIFONUM;
wire   [0:0] mem_1_0_RUSER;
wire   [1:0] mem_1_0_RRESP;
wire    mem_1_0_BVALID;
wire   [1:0] mem_1_0_BRESP;
wire   [0:0] mem_1_0_BID;
wire   [0:0] mem_1_0_BUSER;
wire    read_U0_ap_start;
wire    read_U0_ap_done;
wire    read_U0_ap_continue;
wire    read_U0_ap_idle;
wire    read_U0_ap_ready;
wire   [63:0] read_U0_mem_0_r_c_din;
wire    read_U0_mem_0_r_c_write;
wire    read_U0_m_axi_mem_0_0_AWVALID;
wire   [63:0] read_U0_m_axi_mem_0_0_AWADDR;
wire   [0:0] read_U0_m_axi_mem_0_0_AWID;
wire   [31:0] read_U0_m_axi_mem_0_0_AWLEN;
wire   [2:0] read_U0_m_axi_mem_0_0_AWSIZE;
wire   [1:0] read_U0_m_axi_mem_0_0_AWBURST;
wire   [1:0] read_U0_m_axi_mem_0_0_AWLOCK;
wire   [3:0] read_U0_m_axi_mem_0_0_AWCACHE;
wire   [2:0] read_U0_m_axi_mem_0_0_AWPROT;
wire   [3:0] read_U0_m_axi_mem_0_0_AWQOS;
wire   [3:0] read_U0_m_axi_mem_0_0_AWREGION;
wire   [0:0] read_U0_m_axi_mem_0_0_AWUSER;
wire    read_U0_m_axi_mem_0_0_WVALID;
wire   [511:0] read_U0_m_axi_mem_0_0_WDATA;
wire   [63:0] read_U0_m_axi_mem_0_0_WSTRB;
wire    read_U0_m_axi_mem_0_0_WLAST;
wire   [0:0] read_U0_m_axi_mem_0_0_WID;
wire   [0:0] read_U0_m_axi_mem_0_0_WUSER;
wire    read_U0_m_axi_mem_0_0_ARVALID;
wire   [63:0] read_U0_m_axi_mem_0_0_ARADDR;
wire   [0:0] read_U0_m_axi_mem_0_0_ARID;
wire   [31:0] read_U0_m_axi_mem_0_0_ARLEN;
wire   [2:0] read_U0_m_axi_mem_0_0_ARSIZE;
wire   [1:0] read_U0_m_axi_mem_0_0_ARBURST;
wire   [1:0] read_U0_m_axi_mem_0_0_ARLOCK;
wire   [3:0] read_U0_m_axi_mem_0_0_ARCACHE;
wire   [2:0] read_U0_m_axi_mem_0_0_ARPROT;
wire   [3:0] read_U0_m_axi_mem_0_0_ARQOS;
wire   [3:0] read_U0_m_axi_mem_0_0_ARREGION;
wire   [0:0] read_U0_m_axi_mem_0_0_ARUSER;
wire    read_U0_m_axi_mem_0_0_RREADY;
wire    read_U0_m_axi_mem_0_0_BREADY;
wire   [31:0] read_U0_stream_0_din;
wire    read_U0_stream_0_write;
wire    read_U0_start_out;
wire    read_U0_start_write;
wire    read_1_U0_ap_start;
wire    read_1_U0_ap_done;
wire    read_1_U0_ap_continue;
wire    read_1_U0_ap_idle;
wire    read_1_U0_ap_ready;
wire   [63:0] read_1_U0_mem_1_r_c_din;
wire    read_1_U0_mem_1_r_c_write;
wire    read_1_U0_m_axi_mem_1_0_AWVALID;
wire   [63:0] read_1_U0_m_axi_mem_1_0_AWADDR;
wire   [0:0] read_1_U0_m_axi_mem_1_0_AWID;
wire   [31:0] read_1_U0_m_axi_mem_1_0_AWLEN;
wire   [2:0] read_1_U0_m_axi_mem_1_0_AWSIZE;
wire   [1:0] read_1_U0_m_axi_mem_1_0_AWBURST;
wire   [1:0] read_1_U0_m_axi_mem_1_0_AWLOCK;
wire   [3:0] read_1_U0_m_axi_mem_1_0_AWCACHE;
wire   [2:0] read_1_U0_m_axi_mem_1_0_AWPROT;
wire   [3:0] read_1_U0_m_axi_mem_1_0_AWQOS;
wire   [3:0] read_1_U0_m_axi_mem_1_0_AWREGION;
wire   [0:0] read_1_U0_m_axi_mem_1_0_AWUSER;
wire    read_1_U0_m_axi_mem_1_0_WVALID;
wire   [511:0] read_1_U0_m_axi_mem_1_0_WDATA;
wire   [63:0] read_1_U0_m_axi_mem_1_0_WSTRB;
wire    read_1_U0_m_axi_mem_1_0_WLAST;
wire   [0:0] read_1_U0_m_axi_mem_1_0_WID;
wire   [0:0] read_1_U0_m_axi_mem_1_0_WUSER;
wire    read_1_U0_m_axi_mem_1_0_ARVALID;
wire   [63:0] read_1_U0_m_axi_mem_1_0_ARADDR;
wire   [0:0] read_1_U0_m_axi_mem_1_0_ARID;
wire   [31:0] read_1_U0_m_axi_mem_1_0_ARLEN;
wire   [2:0] read_1_U0_m_axi_mem_1_0_ARSIZE;
wire   [1:0] read_1_U0_m_axi_mem_1_0_ARBURST;
wire   [1:0] read_1_U0_m_axi_mem_1_0_ARLOCK;
wire   [3:0] read_1_U0_m_axi_mem_1_0_ARCACHE;
wire   [2:0] read_1_U0_m_axi_mem_1_0_ARPROT;
wire   [3:0] read_1_U0_m_axi_mem_1_0_ARQOS;
wire   [3:0] read_1_U0_m_axi_mem_1_0_ARREGION;
wire   [0:0] read_1_U0_m_axi_mem_1_0_ARUSER;
wire    read_1_U0_m_axi_mem_1_0_RREADY;
wire    read_1_U0_m_axi_mem_1_0_BREADY;
wire   [31:0] read_1_U0_stream_1_din;
wire    read_1_U0_stream_1_write;
wire    read_1_U0_start_out;
wire    read_1_U0_start_write;
wire    write_U0_ap_start;
wire    write_U0_ap_done;
wire    write_U0_ap_continue;
wire    write_U0_ap_idle;
wire    write_U0_ap_ready;
wire    write_U0_m_axi_mem_0_0_AWVALID;
wire   [63:0] write_U0_m_axi_mem_0_0_AWADDR;
wire   [0:0] write_U0_m_axi_mem_0_0_AWID;
wire   [31:0] write_U0_m_axi_mem_0_0_AWLEN;
wire   [2:0] write_U0_m_axi_mem_0_0_AWSIZE;
wire   [1:0] write_U0_m_axi_mem_0_0_AWBURST;
wire   [1:0] write_U0_m_axi_mem_0_0_AWLOCK;
wire   [3:0] write_U0_m_axi_mem_0_0_AWCACHE;
wire   [2:0] write_U0_m_axi_mem_0_0_AWPROT;
wire   [3:0] write_U0_m_axi_mem_0_0_AWQOS;
wire   [3:0] write_U0_m_axi_mem_0_0_AWREGION;
wire   [0:0] write_U0_m_axi_mem_0_0_AWUSER;
wire    write_U0_m_axi_mem_0_0_WVALID;
wire   [511:0] write_U0_m_axi_mem_0_0_WDATA;
wire   [63:0] write_U0_m_axi_mem_0_0_WSTRB;
wire    write_U0_m_axi_mem_0_0_WLAST;
wire   [0:0] write_U0_m_axi_mem_0_0_WID;
wire   [0:0] write_U0_m_axi_mem_0_0_WUSER;
wire    write_U0_m_axi_mem_0_0_ARVALID;
wire   [63:0] write_U0_m_axi_mem_0_0_ARADDR;
wire   [0:0] write_U0_m_axi_mem_0_0_ARID;
wire   [31:0] write_U0_m_axi_mem_0_0_ARLEN;
wire   [2:0] write_U0_m_axi_mem_0_0_ARSIZE;
wire   [1:0] write_U0_m_axi_mem_0_0_ARBURST;
wire   [1:0] write_U0_m_axi_mem_0_0_ARLOCK;
wire   [3:0] write_U0_m_axi_mem_0_0_ARCACHE;
wire   [2:0] write_U0_m_axi_mem_0_0_ARPROT;
wire   [3:0] write_U0_m_axi_mem_0_0_ARQOS;
wire   [3:0] write_U0_m_axi_mem_0_0_ARREGION;
wire   [0:0] write_U0_m_axi_mem_0_0_ARUSER;
wire    write_U0_m_axi_mem_0_0_RREADY;
wire    write_U0_m_axi_mem_0_0_BREADY;
wire    write_U0_mem_read;
wire    write_U0_stream_0_read;
wire    ap_sync_continue;
wire    write_2_U0_ap_start;
wire    write_2_U0_ap_done;
wire    write_2_U0_ap_continue;
wire    write_2_U0_ap_idle;
wire    write_2_U0_ap_ready;
wire    write_2_U0_m_axi_mem_1_0_AWVALID;
wire   [63:0] write_2_U0_m_axi_mem_1_0_AWADDR;
wire   [0:0] write_2_U0_m_axi_mem_1_0_AWID;
wire   [31:0] write_2_U0_m_axi_mem_1_0_AWLEN;
wire   [2:0] write_2_U0_m_axi_mem_1_0_AWSIZE;
wire   [1:0] write_2_U0_m_axi_mem_1_0_AWBURST;
wire   [1:0] write_2_U0_m_axi_mem_1_0_AWLOCK;
wire   [3:0] write_2_U0_m_axi_mem_1_0_AWCACHE;
wire   [2:0] write_2_U0_m_axi_mem_1_0_AWPROT;
wire   [3:0] write_2_U0_m_axi_mem_1_0_AWQOS;
wire   [3:0] write_2_U0_m_axi_mem_1_0_AWREGION;
wire   [0:0] write_2_U0_m_axi_mem_1_0_AWUSER;
wire    write_2_U0_m_axi_mem_1_0_WVALID;
wire   [511:0] write_2_U0_m_axi_mem_1_0_WDATA;
wire   [63:0] write_2_U0_m_axi_mem_1_0_WSTRB;
wire    write_2_U0_m_axi_mem_1_0_WLAST;
wire   [0:0] write_2_U0_m_axi_mem_1_0_WID;
wire   [0:0] write_2_U0_m_axi_mem_1_0_WUSER;
wire    write_2_U0_m_axi_mem_1_0_ARVALID;
wire   [63:0] write_2_U0_m_axi_mem_1_0_ARADDR;
wire   [0:0] write_2_U0_m_axi_mem_1_0_ARID;
wire   [31:0] write_2_U0_m_axi_mem_1_0_ARLEN;
wire   [2:0] write_2_U0_m_axi_mem_1_0_ARSIZE;
wire   [1:0] write_2_U0_m_axi_mem_1_0_ARBURST;
wire   [1:0] write_2_U0_m_axi_mem_1_0_ARLOCK;
wire   [3:0] write_2_U0_m_axi_mem_1_0_ARCACHE;
wire   [2:0] write_2_U0_m_axi_mem_1_0_ARPROT;
wire   [3:0] write_2_U0_m_axi_mem_1_0_ARQOS;
wire   [3:0] write_2_U0_m_axi_mem_1_0_ARREGION;
wire   [0:0] write_2_U0_m_axi_mem_1_0_ARUSER;
wire    write_2_U0_m_axi_mem_1_0_RREADY;
wire    write_2_U0_m_axi_mem_1_0_BREADY;
wire    write_2_U0_mem_read;
wire    write_2_U0_stream_1_read;
wire    stream_full_n;
wire   [31:0] stream_dout;
wire    stream_empty_n;
wire   [2:0] stream_num_data_valid;
wire   [2:0] stream_fifo_cap;
wire    mem_0_r_c_full_n;
wire   [63:0] mem_0_r_c_dout;
wire    mem_0_r_c_empty_n;
wire   [2:0] mem_0_r_c_num_data_valid;
wire   [2:0] mem_0_r_c_fifo_cap;
wire    stream_1_full_n;
wire   [31:0] stream_1_dout;
wire    stream_1_empty_n;
wire   [2:0] stream_1_num_data_valid;
wire   [2:0] stream_1_fifo_cap;
wire    mem_1_r_c_full_n;
wire   [63:0] mem_1_r_c_dout;
wire    mem_1_r_c_empty_n;
wire   [2:0] mem_1_r_c_num_data_valid;
wire   [2:0] mem_1_r_c_fifo_cap;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_read_U0_ap_ready;
wire    ap_sync_read_U0_ap_ready;
reg    ap_sync_reg_read_1_U0_ap_ready;
wire    ap_sync_read_1_U0_ap_ready;
wire   [0:0] start_for_write_U0_din;
wire    start_for_write_U0_full_n;
wire   [0:0] start_for_write_U0_dout;
wire    start_for_write_U0_empty_n;
wire   [0:0] start_for_write_2_U0_din;
wire    start_for_write_2_U0_full_n;
wire   [0:0] start_for_write_2_U0_dout;
wire    start_for_write_2_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_sync_reg_read_U0_ap_ready = 1'b0;
#0 ap_sync_reg_read_1_U0_ap_ready = 1'b0;
end

read_write_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mem_0_r(mem_0_r),
    .mem_1_r(mem_1_r),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

read_write_mem_0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MEM_0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MEM_0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MEM_0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MEM_0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MEM_0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MEM_0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MEM_0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MEM_0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MEM_0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MEM_0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MEM_0_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 1 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 5 ),
    .CH0_USER_DW( 512 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 1 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
mem_0_m_axi_U(
    .AWVALID(m_axi_mem_0_AWVALID),
    .AWREADY(m_axi_mem_0_AWREADY),
    .AWADDR(m_axi_mem_0_AWADDR),
    .AWID(m_axi_mem_0_AWID),
    .AWLEN(m_axi_mem_0_AWLEN),
    .AWSIZE(m_axi_mem_0_AWSIZE),
    .AWBURST(m_axi_mem_0_AWBURST),
    .AWLOCK(m_axi_mem_0_AWLOCK),
    .AWCACHE(m_axi_mem_0_AWCACHE),
    .AWPROT(m_axi_mem_0_AWPROT),
    .AWQOS(m_axi_mem_0_AWQOS),
    .AWREGION(m_axi_mem_0_AWREGION),
    .AWUSER(m_axi_mem_0_AWUSER),
    .WVALID(m_axi_mem_0_WVALID),
    .WREADY(m_axi_mem_0_WREADY),
    .WDATA(m_axi_mem_0_WDATA),
    .WSTRB(m_axi_mem_0_WSTRB),
    .WLAST(m_axi_mem_0_WLAST),
    .WID(m_axi_mem_0_WID),
    .WUSER(m_axi_mem_0_WUSER),
    .ARVALID(m_axi_mem_0_ARVALID),
    .ARREADY(m_axi_mem_0_ARREADY),
    .ARADDR(m_axi_mem_0_ARADDR),
    .ARID(m_axi_mem_0_ARID),
    .ARLEN(m_axi_mem_0_ARLEN),
    .ARSIZE(m_axi_mem_0_ARSIZE),
    .ARBURST(m_axi_mem_0_ARBURST),
    .ARLOCK(m_axi_mem_0_ARLOCK),
    .ARCACHE(m_axi_mem_0_ARCACHE),
    .ARPROT(m_axi_mem_0_ARPROT),
    .ARQOS(m_axi_mem_0_ARQOS),
    .ARREGION(m_axi_mem_0_ARREGION),
    .ARUSER(m_axi_mem_0_ARUSER),
    .RVALID(m_axi_mem_0_RVALID),
    .RREADY(m_axi_mem_0_RREADY),
    .RDATA(m_axi_mem_0_RDATA),
    .RLAST(m_axi_mem_0_RLAST),
    .RID(m_axi_mem_0_RID),
    .RUSER(m_axi_mem_0_RUSER),
    .RRESP(m_axi_mem_0_RRESP),
    .BVALID(m_axi_mem_0_BVALID),
    .BREADY(m_axi_mem_0_BREADY),
    .BRESP(m_axi_mem_0_BRESP),
    .BID(m_axi_mem_0_BID),
    .BUSER(m_axi_mem_0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(read_U0_m_axi_mem_0_0_ARVALID),
    .I_CH0_ARREADY(mem_0_0_ARREADY),
    .I_CH0_ARADDR(read_U0_m_axi_mem_0_0_ARADDR),
    .I_CH0_ARLEN(read_U0_m_axi_mem_0_0_ARLEN),
    .I_CH0_RVALID(mem_0_0_RVALID),
    .I_CH0_RREADY(read_U0_m_axi_mem_0_0_RREADY),
    .I_CH0_RDATA(mem_0_0_RDATA),
    .I_CH0_RFIFONUM(mem_0_0_RFIFONUM),
    .I_CH0_AWVALID(write_U0_m_axi_mem_0_0_AWVALID),
    .I_CH0_AWREADY(mem_0_0_AWREADY),
    .I_CH0_AWADDR(write_U0_m_axi_mem_0_0_AWADDR),
    .I_CH0_AWLEN(write_U0_m_axi_mem_0_0_AWLEN),
    .I_CH0_WVALID(write_U0_m_axi_mem_0_0_WVALID),
    .I_CH0_WREADY(mem_0_0_WREADY),
    .I_CH0_WDATA(write_U0_m_axi_mem_0_0_WDATA),
    .I_CH0_WSTRB(write_U0_m_axi_mem_0_0_WSTRB),
    .I_CH0_BVALID(mem_0_0_BVALID),
    .I_CH0_BREADY(write_U0_m_axi_mem_0_0_BREADY)
);

read_write_mem_1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MEM_1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MEM_1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MEM_1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MEM_1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MEM_1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MEM_1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MEM_1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MEM_1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MEM_1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MEM_1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MEM_1_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 1 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 5 ),
    .CH0_USER_DW( 512 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 1 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
mem_1_m_axi_U(
    .AWVALID(m_axi_mem_1_AWVALID),
    .AWREADY(m_axi_mem_1_AWREADY),
    .AWADDR(m_axi_mem_1_AWADDR),
    .AWID(m_axi_mem_1_AWID),
    .AWLEN(m_axi_mem_1_AWLEN),
    .AWSIZE(m_axi_mem_1_AWSIZE),
    .AWBURST(m_axi_mem_1_AWBURST),
    .AWLOCK(m_axi_mem_1_AWLOCK),
    .AWCACHE(m_axi_mem_1_AWCACHE),
    .AWPROT(m_axi_mem_1_AWPROT),
    .AWQOS(m_axi_mem_1_AWQOS),
    .AWREGION(m_axi_mem_1_AWREGION),
    .AWUSER(m_axi_mem_1_AWUSER),
    .WVALID(m_axi_mem_1_WVALID),
    .WREADY(m_axi_mem_1_WREADY),
    .WDATA(m_axi_mem_1_WDATA),
    .WSTRB(m_axi_mem_1_WSTRB),
    .WLAST(m_axi_mem_1_WLAST),
    .WID(m_axi_mem_1_WID),
    .WUSER(m_axi_mem_1_WUSER),
    .ARVALID(m_axi_mem_1_ARVALID),
    .ARREADY(m_axi_mem_1_ARREADY),
    .ARADDR(m_axi_mem_1_ARADDR),
    .ARID(m_axi_mem_1_ARID),
    .ARLEN(m_axi_mem_1_ARLEN),
    .ARSIZE(m_axi_mem_1_ARSIZE),
    .ARBURST(m_axi_mem_1_ARBURST),
    .ARLOCK(m_axi_mem_1_ARLOCK),
    .ARCACHE(m_axi_mem_1_ARCACHE),
    .ARPROT(m_axi_mem_1_ARPROT),
    .ARQOS(m_axi_mem_1_ARQOS),
    .ARREGION(m_axi_mem_1_ARREGION),
    .ARUSER(m_axi_mem_1_ARUSER),
    .RVALID(m_axi_mem_1_RVALID),
    .RREADY(m_axi_mem_1_RREADY),
    .RDATA(m_axi_mem_1_RDATA),
    .RLAST(m_axi_mem_1_RLAST),
    .RID(m_axi_mem_1_RID),
    .RUSER(m_axi_mem_1_RUSER),
    .RRESP(m_axi_mem_1_RRESP),
    .BVALID(m_axi_mem_1_BVALID),
    .BREADY(m_axi_mem_1_BREADY),
    .BRESP(m_axi_mem_1_BRESP),
    .BID(m_axi_mem_1_BID),
    .BUSER(m_axi_mem_1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(read_1_U0_m_axi_mem_1_0_ARVALID),
    .I_CH0_ARREADY(mem_1_0_ARREADY),
    .I_CH0_ARADDR(read_1_U0_m_axi_mem_1_0_ARADDR),
    .I_CH0_ARLEN(read_1_U0_m_axi_mem_1_0_ARLEN),
    .I_CH0_RVALID(mem_1_0_RVALID),
    .I_CH0_RREADY(read_1_U0_m_axi_mem_1_0_RREADY),
    .I_CH0_RDATA(mem_1_0_RDATA),
    .I_CH0_RFIFONUM(mem_1_0_RFIFONUM),
    .I_CH0_AWVALID(write_2_U0_m_axi_mem_1_0_AWVALID),
    .I_CH0_AWREADY(mem_1_0_AWREADY),
    .I_CH0_AWADDR(write_2_U0_m_axi_mem_1_0_AWADDR),
    .I_CH0_AWLEN(write_2_U0_m_axi_mem_1_0_AWLEN),
    .I_CH0_WVALID(write_2_U0_m_axi_mem_1_0_WVALID),
    .I_CH0_WREADY(mem_1_0_WREADY),
    .I_CH0_WDATA(write_2_U0_m_axi_mem_1_0_WDATA),
    .I_CH0_WSTRB(write_2_U0_m_axi_mem_1_0_WSTRB),
    .I_CH0_BVALID(mem_1_0_BVALID),
    .I_CH0_BREADY(write_2_U0_m_axi_mem_1_0_BREADY)
);

read_write_read_r read_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(read_U0_ap_start),
    .start_full_n(start_for_write_U0_full_n),
    .ap_done(read_U0_ap_done),
    .ap_continue(read_U0_ap_continue),
    .ap_idle(read_U0_ap_idle),
    .ap_ready(read_U0_ap_ready),
    .mem_0_r_c_din(read_U0_mem_0_r_c_din),
    .mem_0_r_c_full_n(mem_0_r_c_full_n),
    .mem_0_r_c_write(read_U0_mem_0_r_c_write),
    .mem_0_r_c_num_data_valid(mem_0_r_c_num_data_valid),
    .mem_0_r_c_fifo_cap(mem_0_r_c_fifo_cap),
    .m_axi_mem_0_0_AWVALID(read_U0_m_axi_mem_0_0_AWVALID),
    .m_axi_mem_0_0_AWREADY(1'b0),
    .m_axi_mem_0_0_AWADDR(read_U0_m_axi_mem_0_0_AWADDR),
    .m_axi_mem_0_0_AWID(read_U0_m_axi_mem_0_0_AWID),
    .m_axi_mem_0_0_AWLEN(read_U0_m_axi_mem_0_0_AWLEN),
    .m_axi_mem_0_0_AWSIZE(read_U0_m_axi_mem_0_0_AWSIZE),
    .m_axi_mem_0_0_AWBURST(read_U0_m_axi_mem_0_0_AWBURST),
    .m_axi_mem_0_0_AWLOCK(read_U0_m_axi_mem_0_0_AWLOCK),
    .m_axi_mem_0_0_AWCACHE(read_U0_m_axi_mem_0_0_AWCACHE),
    .m_axi_mem_0_0_AWPROT(read_U0_m_axi_mem_0_0_AWPROT),
    .m_axi_mem_0_0_AWQOS(read_U0_m_axi_mem_0_0_AWQOS),
    .m_axi_mem_0_0_AWREGION(read_U0_m_axi_mem_0_0_AWREGION),
    .m_axi_mem_0_0_AWUSER(read_U0_m_axi_mem_0_0_AWUSER),
    .m_axi_mem_0_0_WVALID(read_U0_m_axi_mem_0_0_WVALID),
    .m_axi_mem_0_0_WREADY(1'b0),
    .m_axi_mem_0_0_WDATA(read_U0_m_axi_mem_0_0_WDATA),
    .m_axi_mem_0_0_WSTRB(read_U0_m_axi_mem_0_0_WSTRB),
    .m_axi_mem_0_0_WLAST(read_U0_m_axi_mem_0_0_WLAST),
    .m_axi_mem_0_0_WID(read_U0_m_axi_mem_0_0_WID),
    .m_axi_mem_0_0_WUSER(read_U0_m_axi_mem_0_0_WUSER),
    .m_axi_mem_0_0_ARVALID(read_U0_m_axi_mem_0_0_ARVALID),
    .m_axi_mem_0_0_ARREADY(mem_0_0_ARREADY),
    .m_axi_mem_0_0_ARADDR(read_U0_m_axi_mem_0_0_ARADDR),
    .m_axi_mem_0_0_ARID(read_U0_m_axi_mem_0_0_ARID),
    .m_axi_mem_0_0_ARLEN(read_U0_m_axi_mem_0_0_ARLEN),
    .m_axi_mem_0_0_ARSIZE(read_U0_m_axi_mem_0_0_ARSIZE),
    .m_axi_mem_0_0_ARBURST(read_U0_m_axi_mem_0_0_ARBURST),
    .m_axi_mem_0_0_ARLOCK(read_U0_m_axi_mem_0_0_ARLOCK),
    .m_axi_mem_0_0_ARCACHE(read_U0_m_axi_mem_0_0_ARCACHE),
    .m_axi_mem_0_0_ARPROT(read_U0_m_axi_mem_0_0_ARPROT),
    .m_axi_mem_0_0_ARQOS(read_U0_m_axi_mem_0_0_ARQOS),
    .m_axi_mem_0_0_ARREGION(read_U0_m_axi_mem_0_0_ARREGION),
    .m_axi_mem_0_0_ARUSER(read_U0_m_axi_mem_0_0_ARUSER),
    .m_axi_mem_0_0_RVALID(mem_0_0_RVALID),
    .m_axi_mem_0_0_RREADY(read_U0_m_axi_mem_0_0_RREADY),
    .m_axi_mem_0_0_RDATA(mem_0_0_RDATA),
    .m_axi_mem_0_0_RLAST(mem_0_0_RLAST),
    .m_axi_mem_0_0_RID(mem_0_0_RID),
    .m_axi_mem_0_0_RFIFONUM(mem_0_0_RFIFONUM),
    .m_axi_mem_0_0_RUSER(mem_0_0_RUSER),
    .m_axi_mem_0_0_RRESP(mem_0_0_RRESP),
    .m_axi_mem_0_0_BVALID(1'b0),
    .m_axi_mem_0_0_BREADY(read_U0_m_axi_mem_0_0_BREADY),
    .m_axi_mem_0_0_BRESP(2'd0),
    .m_axi_mem_0_0_BID(1'd0),
    .m_axi_mem_0_0_BUSER(1'd0),
    .stream_0_din(read_U0_stream_0_din),
    .stream_0_full_n(stream_full_n),
    .stream_0_write(read_U0_stream_0_write),
    .stream_0_num_data_valid(stream_num_data_valid),
    .stream_0_fifo_cap(stream_fifo_cap),
    .start_out(read_U0_start_out),
    .start_write(read_U0_start_write),
    .mem(mem_0_r)
);

read_write_read_1 read_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(read_1_U0_ap_start),
    .start_full_n(start_for_write_2_U0_full_n),
    .ap_done(read_1_U0_ap_done),
    .ap_continue(read_1_U0_ap_continue),
    .ap_idle(read_1_U0_ap_idle),
    .ap_ready(read_1_U0_ap_ready),
    .mem_1_r_c_din(read_1_U0_mem_1_r_c_din),
    .mem_1_r_c_full_n(mem_1_r_c_full_n),
    .mem_1_r_c_write(read_1_U0_mem_1_r_c_write),
    .mem_1_r_c_num_data_valid(mem_1_r_c_num_data_valid),
    .mem_1_r_c_fifo_cap(mem_1_r_c_fifo_cap),
    .m_axi_mem_1_0_AWVALID(read_1_U0_m_axi_mem_1_0_AWVALID),
    .m_axi_mem_1_0_AWREADY(1'b0),
    .m_axi_mem_1_0_AWADDR(read_1_U0_m_axi_mem_1_0_AWADDR),
    .m_axi_mem_1_0_AWID(read_1_U0_m_axi_mem_1_0_AWID),
    .m_axi_mem_1_0_AWLEN(read_1_U0_m_axi_mem_1_0_AWLEN),
    .m_axi_mem_1_0_AWSIZE(read_1_U0_m_axi_mem_1_0_AWSIZE),
    .m_axi_mem_1_0_AWBURST(read_1_U0_m_axi_mem_1_0_AWBURST),
    .m_axi_mem_1_0_AWLOCK(read_1_U0_m_axi_mem_1_0_AWLOCK),
    .m_axi_mem_1_0_AWCACHE(read_1_U0_m_axi_mem_1_0_AWCACHE),
    .m_axi_mem_1_0_AWPROT(read_1_U0_m_axi_mem_1_0_AWPROT),
    .m_axi_mem_1_0_AWQOS(read_1_U0_m_axi_mem_1_0_AWQOS),
    .m_axi_mem_1_0_AWREGION(read_1_U0_m_axi_mem_1_0_AWREGION),
    .m_axi_mem_1_0_AWUSER(read_1_U0_m_axi_mem_1_0_AWUSER),
    .m_axi_mem_1_0_WVALID(read_1_U0_m_axi_mem_1_0_WVALID),
    .m_axi_mem_1_0_WREADY(1'b0),
    .m_axi_mem_1_0_WDATA(read_1_U0_m_axi_mem_1_0_WDATA),
    .m_axi_mem_1_0_WSTRB(read_1_U0_m_axi_mem_1_0_WSTRB),
    .m_axi_mem_1_0_WLAST(read_1_U0_m_axi_mem_1_0_WLAST),
    .m_axi_mem_1_0_WID(read_1_U0_m_axi_mem_1_0_WID),
    .m_axi_mem_1_0_WUSER(read_1_U0_m_axi_mem_1_0_WUSER),
    .m_axi_mem_1_0_ARVALID(read_1_U0_m_axi_mem_1_0_ARVALID),
    .m_axi_mem_1_0_ARREADY(mem_1_0_ARREADY),
    .m_axi_mem_1_0_ARADDR(read_1_U0_m_axi_mem_1_0_ARADDR),
    .m_axi_mem_1_0_ARID(read_1_U0_m_axi_mem_1_0_ARID),
    .m_axi_mem_1_0_ARLEN(read_1_U0_m_axi_mem_1_0_ARLEN),
    .m_axi_mem_1_0_ARSIZE(read_1_U0_m_axi_mem_1_0_ARSIZE),
    .m_axi_mem_1_0_ARBURST(read_1_U0_m_axi_mem_1_0_ARBURST),
    .m_axi_mem_1_0_ARLOCK(read_1_U0_m_axi_mem_1_0_ARLOCK),
    .m_axi_mem_1_0_ARCACHE(read_1_U0_m_axi_mem_1_0_ARCACHE),
    .m_axi_mem_1_0_ARPROT(read_1_U0_m_axi_mem_1_0_ARPROT),
    .m_axi_mem_1_0_ARQOS(read_1_U0_m_axi_mem_1_0_ARQOS),
    .m_axi_mem_1_0_ARREGION(read_1_U0_m_axi_mem_1_0_ARREGION),
    .m_axi_mem_1_0_ARUSER(read_1_U0_m_axi_mem_1_0_ARUSER),
    .m_axi_mem_1_0_RVALID(mem_1_0_RVALID),
    .m_axi_mem_1_0_RREADY(read_1_U0_m_axi_mem_1_0_RREADY),
    .m_axi_mem_1_0_RDATA(mem_1_0_RDATA),
    .m_axi_mem_1_0_RLAST(mem_1_0_RLAST),
    .m_axi_mem_1_0_RID(mem_1_0_RID),
    .m_axi_mem_1_0_RFIFONUM(mem_1_0_RFIFONUM),
    .m_axi_mem_1_0_RUSER(mem_1_0_RUSER),
    .m_axi_mem_1_0_RRESP(mem_1_0_RRESP),
    .m_axi_mem_1_0_BVALID(1'b0),
    .m_axi_mem_1_0_BREADY(read_1_U0_m_axi_mem_1_0_BREADY),
    .m_axi_mem_1_0_BRESP(2'd0),
    .m_axi_mem_1_0_BID(1'd0),
    .m_axi_mem_1_0_BUSER(1'd0),
    .stream_1_din(read_1_U0_stream_1_din),
    .stream_1_full_n(stream_1_full_n),
    .stream_1_write(read_1_U0_stream_1_write),
    .stream_1_num_data_valid(stream_1_num_data_valid),
    .stream_1_fifo_cap(stream_1_fifo_cap),
    .start_out(read_1_U0_start_out),
    .start_write(read_1_U0_start_write),
    .mem(mem_1_r)
);

read_write_write_r write_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(write_U0_ap_start),
    .ap_done(write_U0_ap_done),
    .ap_continue(write_U0_ap_continue),
    .ap_idle(write_U0_ap_idle),
    .ap_ready(write_U0_ap_ready),
    .m_axi_mem_0_0_AWVALID(write_U0_m_axi_mem_0_0_AWVALID),
    .m_axi_mem_0_0_AWREADY(mem_0_0_AWREADY),
    .m_axi_mem_0_0_AWADDR(write_U0_m_axi_mem_0_0_AWADDR),
    .m_axi_mem_0_0_AWID(write_U0_m_axi_mem_0_0_AWID),
    .m_axi_mem_0_0_AWLEN(write_U0_m_axi_mem_0_0_AWLEN),
    .m_axi_mem_0_0_AWSIZE(write_U0_m_axi_mem_0_0_AWSIZE),
    .m_axi_mem_0_0_AWBURST(write_U0_m_axi_mem_0_0_AWBURST),
    .m_axi_mem_0_0_AWLOCK(write_U0_m_axi_mem_0_0_AWLOCK),
    .m_axi_mem_0_0_AWCACHE(write_U0_m_axi_mem_0_0_AWCACHE),
    .m_axi_mem_0_0_AWPROT(write_U0_m_axi_mem_0_0_AWPROT),
    .m_axi_mem_0_0_AWQOS(write_U0_m_axi_mem_0_0_AWQOS),
    .m_axi_mem_0_0_AWREGION(write_U0_m_axi_mem_0_0_AWREGION),
    .m_axi_mem_0_0_AWUSER(write_U0_m_axi_mem_0_0_AWUSER),
    .m_axi_mem_0_0_WVALID(write_U0_m_axi_mem_0_0_WVALID),
    .m_axi_mem_0_0_WREADY(mem_0_0_WREADY),
    .m_axi_mem_0_0_WDATA(write_U0_m_axi_mem_0_0_WDATA),
    .m_axi_mem_0_0_WSTRB(write_U0_m_axi_mem_0_0_WSTRB),
    .m_axi_mem_0_0_WLAST(write_U0_m_axi_mem_0_0_WLAST),
    .m_axi_mem_0_0_WID(write_U0_m_axi_mem_0_0_WID),
    .m_axi_mem_0_0_WUSER(write_U0_m_axi_mem_0_0_WUSER),
    .m_axi_mem_0_0_ARVALID(write_U0_m_axi_mem_0_0_ARVALID),
    .m_axi_mem_0_0_ARREADY(1'b0),
    .m_axi_mem_0_0_ARADDR(write_U0_m_axi_mem_0_0_ARADDR),
    .m_axi_mem_0_0_ARID(write_U0_m_axi_mem_0_0_ARID),
    .m_axi_mem_0_0_ARLEN(write_U0_m_axi_mem_0_0_ARLEN),
    .m_axi_mem_0_0_ARSIZE(write_U0_m_axi_mem_0_0_ARSIZE),
    .m_axi_mem_0_0_ARBURST(write_U0_m_axi_mem_0_0_ARBURST),
    .m_axi_mem_0_0_ARLOCK(write_U0_m_axi_mem_0_0_ARLOCK),
    .m_axi_mem_0_0_ARCACHE(write_U0_m_axi_mem_0_0_ARCACHE),
    .m_axi_mem_0_0_ARPROT(write_U0_m_axi_mem_0_0_ARPROT),
    .m_axi_mem_0_0_ARQOS(write_U0_m_axi_mem_0_0_ARQOS),
    .m_axi_mem_0_0_ARREGION(write_U0_m_axi_mem_0_0_ARREGION),
    .m_axi_mem_0_0_ARUSER(write_U0_m_axi_mem_0_0_ARUSER),
    .m_axi_mem_0_0_RVALID(1'b0),
    .m_axi_mem_0_0_RREADY(write_U0_m_axi_mem_0_0_RREADY),
    .m_axi_mem_0_0_RDATA(512'd0),
    .m_axi_mem_0_0_RLAST(1'b0),
    .m_axi_mem_0_0_RID(1'd0),
    .m_axi_mem_0_0_RFIFONUM(5'd0),
    .m_axi_mem_0_0_RUSER(1'd0),
    .m_axi_mem_0_0_RRESP(2'd0),
    .m_axi_mem_0_0_BVALID(mem_0_0_BVALID),
    .m_axi_mem_0_0_BREADY(write_U0_m_axi_mem_0_0_BREADY),
    .m_axi_mem_0_0_BRESP(mem_0_0_BRESP),
    .m_axi_mem_0_0_BID(mem_0_0_BID),
    .m_axi_mem_0_0_BUSER(mem_0_0_BUSER),
    .mem_dout(mem_0_r_c_dout),
    .mem_empty_n(mem_0_r_c_empty_n),
    .mem_read(write_U0_mem_read),
    .mem_num_data_valid(mem_0_r_c_num_data_valid),
    .mem_fifo_cap(mem_0_r_c_fifo_cap),
    .stream_0_dout(stream_dout),
    .stream_0_empty_n(stream_empty_n),
    .stream_0_read(write_U0_stream_0_read),
    .stream_0_num_data_valid(stream_num_data_valid),
    .stream_0_fifo_cap(stream_fifo_cap)
);

read_write_write_2 write_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(write_2_U0_ap_start),
    .ap_done(write_2_U0_ap_done),
    .ap_continue(write_2_U0_ap_continue),
    .ap_idle(write_2_U0_ap_idle),
    .ap_ready(write_2_U0_ap_ready),
    .m_axi_mem_1_0_AWVALID(write_2_U0_m_axi_mem_1_0_AWVALID),
    .m_axi_mem_1_0_AWREADY(mem_1_0_AWREADY),
    .m_axi_mem_1_0_AWADDR(write_2_U0_m_axi_mem_1_0_AWADDR),
    .m_axi_mem_1_0_AWID(write_2_U0_m_axi_mem_1_0_AWID),
    .m_axi_mem_1_0_AWLEN(write_2_U0_m_axi_mem_1_0_AWLEN),
    .m_axi_mem_1_0_AWSIZE(write_2_U0_m_axi_mem_1_0_AWSIZE),
    .m_axi_mem_1_0_AWBURST(write_2_U0_m_axi_mem_1_0_AWBURST),
    .m_axi_mem_1_0_AWLOCK(write_2_U0_m_axi_mem_1_0_AWLOCK),
    .m_axi_mem_1_0_AWCACHE(write_2_U0_m_axi_mem_1_0_AWCACHE),
    .m_axi_mem_1_0_AWPROT(write_2_U0_m_axi_mem_1_0_AWPROT),
    .m_axi_mem_1_0_AWQOS(write_2_U0_m_axi_mem_1_0_AWQOS),
    .m_axi_mem_1_0_AWREGION(write_2_U0_m_axi_mem_1_0_AWREGION),
    .m_axi_mem_1_0_AWUSER(write_2_U0_m_axi_mem_1_0_AWUSER),
    .m_axi_mem_1_0_WVALID(write_2_U0_m_axi_mem_1_0_WVALID),
    .m_axi_mem_1_0_WREADY(mem_1_0_WREADY),
    .m_axi_mem_1_0_WDATA(write_2_U0_m_axi_mem_1_0_WDATA),
    .m_axi_mem_1_0_WSTRB(write_2_U0_m_axi_mem_1_0_WSTRB),
    .m_axi_mem_1_0_WLAST(write_2_U0_m_axi_mem_1_0_WLAST),
    .m_axi_mem_1_0_WID(write_2_U0_m_axi_mem_1_0_WID),
    .m_axi_mem_1_0_WUSER(write_2_U0_m_axi_mem_1_0_WUSER),
    .m_axi_mem_1_0_ARVALID(write_2_U0_m_axi_mem_1_0_ARVALID),
    .m_axi_mem_1_0_ARREADY(1'b0),
    .m_axi_mem_1_0_ARADDR(write_2_U0_m_axi_mem_1_0_ARADDR),
    .m_axi_mem_1_0_ARID(write_2_U0_m_axi_mem_1_0_ARID),
    .m_axi_mem_1_0_ARLEN(write_2_U0_m_axi_mem_1_0_ARLEN),
    .m_axi_mem_1_0_ARSIZE(write_2_U0_m_axi_mem_1_0_ARSIZE),
    .m_axi_mem_1_0_ARBURST(write_2_U0_m_axi_mem_1_0_ARBURST),
    .m_axi_mem_1_0_ARLOCK(write_2_U0_m_axi_mem_1_0_ARLOCK),
    .m_axi_mem_1_0_ARCACHE(write_2_U0_m_axi_mem_1_0_ARCACHE),
    .m_axi_mem_1_0_ARPROT(write_2_U0_m_axi_mem_1_0_ARPROT),
    .m_axi_mem_1_0_ARQOS(write_2_U0_m_axi_mem_1_0_ARQOS),
    .m_axi_mem_1_0_ARREGION(write_2_U0_m_axi_mem_1_0_ARREGION),
    .m_axi_mem_1_0_ARUSER(write_2_U0_m_axi_mem_1_0_ARUSER),
    .m_axi_mem_1_0_RVALID(1'b0),
    .m_axi_mem_1_0_RREADY(write_2_U0_m_axi_mem_1_0_RREADY),
    .m_axi_mem_1_0_RDATA(512'd0),
    .m_axi_mem_1_0_RLAST(1'b0),
    .m_axi_mem_1_0_RID(1'd0),
    .m_axi_mem_1_0_RFIFONUM(5'd0),
    .m_axi_mem_1_0_RUSER(1'd0),
    .m_axi_mem_1_0_RRESP(2'd0),
    .m_axi_mem_1_0_BVALID(mem_1_0_BVALID),
    .m_axi_mem_1_0_BREADY(write_2_U0_m_axi_mem_1_0_BREADY),
    .m_axi_mem_1_0_BRESP(mem_1_0_BRESP),
    .m_axi_mem_1_0_BID(mem_1_0_BID),
    .m_axi_mem_1_0_BUSER(mem_1_0_BUSER),
    .mem_dout(mem_1_r_c_dout),
    .mem_empty_n(mem_1_r_c_empty_n),
    .mem_read(write_2_U0_mem_read),
    .mem_num_data_valid(mem_1_r_c_num_data_valid),
    .mem_fifo_cap(mem_1_r_c_fifo_cap),
    .stream_1_dout(stream_1_dout),
    .stream_1_empty_n(stream_1_empty_n),
    .stream_1_read(write_2_U0_stream_1_read),
    .stream_1_num_data_valid(stream_1_num_data_valid),
    .stream_1_fifo_cap(stream_1_fifo_cap)
);

read_write_fifo_w32_d2_S stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_U0_stream_0_din),
    .if_full_n(stream_full_n),
    .if_write(read_U0_stream_0_write),
    .if_dout(stream_dout),
    .if_empty_n(stream_empty_n),
    .if_read(write_U0_stream_0_read),
    .if_num_data_valid(stream_num_data_valid),
    .if_fifo_cap(stream_fifo_cap)
);

read_write_fifo_w64_d2_S mem_0_r_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_U0_mem_0_r_c_din),
    .if_full_n(mem_0_r_c_full_n),
    .if_write(read_U0_mem_0_r_c_write),
    .if_dout(mem_0_r_c_dout),
    .if_empty_n(mem_0_r_c_empty_n),
    .if_read(write_U0_mem_read),
    .if_num_data_valid(mem_0_r_c_num_data_valid),
    .if_fifo_cap(mem_0_r_c_fifo_cap)
);

read_write_fifo_w32_d2_S stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_1_U0_stream_1_din),
    .if_full_n(stream_1_full_n),
    .if_write(read_1_U0_stream_1_write),
    .if_dout(stream_1_dout),
    .if_empty_n(stream_1_empty_n),
    .if_read(write_2_U0_stream_1_read),
    .if_num_data_valid(stream_1_num_data_valid),
    .if_fifo_cap(stream_1_fifo_cap)
);

read_write_fifo_w64_d2_S mem_1_r_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_1_U0_mem_1_r_c_din),
    .if_full_n(mem_1_r_c_full_n),
    .if_write(read_1_U0_mem_1_r_c_write),
    .if_dout(mem_1_r_c_dout),
    .if_empty_n(mem_1_r_c_empty_n),
    .if_read(write_2_U0_mem_read),
    .if_num_data_valid(mem_1_r_c_num_data_valid),
    .if_fifo_cap(mem_1_r_c_fifo_cap)
);

read_write_start_for_write_U0 start_for_write_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write_U0_din),
    .if_full_n(start_for_write_U0_full_n),
    .if_write(read_U0_start_write),
    .if_dout(start_for_write_U0_dout),
    .if_empty_n(start_for_write_U0_empty_n),
    .if_read(write_U0_ap_ready)
);

read_write_start_for_write_2_U0 start_for_write_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write_2_U0_din),
    .if_full_n(start_for_write_2_U0_full_n),
    .if_write(read_1_U0_start_write),
    .if_dout(start_for_write_2_U0_dout),
    .if_empty_n(start_for_write_2_U0_empty_n),
    .if_read(write_2_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_read_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_1_U0_ap_ready <= ap_sync_read_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_read_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_U0_ap_ready <= ap_sync_read_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign ap_done = ap_sync_done;

assign ap_idle = (write_U0_ap_idle & write_2_U0_ap_idle & read_U0_ap_idle & read_1_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_done = (write_U0_ap_done & write_2_U0_ap_done);

assign ap_sync_read_1_U0_ap_ready = (read_1_U0_ap_ready | ap_sync_reg_read_1_U0_ap_ready);

assign ap_sync_read_U0_ap_ready = (read_U0_ap_ready | ap_sync_reg_read_U0_ap_ready);

assign ap_sync_ready = (ap_sync_read_U0_ap_ready & ap_sync_read_1_U0_ap_ready);

assign mem_0_0_BID = 1'd0;

assign mem_0_0_BRESP = 2'd0;

assign mem_0_0_BUSER = 1'd0;

assign mem_0_0_RID = 1'd0;

assign mem_0_0_RLAST = 1'b0;

assign mem_0_0_RRESP = 2'd0;

assign mem_0_0_RUSER = 1'd0;

assign mem_1_0_BID = 1'd0;

assign mem_1_0_BRESP = 2'd0;

assign mem_1_0_BUSER = 1'd0;

assign mem_1_0_RID = 1'd0;

assign mem_1_0_RLAST = 1'b0;

assign mem_1_0_RRESP = 2'd0;

assign mem_1_0_RUSER = 1'd0;

assign read_1_U0_ap_continue = 1'b1;

assign read_1_U0_ap_start = ((ap_sync_reg_read_1_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign read_U0_ap_continue = 1'b1;

assign read_U0_ap_start = ((ap_sync_reg_read_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign start_for_write_2_U0_din = 1'b1;

assign start_for_write_U0_din = 1'b1;

assign write_2_U0_ap_continue = ap_sync_continue;

assign write_2_U0_ap_start = start_for_write_2_U0_empty_n;

assign write_U0_ap_continue = ap_sync_continue;

assign write_U0_ap_start = start_for_write_U0_empty_n;

endmodule //read_write
