-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matmul_full_contiguous_matmul_full_contiguous_Pipeline_load_ab_full_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_a_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_a_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_a_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_a_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_a_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_a_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_a_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_a_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_a_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_a_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_a_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_a_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_a_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_a_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_a_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_a_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_a_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_a_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_a_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_a_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_a_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_a_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_a_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_a_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_a_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_a_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_a_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_a_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_a_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_a_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_a_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_a_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_a_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_a_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_a_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_a_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_a_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_a_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_a_0_RFIFONUM : IN STD_LOGIC_VECTOR (4 downto 0);
    m_axi_gmem_a_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_a_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_a_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_a_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_a_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_a_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_a_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_b_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_b_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_b_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_b_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_b_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_b_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_b_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_b_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_b_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_b_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_b_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_b_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_b_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_b_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_b_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_b_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_b_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_b_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_b_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_b_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_b_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_b_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_RFIFONUM : IN STD_LOGIC_VECTOR (4 downto 0);
    m_axi_gmem_b_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_b_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_b_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_b_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_b_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    B_local_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_ce0 : OUT STD_LOGIC;
    B_local_we0 : OUT STD_LOGIC;
    B_local_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_1_ce0 : OUT STD_LOGIC;
    B_local_1_we0 : OUT STD_LOGIC;
    B_local_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_2_ce0 : OUT STD_LOGIC;
    B_local_2_we0 : OUT STD_LOGIC;
    B_local_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_3_ce0 : OUT STD_LOGIC;
    B_local_3_we0 : OUT STD_LOGIC;
    B_local_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_4_ce0 : OUT STD_LOGIC;
    B_local_4_we0 : OUT STD_LOGIC;
    B_local_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_5_ce0 : OUT STD_LOGIC;
    B_local_5_we0 : OUT STD_LOGIC;
    B_local_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_6_ce0 : OUT STD_LOGIC;
    B_local_6_we0 : OUT STD_LOGIC;
    B_local_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_7_ce0 : OUT STD_LOGIC;
    B_local_7_we0 : OUT STD_LOGIC;
    B_local_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_8_ce0 : OUT STD_LOGIC;
    B_local_8_we0 : OUT STD_LOGIC;
    B_local_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_9_ce0 : OUT STD_LOGIC;
    B_local_9_we0 : OUT STD_LOGIC;
    B_local_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_10_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_10_ce0 : OUT STD_LOGIC;
    B_local_10_we0 : OUT STD_LOGIC;
    B_local_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_11_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_11_ce0 : OUT STD_LOGIC;
    B_local_11_we0 : OUT STD_LOGIC;
    B_local_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_12_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_12_ce0 : OUT STD_LOGIC;
    B_local_12_we0 : OUT STD_LOGIC;
    B_local_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_13_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_13_ce0 : OUT STD_LOGIC;
    B_local_13_we0 : OUT STD_LOGIC;
    B_local_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_14_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_14_ce0 : OUT STD_LOGIC;
    B_local_14_we0 : OUT STD_LOGIC;
    B_local_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_15_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_15_ce0 : OUT STD_LOGIC;
    B_local_15_we0 : OUT STD_LOGIC;
    B_local_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_local_16_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    B_local_16_ce0 : OUT STD_LOGIC;
    B_local_16_we0 : OUT STD_LOGIC;
    B_local_16_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_local_ce0 : OUT STD_LOGIC;
    A_local_we0 : OUT STD_LOGIC;
    A_local_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_local_1_ce0 : OUT STD_LOGIC;
    A_local_1_we0 : OUT STD_LOGIC;
    A_local_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_local_2_ce0 : OUT STD_LOGIC;
    A_local_2_we0 : OUT STD_LOGIC;
    A_local_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_local_3_ce0 : OUT STD_LOGIC;
    A_local_3_we0 : OUT STD_LOGIC;
    A_local_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_local_4_ce0 : OUT STD_LOGIC;
    A_local_4_we0 : OUT STD_LOGIC;
    A_local_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_local_5_ce0 : OUT STD_LOGIC;
    A_local_5_we0 : OUT STD_LOGIC;
    A_local_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_local_6_ce0 : OUT STD_LOGIC;
    A_local_6_we0 : OUT STD_LOGIC;
    A_local_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_local_7_ce0 : OUT STD_LOGIC;
    A_local_7_we0 : OUT STD_LOGIC;
    A_local_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    sext_ln20 : IN STD_LOGIC_VECTOR (57 downto 0);
    sext_ln20_1 : IN STD_LOGIC_VECTOR (57 downto 0) );
end;


architecture behav of matmul_full_contiguous_matmul_full_contiguous_Pipeline_load_ab_full_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv480_lc_1 : STD_LOGIC_VECTOR (479 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv9_10 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_const_lv17_1E2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000111100010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln20_reg_901 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln22_reg_913 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op50_read_state2 : BOOLEAN;
    signal ap_predicate_op52_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln20_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_b_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem_a_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal index_2_reg_895 : STD_LOGIC_VECTOR (8 downto 0);
    signal index_2_reg_895_pp0_iter1_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln20_reg_901_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln20_1_fu_603_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln20_1_reg_905 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln20_1_reg_905_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln20_3_fu_607_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln20_3_reg_909 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln22_fu_611_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln22_reg_913_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_a_addr_read_reg_917 : STD_LOGIC_VECTOR (511 downto 0);
    signal gmem_b_addr_read_reg_922 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_mux_empty_33_phi_fu_538_p4 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter2_empty_33_reg_535 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln20_1_fu_724_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_mux_empty_phi_fu_547_p4 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter2_empty_reg_544 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln20_fu_719_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln20_3_fu_782_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_2_fu_752_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_urem_fu_172 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal select_ln20_fu_683_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_phi_urem_load : STD_LOGIC_VECTOR (8 downto 0);
    signal shiftreg10_fu_176 : STD_LOGIC_VECTOR (479 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal shiftreg8_fu_180 : STD_LOGIC_VECTOR (479 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal index_fu_184 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln20_fu_593_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_index_2 : STD_LOGIC_VECTOR (8 downto 0);
    signal A_local_6_we0_local : STD_LOGIC;
    signal trunc_ln22_fu_794_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal A_local_6_ce0_local : STD_LOGIC;
    signal A_local_5_we0_local : STD_LOGIC;
    signal A_local_5_ce0_local : STD_LOGIC;
    signal A_local_4_we0_local : STD_LOGIC;
    signal A_local_4_ce0_local : STD_LOGIC;
    signal A_local_3_we0_local : STD_LOGIC;
    signal A_local_3_ce0_local : STD_LOGIC;
    signal A_local_2_we0_local : STD_LOGIC;
    signal A_local_2_ce0_local : STD_LOGIC;
    signal A_local_1_we0_local : STD_LOGIC;
    signal A_local_1_ce0_local : STD_LOGIC;
    signal A_local_we0_local : STD_LOGIC;
    signal A_local_ce0_local : STD_LOGIC;
    signal A_local_7_we0_local : STD_LOGIC;
    signal A_local_7_ce0_local : STD_LOGIC;
    signal B_local_15_we0_local : STD_LOGIC;
    signal ap_predicate_pred582_state3 : BOOLEAN;
    signal trunc_ln23_fu_816_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_local_15_ce0_local : STD_LOGIC;
    signal B_local_14_we0_local : STD_LOGIC;
    signal ap_predicate_pred596_state3 : BOOLEAN;
    signal B_local_14_ce0_local : STD_LOGIC;
    signal B_local_13_we0_local : STD_LOGIC;
    signal ap_predicate_pred609_state3 : BOOLEAN;
    signal B_local_13_ce0_local : STD_LOGIC;
    signal B_local_12_we0_local : STD_LOGIC;
    signal ap_predicate_pred622_state3 : BOOLEAN;
    signal B_local_12_ce0_local : STD_LOGIC;
    signal B_local_11_we0_local : STD_LOGIC;
    signal ap_predicate_pred635_state3 : BOOLEAN;
    signal B_local_11_ce0_local : STD_LOGIC;
    signal B_local_10_we0_local : STD_LOGIC;
    signal ap_predicate_pred648_state3 : BOOLEAN;
    signal B_local_10_ce0_local : STD_LOGIC;
    signal B_local_9_we0_local : STD_LOGIC;
    signal ap_predicate_pred661_state3 : BOOLEAN;
    signal B_local_9_ce0_local : STD_LOGIC;
    signal B_local_8_we0_local : STD_LOGIC;
    signal ap_predicate_pred674_state3 : BOOLEAN;
    signal B_local_8_ce0_local : STD_LOGIC;
    signal B_local_7_we0_local : STD_LOGIC;
    signal ap_predicate_pred687_state3 : BOOLEAN;
    signal B_local_7_ce0_local : STD_LOGIC;
    signal B_local_6_we0_local : STD_LOGIC;
    signal ap_predicate_pred700_state3 : BOOLEAN;
    signal B_local_6_ce0_local : STD_LOGIC;
    signal B_local_5_we0_local : STD_LOGIC;
    signal ap_predicate_pred713_state3 : BOOLEAN;
    signal B_local_5_ce0_local : STD_LOGIC;
    signal B_local_4_we0_local : STD_LOGIC;
    signal ap_predicate_pred726_state3 : BOOLEAN;
    signal B_local_4_ce0_local : STD_LOGIC;
    signal B_local_3_we0_local : STD_LOGIC;
    signal ap_predicate_pred739_state3 : BOOLEAN;
    signal B_local_3_ce0_local : STD_LOGIC;
    signal B_local_2_we0_local : STD_LOGIC;
    signal ap_predicate_pred752_state3 : BOOLEAN;
    signal B_local_2_ce0_local : STD_LOGIC;
    signal B_local_1_we0_local : STD_LOGIC;
    signal ap_predicate_pred765_state3 : BOOLEAN;
    signal B_local_1_ce0_local : STD_LOGIC;
    signal B_local_we0_local : STD_LOGIC;
    signal ap_predicate_pred778_state3 : BOOLEAN;
    signal B_local_ce0_local : STD_LOGIC;
    signal B_local_16_we0_local : STD_LOGIC;
    signal ap_predicate_pred820_state3 : BOOLEAN;
    signal B_local_16_ce0_local : STD_LOGIC;
    signal trunc_ln20_fu_599_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln20_1_fu_677_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln20_1_fu_671_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln20_2_fu_729_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln20_fu_736_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln20_fu_736_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln20_fu_736_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_fu_742_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal lshr_ln_fu_773_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln20_fu_736_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component matmul_full_contiguous_mul_8ns_10ns_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component matmul_full_contiguous_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_8ns_10ns_17_1_1_U1 : component matmul_full_contiguous_mul_8ns_10ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln20_fu_736_p0,
        din1 => mul_ln20_fu_736_p1,
        dout => mul_ln20_fu_736_p2);

    flow_control_loop_pipe_sequential_init_U : component matmul_full_contiguous_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    index_fu_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln20_fu_587_p2 = ap_const_lv1_0))) then 
                    index_fu_184 <= add_ln20_fu_593_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    index_fu_184 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    phi_urem_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln20_fu_587_p2 = ap_const_lv1_0))) then 
                    phi_urem_fu_172 <= select_ln20_fu_683_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_urem_fu_172 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    shiftreg10_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    shiftreg10_fu_176 <= ap_const_lv480_lc_1;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    shiftreg10_fu_176 <= ap_phi_mux_empty_phi_fu_547_p4(511 downto 32);
                end if;
            end if; 
        end if;
    end process;

    shiftreg8_fu_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    shiftreg8_fu_180 <= ap_const_lv480_lc_1;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    shiftreg8_fu_180 <= ap_phi_mux_empty_33_phi_fu_538_p4(511 downto 32);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                    ap_predicate_pred582_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_F);
                    ap_predicate_pred596_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_E);
                    ap_predicate_pred609_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_D);
                    ap_predicate_pred622_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_C);
                    ap_predicate_pred635_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_B);
                    ap_predicate_pred648_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_A);
                    ap_predicate_pred661_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_9);
                    ap_predicate_pred674_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_8);
                    ap_predicate_pred687_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_7);
                    ap_predicate_pred700_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_6);
                    ap_predicate_pred713_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_5);
                    ap_predicate_pred726_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_4);
                    ap_predicate_pred739_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_3);
                    ap_predicate_pred752_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_2);
                    ap_predicate_pred765_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_1);
                    ap_predicate_pred778_state3 <= (trunc_ln20_3_reg_909 = ap_const_lv5_0);
                    ap_predicate_pred820_state3 <= (not((trunc_ln20_3_reg_909 = ap_const_lv5_0)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_1)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_2)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_3)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_4)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_5)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_6)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_7)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_8)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_9)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_A)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_B)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_C)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_D)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_E)) and not((trunc_ln20_3_reg_909 = ap_const_lv5_F)));
                gmem_a_addr_read_reg_917 <= m_axi_gmem_a_0_RDATA;
                gmem_b_addr_read_reg_922 <= m_axi_gmem_b_0_RDATA;
                icmp_ln20_reg_901 <= icmp_ln20_fu_587_p2;
                icmp_ln20_reg_901_pp0_iter1_reg <= icmp_ln20_reg_901;
                icmp_ln22_reg_913 <= icmp_ln22_fu_611_p2;
                icmp_ln22_reg_913_pp0_iter1_reg <= icmp_ln22_reg_913;
                index_2_reg_895 <= ap_sig_allocacmp_index_2;
                index_2_reg_895_pp0_iter1_reg <= index_2_reg_895;
                trunc_ln20_1_reg_905 <= trunc_ln20_1_fu_603_p1;
                trunc_ln20_1_reg_905_pp0_iter1_reg <= trunc_ln20_1_reg_905;
                trunc_ln20_3_reg_909 <= trunc_ln20_3_fu_607_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    A_local_1_address0 <= zext_ln20_3_fu_782_p1(5 - 1 downto 0);
    A_local_1_ce0 <= A_local_1_ce0_local;

    A_local_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_1_ce0_local <= ap_const_logic_1;
        else 
            A_local_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_1_d0 <= trunc_ln22_fu_794_p1;
    A_local_1_we0 <= A_local_1_we0_local;

    A_local_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln20_1_reg_905_pp0_iter1_reg)
    begin
        if (((trunc_ln20_1_reg_905_pp0_iter1_reg = ap_const_lv3_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_1_we0_local <= ap_const_logic_1;
        else 
            A_local_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_2_address0 <= zext_ln20_3_fu_782_p1(5 - 1 downto 0);
    A_local_2_ce0 <= A_local_2_ce0_local;

    A_local_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_2_ce0_local <= ap_const_logic_1;
        else 
            A_local_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_2_d0 <= trunc_ln22_fu_794_p1;
    A_local_2_we0 <= A_local_2_we0_local;

    A_local_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln20_1_reg_905_pp0_iter1_reg)
    begin
        if (((trunc_ln20_1_reg_905_pp0_iter1_reg = ap_const_lv3_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_2_we0_local <= ap_const_logic_1;
        else 
            A_local_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_3_address0 <= zext_ln20_3_fu_782_p1(5 - 1 downto 0);
    A_local_3_ce0 <= A_local_3_ce0_local;

    A_local_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_3_ce0_local <= ap_const_logic_1;
        else 
            A_local_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_3_d0 <= trunc_ln22_fu_794_p1;
    A_local_3_we0 <= A_local_3_we0_local;

    A_local_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln20_1_reg_905_pp0_iter1_reg)
    begin
        if (((trunc_ln20_1_reg_905_pp0_iter1_reg = ap_const_lv3_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_3_we0_local <= ap_const_logic_1;
        else 
            A_local_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_4_address0 <= zext_ln20_3_fu_782_p1(5 - 1 downto 0);
    A_local_4_ce0 <= A_local_4_ce0_local;

    A_local_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_4_ce0_local <= ap_const_logic_1;
        else 
            A_local_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_4_d0 <= trunc_ln22_fu_794_p1;
    A_local_4_we0 <= A_local_4_we0_local;

    A_local_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln20_1_reg_905_pp0_iter1_reg)
    begin
        if (((trunc_ln20_1_reg_905_pp0_iter1_reg = ap_const_lv3_4) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_4_we0_local <= ap_const_logic_1;
        else 
            A_local_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_5_address0 <= zext_ln20_3_fu_782_p1(5 - 1 downto 0);
    A_local_5_ce0 <= A_local_5_ce0_local;

    A_local_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_5_ce0_local <= ap_const_logic_1;
        else 
            A_local_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_5_d0 <= trunc_ln22_fu_794_p1;
    A_local_5_we0 <= A_local_5_we0_local;

    A_local_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln20_1_reg_905_pp0_iter1_reg)
    begin
        if (((trunc_ln20_1_reg_905_pp0_iter1_reg = ap_const_lv3_5) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_5_we0_local <= ap_const_logic_1;
        else 
            A_local_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_6_address0 <= zext_ln20_3_fu_782_p1(5 - 1 downto 0);
    A_local_6_ce0 <= A_local_6_ce0_local;

    A_local_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_6_ce0_local <= ap_const_logic_1;
        else 
            A_local_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_6_d0 <= trunc_ln22_fu_794_p1;
    A_local_6_we0 <= A_local_6_we0_local;

    A_local_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln20_1_reg_905_pp0_iter1_reg)
    begin
        if (((trunc_ln20_1_reg_905_pp0_iter1_reg = ap_const_lv3_6) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_6_we0_local <= ap_const_logic_1;
        else 
            A_local_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_7_address0 <= zext_ln20_3_fu_782_p1(5 - 1 downto 0);
    A_local_7_ce0 <= A_local_7_ce0_local;

    A_local_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_7_ce0_local <= ap_const_logic_1;
        else 
            A_local_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_7_d0 <= trunc_ln22_fu_794_p1;
    A_local_7_we0 <= A_local_7_we0_local;

    A_local_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln20_1_reg_905_pp0_iter1_reg)
    begin
        if (((trunc_ln20_1_reg_905_pp0_iter1_reg = ap_const_lv3_7) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_7_we0_local <= ap_const_logic_1;
        else 
            A_local_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_address0 <= zext_ln20_3_fu_782_p1(5 - 1 downto 0);
    A_local_ce0 <= A_local_ce0_local;

    A_local_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_ce0_local <= ap_const_logic_1;
        else 
            A_local_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_local_d0 <= trunc_ln22_fu_794_p1;
    A_local_we0 <= A_local_we0_local;

    A_local_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln20_1_reg_905_pp0_iter1_reg)
    begin
        if (((trunc_ln20_1_reg_905_pp0_iter1_reg = ap_const_lv3_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_local_we0_local <= ap_const_logic_1;
        else 
            A_local_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_10_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_10_ce0 <= B_local_10_ce0_local;

    B_local_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_10_ce0_local <= ap_const_logic_1;
        else 
            B_local_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_10_d0 <= trunc_ln23_fu_816_p1;
    B_local_10_we0 <= B_local_10_we0_local;

    B_local_10_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred648_state3)
    begin
        if (((ap_predicate_pred648_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_10_we0_local <= ap_const_logic_1;
        else 
            B_local_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_11_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_11_ce0 <= B_local_11_ce0_local;

    B_local_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_11_ce0_local <= ap_const_logic_1;
        else 
            B_local_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_11_d0 <= trunc_ln23_fu_816_p1;
    B_local_11_we0 <= B_local_11_we0_local;

    B_local_11_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred635_state3)
    begin
        if (((ap_predicate_pred635_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_11_we0_local <= ap_const_logic_1;
        else 
            B_local_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_12_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_12_ce0 <= B_local_12_ce0_local;

    B_local_12_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_12_ce0_local <= ap_const_logic_1;
        else 
            B_local_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_12_d0 <= trunc_ln23_fu_816_p1;
    B_local_12_we0 <= B_local_12_we0_local;

    B_local_12_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred622_state3)
    begin
        if (((ap_predicate_pred622_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_12_we0_local <= ap_const_logic_1;
        else 
            B_local_12_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_13_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_13_ce0 <= B_local_13_ce0_local;

    B_local_13_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_13_ce0_local <= ap_const_logic_1;
        else 
            B_local_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_13_d0 <= trunc_ln23_fu_816_p1;
    B_local_13_we0 <= B_local_13_we0_local;

    B_local_13_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred609_state3)
    begin
        if (((ap_predicate_pred609_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_13_we0_local <= ap_const_logic_1;
        else 
            B_local_13_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_14_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_14_ce0 <= B_local_14_ce0_local;

    B_local_14_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_14_ce0_local <= ap_const_logic_1;
        else 
            B_local_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_14_d0 <= trunc_ln23_fu_816_p1;
    B_local_14_we0 <= B_local_14_we0_local;

    B_local_14_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred596_state3)
    begin
        if (((ap_predicate_pred596_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_14_we0_local <= ap_const_logic_1;
        else 
            B_local_14_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_15_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_15_ce0 <= B_local_15_ce0_local;

    B_local_15_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_15_ce0_local <= ap_const_logic_1;
        else 
            B_local_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_15_d0 <= trunc_ln23_fu_816_p1;
    B_local_15_we0 <= B_local_15_we0_local;

    B_local_15_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred582_state3)
    begin
        if (((ap_predicate_pred582_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_15_we0_local <= ap_const_logic_1;
        else 
            B_local_15_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_16_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_16_ce0 <= B_local_16_ce0_local;

    B_local_16_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_16_ce0_local <= ap_const_logic_1;
        else 
            B_local_16_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_16_d0 <= trunc_ln23_fu_816_p1;
    B_local_16_we0 <= B_local_16_we0_local;

    B_local_16_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred820_state3)
    begin
        if (((ap_predicate_pred820_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_16_we0_local <= ap_const_logic_1;
        else 
            B_local_16_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_1_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_1_ce0 <= B_local_1_ce0_local;

    B_local_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_1_ce0_local <= ap_const_logic_1;
        else 
            B_local_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_1_d0 <= trunc_ln23_fu_816_p1;
    B_local_1_we0 <= B_local_1_we0_local;

    B_local_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred765_state3)
    begin
        if (((ap_predicate_pred765_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_1_we0_local <= ap_const_logic_1;
        else 
            B_local_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_2_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_2_ce0 <= B_local_2_ce0_local;

    B_local_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_2_ce0_local <= ap_const_logic_1;
        else 
            B_local_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_2_d0 <= trunc_ln23_fu_816_p1;
    B_local_2_we0 <= B_local_2_we0_local;

    B_local_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred752_state3)
    begin
        if (((ap_predicate_pred752_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_2_we0_local <= ap_const_logic_1;
        else 
            B_local_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_3_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_3_ce0 <= B_local_3_ce0_local;

    B_local_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_3_ce0_local <= ap_const_logic_1;
        else 
            B_local_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_3_d0 <= trunc_ln23_fu_816_p1;
    B_local_3_we0 <= B_local_3_we0_local;

    B_local_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred739_state3)
    begin
        if (((ap_predicate_pred739_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_3_we0_local <= ap_const_logic_1;
        else 
            B_local_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_4_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_4_ce0 <= B_local_4_ce0_local;

    B_local_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_4_ce0_local <= ap_const_logic_1;
        else 
            B_local_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_4_d0 <= trunc_ln23_fu_816_p1;
    B_local_4_we0 <= B_local_4_we0_local;

    B_local_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred726_state3)
    begin
        if (((ap_predicate_pred726_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_4_we0_local <= ap_const_logic_1;
        else 
            B_local_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_5_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_5_ce0 <= B_local_5_ce0_local;

    B_local_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_5_ce0_local <= ap_const_logic_1;
        else 
            B_local_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_5_d0 <= trunc_ln23_fu_816_p1;
    B_local_5_we0 <= B_local_5_we0_local;

    B_local_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred713_state3)
    begin
        if (((ap_predicate_pred713_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_5_we0_local <= ap_const_logic_1;
        else 
            B_local_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_6_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_6_ce0 <= B_local_6_ce0_local;

    B_local_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_6_ce0_local <= ap_const_logic_1;
        else 
            B_local_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_6_d0 <= trunc_ln23_fu_816_p1;
    B_local_6_we0 <= B_local_6_we0_local;

    B_local_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred700_state3)
    begin
        if (((ap_predicate_pred700_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_6_we0_local <= ap_const_logic_1;
        else 
            B_local_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_7_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_7_ce0 <= B_local_7_ce0_local;

    B_local_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_7_ce0_local <= ap_const_logic_1;
        else 
            B_local_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_7_d0 <= trunc_ln23_fu_816_p1;
    B_local_7_we0 <= B_local_7_we0_local;

    B_local_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred687_state3)
    begin
        if (((ap_predicate_pred687_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_7_we0_local <= ap_const_logic_1;
        else 
            B_local_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_8_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_8_ce0 <= B_local_8_ce0_local;

    B_local_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_8_ce0_local <= ap_const_logic_1;
        else 
            B_local_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_8_d0 <= trunc_ln23_fu_816_p1;
    B_local_8_we0 <= B_local_8_we0_local;

    B_local_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred674_state3)
    begin
        if (((ap_predicate_pred674_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_8_we0_local <= ap_const_logic_1;
        else 
            B_local_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_9_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_9_ce0 <= B_local_9_ce0_local;

    B_local_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_9_ce0_local <= ap_const_logic_1;
        else 
            B_local_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_9_d0 <= trunc_ln23_fu_816_p1;
    B_local_9_we0 <= B_local_9_we0_local;

    B_local_9_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred661_state3)
    begin
        if (((ap_predicate_pred661_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_9_we0_local <= ap_const_logic_1;
        else 
            B_local_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_address0 <= zext_ln20_2_fu_752_p1(4 - 1 downto 0);
    B_local_ce0 <= B_local_ce0_local;

    B_local_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_ce0_local <= ap_const_logic_1;
        else 
            B_local_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_local_d0 <= trunc_ln23_fu_816_p1;
    B_local_we0 <= B_local_we0_local;

    B_local_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred778_state3)
    begin
        if (((ap_predicate_pred778_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            B_local_we0_local <= ap_const_logic_1;
        else 
            B_local_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln20_1_fu_671_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_urem_load) + unsigned(ap_const_lv9_1));
    add_ln20_fu_593_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_index_2) + unsigned(ap_const_lv9_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_gmem_a_0_RVALID, ap_predicate_op50_read_state2, m_axi_gmem_b_0_RVALID, ap_predicate_op52_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((ap_predicate_op50_read_state2 = ap_const_boolean_1) and (m_axi_gmem_a_0_RVALID = ap_const_logic_0)) or ((ap_predicate_op52_read_state2 = ap_const_boolean_1) and (m_axi_gmem_b_0_RVALID = ap_const_logic_0)));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln20_fu_587_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln20_fu_587_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_empty_33_phi_fu_538_p4_assign_proc : process(icmp_ln20_reg_901_pp0_iter1_reg, icmp_ln22_reg_913_pp0_iter1_reg, gmem_a_addr_read_reg_917, ap_phi_reg_pp0_iter2_empty_33_reg_535, zext_ln20_1_fu_724_p1)
    begin
        if ((icmp_ln20_reg_901_pp0_iter1_reg = ap_const_lv1_0)) then
            if ((icmp_ln22_reg_913_pp0_iter1_reg = ap_const_lv1_0)) then 
                ap_phi_mux_empty_33_phi_fu_538_p4 <= zext_ln20_1_fu_724_p1;
            elsif ((icmp_ln22_reg_913_pp0_iter1_reg = ap_const_lv1_1)) then 
                ap_phi_mux_empty_33_phi_fu_538_p4 <= gmem_a_addr_read_reg_917;
            else 
                ap_phi_mux_empty_33_phi_fu_538_p4 <= ap_phi_reg_pp0_iter2_empty_33_reg_535;
            end if;
        else 
            ap_phi_mux_empty_33_phi_fu_538_p4 <= ap_phi_reg_pp0_iter2_empty_33_reg_535;
        end if; 
    end process;


    ap_phi_mux_empty_phi_fu_547_p4_assign_proc : process(icmp_ln20_reg_901_pp0_iter1_reg, icmp_ln22_reg_913_pp0_iter1_reg, gmem_b_addr_read_reg_922, ap_phi_reg_pp0_iter2_empty_reg_544, zext_ln20_fu_719_p1)
    begin
        if ((icmp_ln20_reg_901_pp0_iter1_reg = ap_const_lv1_0)) then
            if ((icmp_ln22_reg_913_pp0_iter1_reg = ap_const_lv1_0)) then 
                ap_phi_mux_empty_phi_fu_547_p4 <= zext_ln20_fu_719_p1;
            elsif ((icmp_ln22_reg_913_pp0_iter1_reg = ap_const_lv1_1)) then 
                ap_phi_mux_empty_phi_fu_547_p4 <= gmem_b_addr_read_reg_922;
            else 
                ap_phi_mux_empty_phi_fu_547_p4 <= ap_phi_reg_pp0_iter2_empty_reg_544;
            end if;
        else 
            ap_phi_mux_empty_phi_fu_547_p4 <= ap_phi_reg_pp0_iter2_empty_reg_544;
        end if; 
    end process;

    ap_phi_reg_pp0_iter2_empty_33_reg_535 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter2_empty_reg_544 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op50_read_state2_assign_proc : process(icmp_ln20_reg_901, icmp_ln22_reg_913)
    begin
                ap_predicate_op50_read_state2 <= ((icmp_ln22_reg_913 = ap_const_lv1_1) and (icmp_ln20_reg_901 = ap_const_lv1_0));
    end process;


    ap_predicate_op52_read_state2_assign_proc : process(icmp_ln20_reg_901, icmp_ln22_reg_913)
    begin
                ap_predicate_op52_read_state2 <= ((icmp_ln22_reg_913 = ap_const_lv1_1) and (icmp_ln20_reg_901 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_index_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, index_fu_184)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_index_2 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_index_2 <= index_fu_184;
        end if; 
    end process;


    ap_sig_allocacmp_phi_urem_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, phi_urem_fu_172, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_phi_urem_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_phi_urem_load <= phi_urem_fu_172;
        end if; 
    end process;


    gmem_a_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_a_0_RVALID, ap_predicate_op50_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op50_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem_a_blk_n_R <= m_axi_gmem_a_0_RVALID;
        else 
            gmem_a_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    gmem_b_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_b_0_RVALID, ap_predicate_op52_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op52_read_state2 = ap_const_boolean_1))) then 
            gmem_b_blk_n_R <= m_axi_gmem_b_0_RVALID;
        else 
            gmem_b_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln20_1_fu_677_p2 <= "1" when (ap_sig_allocacmp_phi_urem_load = ap_const_lv9_10) else "0";
    icmp_ln20_fu_587_p2 <= "1" when (ap_sig_allocacmp_index_2 = ap_const_lv9_100) else "0";
    icmp_ln22_fu_611_p2 <= "1" when (trunc_ln20_fu_599_p1 = ap_const_lv4_0) else "0";
    lshr_ln_fu_773_p4 <= index_2_reg_895_pp0_iter1_reg(7 downto 3);
    m_axi_gmem_a_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_a_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_a_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_a_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_a_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_a_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_a_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_a_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_a_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_a_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_a_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_a_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_a_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_a_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_a_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_a_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_a_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_a_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_a_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_a_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_a_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_a_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_a_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_a_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_a_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_a_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op50_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op50_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem_a_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_a_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_a_0_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem_a_0_WID <= ap_const_lv1_0;
    m_axi_gmem_a_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_a_0_WSTRB <= ap_const_lv64_0;
    m_axi_gmem_a_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_a_0_WVALID <= ap_const_logic_0;
    m_axi_gmem_b_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_b_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_b_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_b_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_b_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_b_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_b_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_b_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_b_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_b_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_b_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_b_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_b_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_b_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_b_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_b_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_b_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_b_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_b_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_b_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_b_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_b_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_b_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_b_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_b_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_b_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op52_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op52_read_state2 = ap_const_boolean_1))) then 
            m_axi_gmem_b_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_b_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_b_0_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem_b_0_WID <= ap_const_lv1_0;
    m_axi_gmem_b_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_b_0_WSTRB <= ap_const_lv64_0;
    m_axi_gmem_b_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_b_0_WVALID <= ap_const_logic_0;
    mul_ln20_fu_736_p0 <= mul_ln20_fu_736_p00(8 - 1 downto 0);
    mul_ln20_fu_736_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln20_2_fu_729_p1),17));
    mul_ln20_fu_736_p1 <= ap_const_lv17_1E2(10 - 1 downto 0);
    select_ln20_fu_683_p3 <= 
        ap_const_lv9_0 when (icmp_ln20_1_fu_677_p2(0) = '1') else 
        add_ln20_1_fu_671_p2;
    tmp_fu_742_p4 <= mul_ln20_fu_736_p2(16 downto 13);
    trunc_ln20_1_fu_603_p1 <= ap_sig_allocacmp_index_2(3 - 1 downto 0);
    trunc_ln20_2_fu_729_p1 <= index_2_reg_895_pp0_iter1_reg(8 - 1 downto 0);
    trunc_ln20_3_fu_607_p1 <= ap_sig_allocacmp_phi_urem_load(5 - 1 downto 0);
    trunc_ln20_fu_599_p1 <= ap_sig_allocacmp_index_2(4 - 1 downto 0);
    trunc_ln22_fu_794_p1 <= ap_phi_mux_empty_33_phi_fu_538_p4(32 - 1 downto 0);
    trunc_ln23_fu_816_p1 <= ap_phi_mux_empty_phi_fu_547_p4(32 - 1 downto 0);
    zext_ln20_1_fu_724_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shiftreg8_fu_180),512));
    zext_ln20_2_fu_752_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_742_p4),64));
    zext_ln20_3_fu_782_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_773_p4),64));
    zext_ln20_fu_719_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shiftreg10_fu_176),512));
end behav;
